== Meditaciones y Experiencias

[.chapter-subtitle--blurb]
Publicado como un testimonio del verdadero camino hacia Dios,
revelado y dado a conocer en este Día de Su aparición gloriosa a Su pueblo,
para que sean animados a caminar en él hasta el fin.

[.centered]
__Éxodos 14:15 "`Di a los hijos de Israel que marchen.`"__

[.small-break]
'''

[.centered]
__Mateos 24:13 "`Mas el que persevere hasta el fin, éste será salvo.`"__

[.centered]
=== I. El Poder que Crucifica el Pecado

Es algo precioso conocer qué es la cruz de Cristo, y cómo tomarla y usarla;
porque en verdad, no es menos que el poder que crucifica el pecado,
y salva de él. La cristiandad generalmente es ignorante de este poder,
habiendo inventado algo más en su lugar, y por eso el pecado continúa vivo,
sin crucificarse, y no se experimenta la salvación. Porque todas las cruces de oro,
de plata y de madera, con toda la humildad voluntaria, en el mundo entero,
no pueden crucificar ni un solo pecado (en cuanto su naturaleza), ni hacer un discípulo,
ni dar la capacidad de velar una hora con Cristo,
ni de seguirlo un solo paso en la regeneración.

[.centered]
=== II. El Ojo de la Mente Abierto

Es un estado bendito sentir el ojo de la mente no solo abriéndose, sino abierto,
por el cual se experimenta una habilidad y sabiduría para leer el libro de la vida,
donde están escondidos todos los tesoros de la sabiduría y del conocimiento.
Aquel que siente esta luz brillando y este ojo abierto en su interior,
camina y no tropieza.
Este ojo y luz interior es eso que los cristianos (así llamados) desprecian y rechazan,
y por lo tanto, caminan en tinieblas y tropiezan, y no saben a dónde van.
Cuando nosotros mismos hacíamos esto, éramos tinieblas, y caminábamos en ellas,
y nuestros pies tropezaban con las montañas de oscuridad.
En el principio, aquello que cerró y detuvo este ojo, y oscureció esta luz interior,
fue el pecado y la transgresión,
y por esto la humanidad dejó de ver y de disfrutar a su Creador.
Y esto testifico,
que ninguna persona sobre la faz de la tierra puede llegar
a experimentar este ojo de la mente abierto otra vez,
salvo en la medida que experimente ese poder en sí mismo que crucifica el pecado,
y salva y redime de la transgresión, y que además sea obediente y esté sujeto al mismo.

[.centered]
=== III. La Sustancia de Todo

Recordar la obra del primer día es muy precioso,
cuando la luz fue separada de las tinieblas en nuestros corazones,
por lo cual llegamos a conocer el nombre y naturaleza de cada una.
Por esto también nuestras mentes
fueron vueltas de la oscuridad interior a luz interior;
del poder de Satanás interior al poder de Dios interior;
de los maestros y libros externos, a la gracia,
a la unción y al verdadero maestro interno.
El recuerdo de esto es muy precioso.
Y ahora solo nos queda que caminemos en esta luz,
para que seamos hijos de ella en verdad, y que siempre seamos obedientes a este poder,
y aprendamos de esta unción, hasta que hayamos aprendido plenamente.
Esta es la sustancia de todo.
Este es el fin de todas las palabras y escritos; sí,
es el fin de todas las dispensaciones de Dios desde el principio.

[.centered]
=== IV. La Naturaleza de la Bestia Asesinada

La preciosa luz que resplandece en el corazón es el Día eterno de Dios,
en el cual Él camina, y en el cual Él trabaja.
Benditos aquellos que caminan con Él, y trabajan con Él;
estos pueden contar
Sus proezas y hablar de Sus maravillosas obras.
Aquellos que caminan en esta luz, y se han convertido en hijos de este día,
conocen la verdadera y eterna adoración que es en el Espíritu y en la verdad.
Los tales han llegado a la sustancia y fin de todas
las administraciones legales y del culto del templo,
que en su mayoría consistían en matar y ofrecer diariamente becerros,
carneros y corderos, etc.
Ahora aquellos que han llegado a la adoración en
el Espíritu experimentan una muerte diaria,
y una ofrenda diaria, hasta que llegan a ser verdaderamente crucificados.
Los tales saben que es más fácil matar un becerro o un carnero externamente,
que matar o hacer morir la naturaleza de la bestia internamente.
En verdad,
es una obra mayor experimentar la voluntad totalmente entregada a la voluntad del Señor,
y los pensamientos e imaginaciones sometidos a la obediencia de la cruz,
que realizar la parte externa de la adoración ordenada en la ley.
Y yo les testifico a todos,
que aquellos que no han experimentado la naturaleza
de la bestia asesinada y ofrecida en sí mismos,
ni sus pensamientos y voluntad sometidos, no han llegado al fin de la ley,
ni han salido de debajo de ella, ni han llegado a la única ofrenda eterna--Cristo Jesús.

[.centered]
=== V. La Ley Que es Espiritual

Es muy precioso (no solo cuando nos reunimos,
sino en todo momento) sentir nuestras mentes siendo tratadas por la ley del Señor,
y meditando en ella, la cual es espiritual.
Ningún mal o tentación prevalecerá contra aquellos que están
ejercitados en esta ley del Espíritu de Vida,
y caminan en obediencia a ella; más bien,
ellos experimentarán la salvación como muros y antemuros.
Algunos en la antigüedad dieron testimonio de que la ley del Señor era pura y perfecta.
Muchos dan testimonio de lo mismo en este día, y saben que es así por su obra en ellos,
y se sienten a sí mismos sujetos a esa ley que es espiritual e interna,
la cual juzga cada pensamiento vano y cada palabra ociosa,
y derriba cada imaginación vana.
Es un estado bendito estar meditando en esta ley día y noche.
Porque yo doy testimonio de que esta ley del Espíritu de
Vida en el interior fue la regla del hombre por la cual
caminó en inocencia y rectitud antes de que entrara la transgresión,
y antes de que se inventaran las letras externas,
o antes de que existiera alguna ley externa escrita o grabada en tablas de piedra.
A esta misma ley interna muchos son llamados ahora, y muchos están llegando y han llegado.
Benditos sean por siempre aquellos que caminan en ella y son gobernados por ella.

[.centered]
=== VI. No Conociendo a Cristo Según la Carne

El verdadero conocimiento de Jesucristo es muy precioso--conocerlo
como Él era antes de que Abraham fuese,
y sentir que ese conocimiento de Él según la carne ha pasado.
Los que han llegado a esto lo conocen como el Árbol de Vida,
que crece en medio del jardín de Dios,
y ellos se sientan bajo Su sombra con gran deleite, y Su fruto es dulce a su paladar.
Los que comen de este fruto, conocen esa comida de la cual el mundo es ignorante,
y que está más allá de las palabras.
Este fruto y comer de él, ambas cosas, son mucho más que palabras.
Los tales han llegado a experimentar el cumplimiento de las promesas del evangelio,
y no necesitan que ningún hombre los enseñe. Ningún hombre necesitará decirle a su prójimo,
"`Conoce al Señor,`" porque el conocimiento de Él abunda en sus corazones.
Aquello que hace que las reuniones de los justos difieran
de todas las otras reuniones en el mundo es sentir a Jesús,
el Salvador, en medio de ellos,
y sentir sus corazones y mentes en unidad y comunión con Él. Este
sentir y conocimiento trasciende todas las palabras y religiones.
Porque, por un tiempo, hasta los discípulos de Cristo no lo conocían de esta manera,
mientras que estaba con ellos en ese "`cuerpo preparado.`"^
footnote:[Hebreos 10:5]
Por lo tanto,
un remanente puede llamar bendito a ese día en el que sus mentes
fueron convertidas de las tinieblas internas a la luz interna,
que revela y manifiesta a Cristo nuevamente,
como Él era con el Padre antes del principio del mundo,
y como Él era antes de que fuese Abraham.

[.centered]
=== VII. El Recto de Corazón

En este día se conoce, de manera tan verdadera como en la antigüedad,
que "`los ojos del Señor recorren toda la tierra,`"^
footnote:[2 Crónicas 16:9 Reina Valera 1602 Purificada]
mirando a los malos y a los buenos--es decir,
ese ojo que escudriña el corazón prueba la mente,
y le muestra al hombre sus pensamientos.
Nuestra felicidad consiste en esto:
que tenemos dentro de nosotros mismos un testimonio de que nuestros
corazones son rectos y sinceros ante la vista de estos ojos.
Esto era lo que Dios buscaba en todas las edades.
Porque cuando los judíos, su pueblo escogido, se degeneraron de la rectitud de corazón,
a pesar de que mantenían las celebraciones y observaciones externas (como guardar fiestas,
lunas nuevas y días de reposo, asambleas solemnes, matar y ofrecer sacrificios,
etc.) aun así, ningunas de estas cosas eran aceptadas, más bien eran abominables para Él,
mientras sus corazones estaban lejos de Él,
y no eran rectos ni sinceros ante la vista del ojo del Señor.

Es algo precioso sentir que nuestros corazones son rectos ante la vista del Señor,
ante sus ojos que recorren toda la tierra,
para que ese pecado que venció a los judíos de la antigüedad nunca pueda vencerlos,
a saber, guardar la forma externa y perder el poder.
Nuestras reuniones solemnes, nuestra forma de sanas palabras,
nuestra conducta externa a las que la vida de la verdad nos ha llevado, etc., en verdad,
todo es vano y sin provecho si no sentimos esta misma
vida acompañándonos y preservándonos en ello,
de modo que seamos un pueblo vivo,
caminando rectamente ante el Señor. Es el corazón honesto y recto
el que es la buena tierra donde la semilla del reino crece,
prospera y produce fruto aceptable.

[.centered]
=== VIII. Las Cosas Buenas del Reino

Es algo muy precioso experimentar una verdadera espera en el Señor. Muchas
promesas grandes y gloriosas son hechas a aquellos que esperan verdaderamente
en Él. Los que esperan en el Señor no les faltará ninguna cosa buena.
Experimentar y disfrutar esto es la sustancia de todo.
Mientras esperábamos en métodos inventados, en hombres y en libros,
en nuestros propios pensamientos e imaginaciones,
en nuestra propia sabiduría y entendimiento, carecíamos de las cosas buenas,
porque nada de esto era suficiente para llevarnos al conocimiento o disfrute de ellas.
Por esto toda la cristiandad (así llamada) puede ser probada y juzgada, es decir,
por esta única cosa: ellos pretenden una adoración y espera en el Señor,
pero carecen de las cosas buenas, y las cosas malas todavía abundan entre ellos.
En esto son hallados como testigos falsos,
que dicen esperar en el Señor pero que Él no les ha cumplido Sus promesas.
Pero un remanente en este día es testigo fiel y verdadero de que el Señor es leal,
justo y fiel a Sus promesas,
y que Él los ha provisto y revestido con los tesoros celestiales,
las cosas buenas de Su reino,
a medida que esperan verdaderamente en Él. Esta espera
no comienza cuando empiezan nuestras reuniones solemnes,
tampoco termina cuando ellas terminan, sino que siempre permanece.

[.centered]
=== IX. La Operación de la Verdad

La verdad en sí misma es muy preciosa,
y la revelación y conocimiento de ella en nuestros corazones también lo es.
Es en esta verdad que Dios es adorado con esa adoración
que es más aceptable que todas las adoraciones en el mundo,
cuyos adoradores profesan la verdad en palabras, pero no la conocen,
ni han sido librados por ella,
y por lo tanto son hallados como falsos adoradores y falsos testigos.
Porque la revelación y conocimiento de la verdad lleva a la libertad del pecado.
Da poder sobre los pensamientos vanos, sobre las pasiones,
sobre la voluntad y afectos desordenados,
y también remueve el terreno de donde brota toda maldad.
La revelación y conocimiento de esta verdad lleva a esa
justicia que es mayor que la de los escribas y fariseos;
esto limpia lo de adentro.
Todo otro conocimiento y religión en el mundo, en el mejor de los casos,
limpia solo lo de afuera; pero esto limpia lo de adentro,
y entonces lo de afuera también será limpio.

¡Oh, que lamentación se podría levantar sobre la mayor parte de la humanidad,
quienes no solamente son ajenos a la revelación y
operación poderosa de la verdad en lo íntimo,
sino que también, a través de las asechanzas del enemigo de la eterna paz de sus almas,
se ha formado en ellos una creencia de que es imposible experimentar una
limpieza interior y ser redimidos de todo mal en este lado de la tumba!
Ellos con facilidad son persuadidos a creer que el
enemigo de sus almas siempre está cerca de ellos,
listo a la mano derecha y a la mano izquierda para
desviarlos al camino por el cual no deben andar,
pero no tienen conocimiento o fe en la verdad y virtud celestial,
ni en el poder presente,
que es capaz de salvar de todas las tentaciones y de librar de las trampas de Satanás,
y así son llevados cautivos a su antojo.
Nosotros mismos estábamos en este estado,
pero ahora el conocimiento de la verdad ha llegado,
y hemos sentido su poderosa operación. Que perseveremos y caminemos en dicha operación,
para que podamos experimentar el fin de su obra, que es terminar y poner fin al pecado,
y traer la justicia perdurable.
Esta es la sustancia de todo, y el fin para el cual la Verdad se revela a sí misma.

Ahora bien,
en el sentir y disfrute presente de la revelación y conocimiento
de la operación poderosa de la verdad dentro de nuestros corazones,
no podemos evitar recordar los días pasados en los
cuales el Señor esperó para tener piedad de nosotros,
y nos persiguió con Sus misericordias y con Sus juicios,
tocando frecuentemente la puerta de nuestros corazones, y a menudo apareciéndosenos,
aunque nosotros no lo conocíamos.
En verdad Su paciencia fue muy grande,
en la cual esperó para mostrarse a Sí mismo amable y piadoso para con nosotros,
quedándose en la puerta, hasta que sus cabellos se empaparon de las gotas de la noche;^
footnote:[Cantares 5:2]
pero no lo dejamos entrar, ni recibimos Su bondad, porque ni lo conocíamos a Él,
ni Su amor.
Pero ahora Él se nos ha revelado.
Él ha abierto ese ojo que puede verlo, y ha abierto nuestros corazones para recibirlo,
y ha venido a hacer Su morada con nosotros.

¡Oh, amigos,
cómo debemos caminar como es digno de este gran amor del cual se nos ha hecho partícipes!
En verdad nosotros lo amamos a Él, porque Él nos amó primero.
Nosotros esperamos en Él, porque el esperó por nosotros primero.
Nosotros podemos decir, como dijeron algunos en la antigüedad,
"`Mirad cuál amor nos ha dado el Padre, para que seamos llamados hijos de Dios`"^
footnote:[1 Juan 3:1]
y herederos de tales preciosas promesas,
y poseedores del conocimiento de esa única verdad eterna que hace libre.
Pero amigos, aun cuando se disfruta el conocimiento de esta verdad,
existe la posibilidad de perderlo otra vez.
El Espíritu Santo que nos sella y establece en él, si es contristado, no hará Su obra;
y un pensamiento vano al que se le dé lugar lo contristará;
una palabra ociosa lo contristará. Por lo tanto,
nos concierne a todos esperar y velar en eso que
siempre preserva y mantiene fuera de todo mal,
a saber, la luz.

[.centered]
=== X. El Camino Simple

Es un estado bendito y feliz tener el testimonio dentro de nosotros mismos de que nuestras
mentes están ejercitadas en aquello en que consiste la adoración eterna y universal,
la cual no esta limitada a tiempo ni a lugar.
Esta adoración no es como las adoraciones que existen entre las sectas del mundo,
que pretenden adorar a Dios únicamente en ciertos lugares y en ciertos tiempos.
Estos piensan que Dios se complace con su supuesto servicio a Él un día a la semana,
o una hora a la semana,
a pesar de que en otros tiempos se sirven a sí mismos (y al maligno),
y hablan sus propias palabras, piensan sus propios pensamientos,
y hacen sus propias obras.
¡Oh, que tristeza siento,
cuando observo el estado del cristianismo y veo la apostasía a la que se ha degenerado,
reteniendo algo de la forma, pero negando el poder!

En esto consiste nuestra bendición y felicidad verdadera;
en tener nuestras mentes ejercitadas en la luz celestial
que lleva a la verdadera adoración eterna,
y nos preserva en ella.
Esta adoración es interna, en el Espíritu y en la Verdad,
de la cual toda la adoración en templos y en Jerusalén (realizada
externamente en ciertos tiempos y lugares prefijados),
no eran más que tipos y sombras.
Esta adoración en el Espíritu y en la Verdad es el antitipo;^
footnote:[Nota del Editor:
Un antitipo es la sustancia o cumplimiento de algo
que ha sido representado por un símbolo o sombra.]
es la sustancia de las adoraciones figurativas y temporales.
¡Oh, mis amigos,
que ninguno de nosotros sea hallado fuera de esta adoración eterna y universal,
que no empieza cuando nos reunimos a esperar en el Señor unas pocas
horas para refrescarnos juntos en el sentido de Su presencia,
ni tampoco termina cuando nos despedimos!

Y Amigos, tengo sobre mi espíritu testificar lo siguiente:
que ninguno puede disfrutar verdadera bendición y consolación espiritual
para su alma más allá del testimonio que tenga en sí mismo de que
camina en la luz preciosa y eterna que ahora resplandece.
A esta luz, en la que Dios mora, nuestras mentes fueron vueltas al principio,
y en ella se aprende y se lleva a cabo la adoración en Espíritu y en verdad,
tanto en esta era como en las pasadas.
El camino es UNO y ha sido UNO durante todas las generaciones, y es un camino simple.
"`El que anduviere en este camino, por torpe que sea, no se extraviará.`"^
footnote:[Isaías 35:8]

En esta luz, muchos ahora son testigos de que Dios los amó, aun cuando eran pecadores,
y que en los días de su oscuridad e ignorancia, Él esperaba por ellos,
para tener piedad de ellos; aunque en aquel entonces no tenían fe en Él, ni lo estimaban,
ni podían ver ninguna hermosura en Él,
siendo "`su apariencia desfigurada más que la de cualquier hombre.`"^
footnote:[Isaías 52:14 LBLA]
Así Él se les manifestaba hasta que la luz resplandeció fuera de las tinieblas,
y les dio el conocimiento de Su gloria, y a medida que caminaban en la luz,
se volvían testigos vivos de su poder obrando la salvación,
redención y translación de las tinieblas y del poder de Satanás,
a la maravillosa luz y poder de Dios.
En verdad, ellos fueron trasladados fuera de la naturaleza corrupta y estado degenerado,
a la naturaleza divina y regeneración pura;
y así se convirtieron en plantas y árboles de justicia, llevando fruto para Dios,
y dándole la gloria y alabanza de todas Sus obras,
quien solamente es digno por todas las generaciones y para siempre.

[.centered]
=== XI. Nuestro Primer Amor

Es un estado bendito vivir en el sentido y experiencia
viva de ese amor que nos visitó al principio,
en el cual nuestras mentes fueron vueltas a la luz que resplandeció en las tinieblas.
Porque en ese entonces nosotros éramos tinieblas;
pero la luz nos manifestó y reveló el don de Dios que nos fue dado,
el cual es comparado con un poco de levadura, con un grano de mostaza,
con una perla escondida en un campo.
Es precioso sentir la levadura actuando, la semilla creciendo, el campo comprado,
y la perla encontrada,
comprada y poseída. Esto es más que palabras y profesión. Ahora muchos pueden
decir (como fue testificado en la antigüedad)--"`Hemos llegado a Él,
piedra viva, escogida y preciosa,`"^
footnote:[1 Pedro 2:4]
y somos guardados por Su poder para salvación,
y estamos en Aquel en quien no hay condenación.

Por lo tanto,
leer y experimentar las Escrituras es mucho más que todas las palabras
y nociones que hay en el mundo que yace en la maldad,
donde está la culpa y la condenación. A medida que vivamos continuamente
en el sentido y experiencia de ese amor precioso que nos buscó primero,
y que arrebató a algunos de nosotros como tizones del incendio,
y a otros como puercas revolcándose en el cieno, yo digo,
a medida que permanezcamos sensibles a este amor,
sentiremos nuestros corazones cada vez más comprometidos
a caminar como es digno del mismo.
No solo profesaremos gracia, sino que viviremos bajo ella.
No solo profesaremos luz, sino que caminaremos en ella,
para que podamos ser hijos perfectos de ella.
Porque si no caminamos en la vida de lo que profesamos,
merecemos un mayor juicio que aquellos que tienen el mismo llamamiento,
pero no han gustado del poder celestial como nosotros.
Por lo tanto, nos concierne ser vigilantes, y retener nuestro primer amor.
Porque en verdad es posible, después de que la casa haya sido barrida y adornada,
y los espíritus inmundos hayan sido echados, que estos regresen y entren otra vez.
Por lo tanto, es muy precioso,
no solo experimentar ese poder bendito que echa fuera el espíritu inmundo,
y barre y adorna la casa con tesoros celestiales,
sino también morar y permanecer en dicho poder,
y ser preservado por él de ser contaminados otra vez.
Esta es la sustancia de la religión cristiana.
Este es el fin de ministrar, predicar, y escribir Esto es más que oír diez mil sermones.
Que siempre permanezcamos en el sentir de este poder, y en la obediencia al mismo,
y nunca caeremos.

[.centered]
=== XII. Preservados en Su Poder

Sentir y disfrutar eso, en lo que consiste el Reino de los cielos,
es más de lo que las palabras pueden expresar.
En las Sagradas Escrituras está escrito que el reino
de los cielos no consiste en comida ni en bebida,
ni en lavamientos externos, sino en el poder y gozo del Espíritu Santo.
Disfrutar esto es la sustancia de todo;
pero ninguno puede llegar a recibir el gozo del Espíritu Santo salvo aquellos
que son guardados por el poder en el cual consiste el reino,
cuyo poder preserva del mal y no deja que caigamos en tentación.
Muchos pueden llegar al conocimiento de este poder,
y pueden experimentarlo y tener algo de fe en él (lo cual va más
allá de muchas de las sectas tradicionales en el cristianismo),
y, sin embargo, si no viven en obediencia al mismo,
y experimentan ser guardados por él hasta el fin, no llegan a ser hijos de este reino,
ni a sentarse en él, ni a disfrutar de sus consuelos y delicias.
La mera profesión o conocimiento externo del poder de Dios tienen poco valor;
pero lo que si tiene valor es ser preservados por
él. Porque si alguno cae en el mal y en la tentación,
apaga al Espíritu Santo, y por lo tanto no puede experimentar Su gozo,
en el cual consiste el reino.
Esto es lo que nos distingue principalmente de las diversas
sectas en el cristianismo--que no solo hablamos del poder,
sino que somos preservados en él.

Está escrito en las Sagradas Escrituras de la verdad, que Cristo Jesús, el segundo Adán,
cuando fue tentado por el diablo con grandes y fuertes tentaciones, no comió nada;
mas bien, en lugar de eso, por el poder de Su Padre que moraba en Él,
resistió al diablo y a todas sus tentaciones.
Y cuando el diablo salió de Él, ángeles le ministraban.
En el día de la prueba, y en la hora de la tentación,
todos tenemos que experimentar este mismo poder que nos preserva en las tentaciones,
y que evita que comamos o recibamos el anzuelo del enemigo o tentador.
Fue el primer Adán el que comió cuando fue tentado.
Ahora bien, este comer implica tomar o dejar entrar algo;
es darle lugar al anzuelo del enemigo,
por el cual entró la tentación. Él no permaneció
en el poder en el cual consiste el reino de los cielos,
que es capaz de preservar, como lo hizo el segundo Adán. Así, al separarse de este poder,
perdió el gozo del Espíritu Santo, en el cual consiste el reino.
Y todos los hijos del primer Adán hacen lo mismo,
quienes no tienen fe en ese poder que salva de la tentación.

Esta es la sustancia de la religión cristiana,
a la cual somos llamados tanto a profesar como a experimentar, a saber,
el poder y gozo del Espíritu Santo, en el cual consiste el reino.
Este es el poder que golpea la raíz de toda iniquidad y maldad en el mundo,
y es el hacha que está puesta a la raíz del árbol
malo que ha crecido en la apostasía. Es por esto,
que el cristianismo debe ser reformado y es solamente por
medio de este poder que puede haber una verdadera reforma,
tanto en cada uno como en general.

Los Amigos son testigos vivos (y muchos podrían sellarlo con sus
vidas) de que no hay otra manera o medio designado por Dios para
llegar al reino de los cielos y sentarse en él,
o para alcanzar la salvación eterna, salvo por creer en el poder de Dios,
en la luz de Cristo en el corazón, a la cual nuestras mentes han sido dirigidas.
Es cierto que entre las muchas sectas del cristianismo
hay otros medios y caminos inventados y establecidos,
pero nosotros sabemos que todos son vanos.
Los hemos intentado y probado, y sabemos que no hay nada de valor en ellos.
Nosotros ahora hemos llegado al camino verdadero y vivo, la senda antigua,
en la cual caminaron los justos en todas las eras.
Y ahora solo nos queda esto:
que siempre sintamos nuestros corazones determinados a andar en este camino,
y a mantenernos sensibles a ese poder que salva del mal,
para que podamos adornar nuestra profesión. Porque si alguno
que profesa este camino eterno entra en tentación,
o hace mal, no adorna su profesión,
sino que la deshonra y pone una piedra de tropiezo en el camino de los demás,
que están donde nosotros estábamos cuando deambulábamos en lugares
desolados y viajábamos en la horrenda soledad de un desierto.
El día de los tales se convertirá en tinieblas,
y la maldición caerá sobre aquel que pone una piedra de tropiezo en el camino del ciego,
y lo guía fuera de su camino.

Por lo tanto, nos concierne a todos ser vigilantes, y perseverar en eso que es bueno;
ser como las luces del mundo, y como la sal de la tierra,
para que nunca dejemos de brillar ni perdamos nuestro sabor.
Porque las cosas que se escribieron, para nuestra enseñanza se escribieron,
y es provechoso meditar y considerar cómo muchos en los tiempos pasados
tuvieron una gran experiencia del poder y presencia del Señor,
vieron muchas de sus maravillas,
y viajaron a través del Mar Rojo y el desierto hasta los límites de la tierra prometida,
y, sin embargo, a causa de la murmuración y desobediencia no entraron en ella,
ni disfrutaron el fin por el cual Dios los sacó de la tierra de Egipto.
Y nosotros también podemos quedar cortos en esta era, como ellos lo hicieron,
si no caminamos cerca del Señor, y aprendemos a apercibirnos por lo que está escrito,
no sea que por desobediencia e incredulidad quedemos cortos
de recibir la gran recompensa del galardón.

[.centered]
=== XIII. El Pan del Reino

El pan del reino es el gozo del Espíritu Santo que se siente y se experimenta internamente,
el cual satisface y refresca el alma.
Este es el pan que desciende del cielo.
El pan de la proposición, en el templo externo,
era un tipo y figura de este pan espiritual, que en verdad es el antitipo y sustancia.
La mesa en el templo externo del Señor tenía un pan físico,
y a medida que sintamos que nuestros cuerpos son el templo del Señor,
disfrutaremos del pan interno, del cual el externo no era más que el tipo y sombra.
Este es el pan que llena y satisface al hambriento,
cuando las cascarás y todas las cosas externas no pueden hacerlo.

[.centered]
=== XIV. El Fundamento de Dios

Muchos en este día (como en tiempos antiguos) son testigos
vivos de que el fundamento de Dios está firme,
y que este fundamento, como ahora se ha manifestado,
ha sido el fundamento de los justos en todas las edades.
Este fundamento es en verdad, la luz, gracia y Espíritu de Dios en el corazón,
que no se mezcla con pensamientos vanos ni imaginaciones perversas,
sino que los descubre y los juzga.
Esta es la piedra que los edificadores menosprecian y rechazan en su sabiduría natural,
y recomiendan otras piedras, e inventan otros fundamentos,
según las imaginaciones de sus propios corazones.
Ahora bien, es algo bendito, y el deber de cada individuo,
sentirse a sí mismo como una piedra viva, edificada sobre este fundamento,
y sentir que su corazón y mente están unidos y conformados a él.

[.centered]
=== XV. El Maestro Interior

La misma gracia, la misma unción,
que era el maestro de los santos en los primeros tiempos,
se ha revelado y experimentado en nuestro día y tiempo.
Es algo bendito mantenerse siempre aprendiendo de Él,
porque muchos que han llegado a la revelación de este maestro,
al no esperar humildemente en eso que lo reveló (para que el yo sea despojado,
y la voluntad y el espíritu egoísta sean derribados) han sido engañados,
y han aprendido del falso maestro, el anticristo, en lugar del verdadero,
aunque bajo el nombre del verdadero.
De hecho, esto ha sucedido en algunos entre nosotros mismos,
desde que nos volvimos en un pueblo.
Porque sepan esto: que ninguna persona jamás ha adorado a la ramera,
a la madre de las rameras, a la bestia, al falso profeta y al anticristo,
llamándolos por esos nombres y denominaciones, sino que, siendo engañados,
les dieron buenos nombres y creyeron que ella era la verdadera mujer,
la esposa del Cordero, el verdadero profeta, y el verdadero Cristo.
Esta ha sido la condición de todos los apóstatas en el cristianismo.
Porque, así como el misterio de la piedad es grande,
también el misterio de la iniquidad es grande,
y no hay nadie que pueda discernir entre el uno y el otro
salvo aquellos que llegan a aprender de la gracia de Dios,
la unción interior.

Por lo tanto, es precioso aprender siempre de la gracia y unción,
y caminar en la luz a la cual nuestras mentes fueron dirigidas al principio,
porque esto revela las cosas profundas de Dios,
y escudriña los tesoros escondidos de Esaú. El recuerdo del tiempo
en que nuestras mentes fueron convertidas de los caminos,
invenciones y enseñanzas de los hombres, a la luz, gracia y unción interna,
es muy precioso;
porque por ella somos hechos partícipes de una medida de la misma
sabiduría y revelación en la que Juan escribió su libro de apocalipsis^
footnote:[El libro de Apocalipsis es llamado _Revelación_ en versiones
más antiguas de la biblia.]. Ahora el mismo Espíritu por el cual
él fue movido a ponerles nombres a las cosas según su naturaleza,
y no según la apariencia es experimentado otra vez.
La gran ramera, la bestia y el falso profeta, la copa de oro que es dada a las naciones,
el anticristo en el templo, y el gran dragón escarlata que Juan vio en el cielo,
estos ahora son revelados y comprendidos por el mismo Espíritu;
y mientras mantengamos nuestros corazones y oídos abiertos a este maestro,
nunca podremos ser engañados por estas cosas otra vez.
Todos los profesantes y sectas de nombre en el cristianismo,
que no aprenden de este maestro,
están tan engañados que creen que la ramera es la esposa del Cordero,
y que su copa de oro es la copa de bendición. De hecho,
estos están bebiendo ávidamente de ella,
sin discernir al falso profeta y anticristo del verdadero,
porque él se mete en el templo de Dios y se viste como un ángel de luz,
y como el verdadero Cristo.
Estos también confunden al gran dragón escarlata
que aparece en el cielo con el cordero de Dios.

Por lo tanto,
es algo bendito mantener siempre nuestras mentes
puestas en la luz celestial que ahora resplandece,
y nuestros pies caminando en ella,
porque ella revela al verdadero maestro que enseña y descubre todas las cosas,
y permite ver la fuente y fundamento de las cosas.
Es algo bendito discernir espíritus,
y mantenerse fuera de eso en que prevalece el misterio de la iniquidad.
Todas las enseñanzas de hombres y de libros en el mundo son solo
escoria y basura en comparación con este maestro divino--la luz,
Espíritu y gracia de Dios en el interior.
Era esto el maestro y guía del hombre antes de que los libros fuesen escritos,
antes de que una ley externa fuese escrita.
Y esto testifico en la Palabra del Señor: que las enseñanzas de todos los hombres,
libros y escritos que tienden a desviar la mente
de la humanidad de este maestro divino e interno,
son vanas e inútiles, y proceden de esa sabiduría que es terrenal, animal y diabólica.
Todos los que les prestan oído a ellas son cautivados en el ministerio de la iniquidad.
Mientras que ellos permanezcan bajo tales maestros, siempre estarán aprendiendo,
y nunca podrán llegar al conocimiento de la verdad que hace libre.
Muchos son testigos vivos de que cuando ellos se entregaron
a ser enseñados y guiados por el verdadero maestro,
la unción interior, muy pronto se volvieron más sabios que todos sus antiguos maestros.

[.centered]
=== XVI. El Antiguo Poder

El mismo poder eterno que en todas las eras pasadas guardaba a los justos del mal,
y de caer en tentaciones, ahora es revelado y experimentando en este nuestro día y era.
Este es el mismo poder y brazo de salvación que preservó a José en Egipto,
a Job en todas sus pruebas y tentaciones, a Daniel y a los tres muchachos,
y a todos los profetas y primeros cristianos en todas las ardientes pruebas,
asaltos y bofetadas de Satanás con los que se encontraron.
Por lo tanto, es algo bendito estar verdaderamente familiarizados con este poder,
y siempre vivir en el sentido de este.
Porque en verdad, es posible que las personas lleguen al conocimiento de este poder,
y lo profesen, y experimenten una gran medida de salvación y redención a través de él, y,
sin embargo,
si no esperan humildemente hasta que este poder lleve a
cabo completamente la obra de salvación y redención en ellos,
o hasta que lleve absolutamente todo pensamiento e imaginación a la obediencia de Cristo,
o someta enteramente sus propias voluntades y el espíritu egoísta,
y ellos sientan que el yo es despojado y clavado en la cruz--yo digo, sin esto,
pueden caer en la trampa del diablo otra vez,
ser cautivados y llevados nuevamente a la tentación. Porque es tras estos
que el tentador y destructor anda como león rugiente buscando devorar,
es decir,
tras aquellos de quienes él ha sido echado y desposeído. Porque está escrito
que él gobierna en los corazones de los hijos de desobediencia.
No necesita perseguir a estos, porque él ya está dentro de ellos; ahí está él en su trono.
Pero es tras los justos que él va, de quienes él ha sido echado,
quienes han sido redimidos de su poder y trasladados fuera de su reino.
Es en contra de estos que el aparece, no sólo como un león rugiente,
sino como una serpiente sutil, y como un ángel de luz.

Por lo tanto, siempre es algo bendito vivir en el sentido,
conocimiento y experiencia viva de este antiguo poder,
que es lo único que salva y redime en medio de todas las pruebas y asaltos del maligno.
Mientras que el ojo de la mente y entendimiento esté puesto en dicho poder,
ninguna tentación podrá prevalecer.
Es algo bendito que sientan la fe incrementándose en él,
porque la fe en este poder de Dios es comparada con un escudo,
que es capaz de apagar todos los dardos de fuego del diablo, y dar victoria sobre él.

Ahora bien,
aquello que era nuestra miseria y pérdida en el tiempo de nuestra ignorancia y oscuridad,
es la miseria y pérdida de la humanidad en su estado no regenerado.
No teníamos fe en el Espíritu de Dios que convence al mundo de pecado.
No creíamos que la misma mano de poder que nos golpeó por nuestro
pecado y transgresión era capaz y suficiente para sanarnos.
Tampoco considerábamos las contiendas internas del Espíritu de Dios en nosotros,
ni le prestábamos atención a Aquel que estaba a la puerta de nuestros corazones y tocaba,
quien esperó por mucho tiempo para tener piedad de nosotros.
Él era como una luz que resplandecía en las tinieblas,
pero nosotros no Le prestábamos atención,
y por lo tanto no conocíamos Su virtud ni Su poderosa
operación. En este estado de incredulidad y desobediencia,
éramos hijos de ira, lo mismo que los demás,
pero habiendo obtenido misericordia para ser fieles,
ahora hemos dejado todo el mundo que está cautivo en el estado
no regenerado a causa de su incredulidad y dureza de corazón.

Y aquí Dios muestra Su amor,
y Su abundante bondad y misericordia--en que Él nos amó cuando aún éramos enemigos,
y esperó para tener piedad de nosotros mientras éramos pecadores,
para reconciliarse con nosotros cuando éramos rebeldes a Él,
y nos iluminó cuando éramos tinieblas.
De hecho, Él frecuentemente llamaba cuando nosotros corríamos lejos de Él,
y estaba cerca y listo para enseñarnos cuando éramos
ignorantes y no deseábamos conocer Sus caminos.
En esto el abundante amor de Dios se nos manifestó en ese entonces,
y es el mismo para todo el mundo ahora.
Su amor es universal para todos, como es testificado en las Sagradas Escrituras:
de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito como una luz al mundo,
para que todo aquel que en Él crea, no se pierda, más tenga vida eterna.

Es muy precioso caminar en esta luz que revela el amor y bondad de Dios,
y lleva al conocimiento y experiencia de los medios de salvación que Él ha designado,
y a sentir ese poder que salva de caer en tentación, sí,
ese mismo poder que preservó a Jesús cuando fue tentado en el desierto.
Ahora bien, si alguno ha llegado al conocimiento y profesión de este poder,
y no es preservado de caer en tentación, ni librado del mal por dicho poder,
esta persona no está siendo obediente o fiel al mismo,
y por lo tanto no adorna su profesión. Y los que hacen esto, no glorifican el poder,
sino que son como "`manchas en nuestros ágapes,`"^
footnote:[Judas 1:12]
un escándalo para el evangelio de la paz, y enemigos de la cruz de Cristo,
la cual es el poder de Dios para Salvación. Ahora bien, aquellos que viven en este poder,
y son obedientes al mismo, son los más sabios, felices y seguros en el mundo.
Ellos son los más bendecidos de todas las familias de la tierra,
bendecidos con cien veces más en este mundo, y con la vida eterna en el mundo venidero.
Estos son la sal de la tierra que sazona todas las cosas,
son como una ciudad asentada sobre un monte, que no se puede esconder,
y como la luz del mundo en verdad.

[.centered]
=== XVII. Aquellos Que Aman Tu Ley

Muchos son testigos vivos de que la ley del Espíritu de vida (a
la cual sus mentes han sido dirigidas) es pura y perfecta.
Ellos sienten que ella es así por su operación en ellos,
por la cual es condenada toda especie de mal.
Tener al testigo o el testimonio en sí mismos de que aman esta ley,
y que meditan en ella día y noche, es la felicidad de cada individuo.
"`¡Oh,`" dijo uno de la antigüedad, "`cuánto amo yo tu ley!`"^
footnote:[Salmos 119:97]
Sólo aquellos que la aman son verdaderos testigos vivos de su pureza y perfección.
Porque es posible que una persona o pueblo no solo profese y hable de esta ley,
sino que también llegue a algún conocimiento de ella, y, sin embargo, no la ame,
ni medite en ella, ni sienta su poder y paz.

Aquellos que aman la ley de Dios son, por medio de ella,
convertidos y hechos sabios para la salvación, y aunque muchos sean sus enemigos,
y además estén muy cerca de ellos, sin embargo,
no podrán prevalecer en contra de aquellos que aman esta ley.
En verdad, estas son las personas más felices de todas las familias de la tierra.
Ningún mal puede prevalecer en su contra,
y tal como ha sido experimentado en la antigüedad,
"`los que aman Tu ley tienen mucha paz,`"^
footnote:[Salmos 119:165 Reina Valera de Gómez]
así también ahora, en esta era, hay testigos vivos de esta misma abundante paz,
quienes aman la ley, la cual es luz.
"`Tu ley es luz,`"^
footnote:[Proverbios 6:23 Reina Valera 1602 Purificada]
dijo uno.
Aquel que ama la luz, lleva sus obras a ella, para que sean probadas y juzgadas por ella;
y después de esto se experimenta mucha paz.

La paz es la recompensa de aquellos que aman la ley de Dios--paz en lo íntimo, sí,
la paz de Dios, que el mundo no puede dar ni quitar.
Esta única frase puede probar a todas las sectas del cristianismo
y a todos los demás que profesan amar la ley de Dios,
pero que no tienen paz en sus corazones.
Estos no tienen "`la respuesta de una buena conciencia,`"^
footnote:[1 Pedro 3:21 Versión Moderna - H.B. Pratt (1929)]
que se mantiene sin ofensa hacia Dios y el hombre.
No tienen esa paz que sobrepasa el entendimiento del hombre en
la caída. No sienten sus corazones y sus mentes guardados por ella,
sino que son hallados haciendo el mal, en lo cual está la tribulación y angustia,
y el temor que trae tormento.
Así que, dondequiera que se esté haciendo el mal, allí no se ama la ley,
no importa cuales sean sus palabras y su profesión.
Lo que está escrito es infaliblemente verdadero:
"`Aquel que hace lo malo, aborrece la luz,`"^
footnote:[Juan 3:20]
y aquel que aborrece la luz es un impío. En verdad, no hay paz para él,
porque la ley no es una lámpara a sus pies, ni una lumbrera a sus caminos.
Él camina en oscuridad y tropieza, y no sabe en qué; y al final, en dolor es sepultado.

Por lo tanto, es muy bueno para cada individuo no sólo conocer la ley de Dios,
sino también vivir en el sentido y amor de esta ley en todo tiempo,
tanto cuando están ocupados en sus responsabilidades comunes en el mundo,
como también en sus reuniones solemnes ante el Señor. Amar esta ley pura del
Espíritu de vida (que juzga toda especie de mal) hace sabio para la salvación,
incluso más sabio que todos los maestros anteriores.
Y escuchar,
amar y obedecer esta ley (o Palabra en el corazón) es el fin de todas las palabras,
y el fin de todas las dispensaciones y ministraciones externas,
incluso cuando estas han procedido del poder mismo de Dios.
Porque si la humanidad no se hubiera degenerado del amor
y obediencia de esta ley o mandamiento interno de Dios,
la transgresión jamás habría entrado,
ni el pecado habría tenido lugar en el corazón del hombre,
ni se habría añadido o dado una ley externa.
Porque la ley externa fue añadida a causa de las transgresiones,
y tiene poder sobre el transgresor mientras este viva en desobediencia
y como ajeno a la ley escrita en la tabla del corazón por el dedo de Dios.
De hecho, la ley interna existía antes de que alguna ley externa fuese escrita,
ya sea en un libro o en tablas de piedra,
y antes de que hubiera necesidad de dicha ley escrita.

[.centered]
=== XVIII. El Tesoro Celestial

La aurora desde lo alto, y la luz eterna ha resplandecido,
y está resplandeciendo de las tinieblas, en los corazones de muchos en esta era, y ellos,
por su resplandor celestial,
han llegado al conocimiento del campo en donde está escondido el tesoro,
y a contemplar eso cuyo valor y belleza trascienden todos
los tesoros y placeres que este mundo puede ofrecer.
Nadie debe quedar satisfecho con el simple conocimiento de este campo,
sino que debe venderlo todo y comprarlo.
Todas las sectas en el cristianismo que no creen en la luz de Cristo
en el corazón y desprecian el día de su visitación en sí mismos,
están tan lejos de disfrutar el tesoro celestial que son completamente
ignorantes del lugar o campo donde está escondido.

Esto está sellado en los corazones de un remanente: que no hay otro camino,
no hay otro medio, no hay otra llave para abrir los misterios celestiales,
ni para desatar sus sellos, ni para conducir al disfrute del tesoro celestial,
salvo esta luz divina y santa.
Esta luz ha aparecido y resplandecido gloriosamente en sus corazones,
para descubrir y destruir al hombre de pecado y al misterio de la iniquidad,
que en otro tiempo operaban y gobernaban allí. Este
remanente ha creído y caminado en esta luz,
y ha visto las maravillas del Señor en lo profundo.
Pero los pueblos y naciones que la desprecian y aborrecen, caminan y moran en tinieblas,
y en la región y sombra de muerte, donde está la pobreza, angustia y miseria.
Aquí es donde tropiezan, andan a tientas, caen y deambulan en lugares desolados,
donde el hombre trabaja por lo que no sacia y es sepultado en dolor.
Por lo tanto,
los corazones del remanente están comprometidos en gran manera con el Señor,
a caminar como es digno de las riquezas de Su gracia, luz y tesoro celestial,
del cual Él los ha hecho participantes.

[.centered]
=== XIX. El Día de Salvación

La luz del glorioso evangelio ya alumbra.
El día de salvación ha llegado, sí, la salvación de Dios,
la cual ha preparado en presencia de todos los pueblos.
Este es el día de gran salvación, que muchos hombres y profetas justos vieron de lejos,
y del cual profetizaron, y que ahora nos es revelado.
Es algo bendito, no sólo conocer la aparición del día de salvación,
sino sentir el gozo de esta, el gozo de la salvación de Dios,
y experimentarla como muros y antemuros que protegen y defienden,
no sólo del asedio externo, sino también del enemigo interno.

Esta es la luz gloriosa del Evangelio que resplandece
en este día de salvación que ahora se ha revelado,
y mientras caminemos y permanezcamos en ella,
seremos tan fuertes como un ejército en orden,
y experimentaremos la victoria sobre nuestros enemigos internos,
que son nuestros más grandes enemigos.
Ser salvados de pensar nuestros propios pensamientos,
de hablar nuestras propias palabras, y de hacer nuestras propias obras (Isaías 58:13),
es la gran salvación que lleva al verdadero día de reposo,
al verdadero modo de guardar el día santo para el Señor. Uno que disfrutaba esta salvación,
hizo esta pregunta--"`¿Cómo escaparemos nosotros,
si descuidamos una salvación tan grande?`"^
footnote:[Hebreos 2:3]
Es una pregunta que incluye una imposibilidad,
porque los que descuidan esta salvación tan grande (que ahora se
les ha manifestado) no pueden escapar de la ira venidera,
porque no hay otro camino o medio designado por Dios aparte
de esta luz del evangelio o del gran día de salvación,
que se nos ha aparecido.

Este es mi testimonio: que nadie puede recibir el gozo de la salvación de Dios,
ni entrar en el día de reposo, o guardar el día santo para el Señor,
más allá de que experimente un cese y una salvación de sus propios pensamientos,
de su propia voluntad y sabiduría. Porque los pensamientos del yo que se levantan
en el interior son la raíz del mal y el fundamento del reino de las tinieblas;
y la luz de este día de salvación es como el hacha puesta a la raíz del árbol malo.
Por lo tanto, es algo bendito para las personas reunirse y esperar juntos,
y caminar en esta luz celestial y día de salvación,
que descubre y juzga cada pensamiento vano e imaginación necia, los somete,
y los lleva cautivos a la obediencia de Cristo.
En esto (mientras caminan y permanecen en ello) se diferencian
verdaderamente de todas las demás familias de la tierra;
porque en esta luz celestial del evangelio, que juzga toda especie de mal,
está la verdadera comunión y unidad.
En verdad,
este es el fundamento de esa Iglesia contra la cual las puertas
del Hades nunca prevalecerán. Y a medida que caminen y moren allí,
el poder de la muerte y del infierno nunca los quebrantará,
sino que permanecerán como el Monte de Sion que nunca podrá ser removido.
En esto consiste su felicidad y seguridad; fuera de esto,
son tan débiles como el resto de las personas.

[.centered]
=== XX. Sentándose en el Reino.

Es algo bendito esperar la aparición de Aquel que es la consolación de Israel,
y la venida de Su reino; pero es algo aún más bendito experimentar Su aparición,
y sentir que Su reino ha llegado.
Y la mayor bendición de todas es llegar a sentarse en el reino con Él,
en la gloria de Su Padre, y nuestro Padre, Su Dios, y nuestro Dios.

[.centered]
=== XXI. La Aparición de Jesús

Es algo bendito saber verdaderamente cómo esperar la aparición de Jesús,
y reconocerlo cuando aparece.
Esto es algo muy bendito; pero es mucho más bendito, o una medida mayor de bendición,
experimentar Su aparición, y unirse a Él cuando aparece,
y así experimentar el propósito de Su aparición cumplido,
al permanecer con Él hasta que sea cumplido,
y entender verdaderamente la razón por la que Él aparece,
y nuestro estado y condición al momento de Su aparición. De hecho,
esto es lo primero y principal que hay que entender y tener en cuenta en todas las dispensaciones.
Y en todas ellas, Su aparición debe considerarse y obedecerse cuidadosamente,
aunque esté en Su primera o más baja manifestación, que es convencer de pecado,
de justicia propia y de juicio, con el fin de destruir el pecado,
terminar la prevaricación y traer la justicia perdurable.
Porque a menos que las personas permanezcan en Él y amen Su aparición en el ministerio
de condenación (el cual trae tribulación y angustia sobre el alma que ha pecado),
nunca llegarán a disfrutar ni a heredar la ministración de vida y salvación,
ni jamás llegarán a disfrutar la gloria de Su aparición "`por segunda vez,
sin relación con el pecado, para salvar.`"^
footnote:[Hebreos 9:28]

Esta es la pérdida y la miseria de la humanidad,
y fue nuestra pérdida y miseria en el día de nuestra ignorancia:
que no sabíamos cómo esperar la aparición de Cristo, o la venida del Justo.
Así como la humanidad no Lo reconoce cuando aparece,
nosotros no Lo reconocíamos cuando se nos aparecía;
porque se nos manifestaba frecuentemente,
y estaba a la puerta de nuestros corazones y tocaba,
y esperaba para tener piedad de nosotros; pero nosotros no sabiendo que era Él,
Lo ignorábamos y no Le abríamos.
Sin embargo, Él era el deseo de nuestros corazones, y Aquel que anhelábamos disfrutar.
Sí, Él es el Deseado de todas las naciones, la luz y salvación de los gentiles,
la consolación y gloria de Israel.
Pero en esto consistía nuestra pérdida y miseria:
que no sabíamos cómo esperar Su aparición, ni Lo reconocíamos cuando aparecía.

Por lo tanto, nuevamente digo,
es algo bendito que un pueblo sepa cómo esperar la aparición de Jesús el Salvador,
y cómo reconocerlo cuando aparece.
Pero he aquí, una medida más grande de bendición, a saber, experimentar Su aparición,
y sentir la venida del Justo,
o el nacimiento del Sol de Justicia trayendo salvación en sus alas,
y ser capaces de decir junto a los primeros cristianos,
"`sabemos que el Hijo de Dios ha venido,
y nos ha dado entendimiento para conocer al que es verdadero; y estamos en el verdadero,
en su Hijo Jesucristo.
Este es el verdadero Dios, y la vida eterna.`"^
footnote:[1 Juan 5:20]
En verdad, este es un conocimiento supremo y celestial, y un estado bendito.
Esta es la meta,
el premio del supremo llamamiento de Dios en Cristo Jesús al cual hemos sido llamados.
De hecho, este es el estado que todos deben esperar, heredar y poseer,
y no quedar cortos del mismo.
Si esto no se experimenta y se disfruta, toda profesión es vana,
todo conocimiento es vano,
toda religión y hablar de cristianismo es vano y sin ningún valor.
Porque solo él que cree que Cristo ha venido en la carne,
y que demuestra la vida de su fe por las obras de ella, este es de Dios; Dios mora en Él,
y él en Dios.
Esto es más que una simple profesión o confesión verbal, según el testimonio de Juan,
en su primera epístola, capítulo 4.

[.centered]
=== XXII. La Pequeña Piedra

La visión que tuvo el profeta Daniel, cuando vio la interpretación del sueño del rey,
fue espiritual y celestial.
En esta visión vio que una piedra fue cortada de la montaña, no con mano,
e hirió a la imagen en sus pies, y desmenuzó el hierro, el bronce, el barro, la plata,
el oro y se hizo un gran monte que llenó toda la tierra.
Un remanente en esta era ha llegado a la misma luz eterna y ojo
espiritual mediante el cual ven el poder de Dios (representado
por esa piedra) prevalecer contra todas las imágenes (no sólo externamente,
sino también internamente) y experimentan su fundamento conmovido y removido.
Los pensamientos e imaginaciones perversos de los hombres
son la base de las imágenes sobre la faz de la tierra,
y el poder que las quiebra,
y que lleva todo pensamiento cautivo a la obediencia a Cristo,
es el antitipo de esa piedra y de su obra,
la cual fue revelada a Daniel y con la cual soñó el rey.

En este día de luz y conocimiento algunos han llegado a sentir que esta
piedra pequeña se hace un gran monte que llena toda la tierra,
y se vuelve el fundamento principal y la piedra de ángulo, escogida y preciosa.
En verdad, esta es la roca y refugio de los justos en esta y en todas las eras.
Estos permanecen en ella, y, por lo tanto,
son preservados de hacer semejanzas e imágenes para sí mismos,
ya sea de cosas en los cielos, o de cosas abajo en la tierra,
o de las muchas mezclas prefiguradas por el hierro, el bronce, el barro,
la plata y el oro, y de contaminarse y corromperse a sí mismos con eso.
No hay otro medio de preservación,
ni de llegar a recibir la piedrecita blanca (que Juan vio en su
visión y revelación) en la cual está escrito un nombre nuevo,
el cual ninguno conoce sino aquel que lo tiene.
Este es el nombre que es mejor que el nombre de hijos e hijas.
El que lee, entienda, y le dé a Dios la gloria por siempre.

[.centered]
=== XXIII. El Camino

Esto testifico, que el camino de la vida y felicidad eternas,
el camino que lleva a sentarse en el reino de Dios con Abraham, Isaac y Jacob,
el cual fue el camino de los justos en todas las edades,
ahora se ha revelado y dado a conocer nuevamente.
Este camino es la luz verdadera y eterna que ahora resplandece, no sólo en las tinieblas,
sino también fuera de ellas.
Esta luz es aquella a la que nuestras mentes fueron dirigidas al principio,
la cual juzga toda especie de mal,
todo pensamiento vano y motivación perversa que se levante en el interior.
Y a medida que se ande en este camino, se experimentará un sentarse en el reino.
Porque hemos sido y somos llamados a heredar la sustancia,
a poseer la vida y a sentarnos con Cristo en lugares celestiales.
Por lo tanto,
es algo precioso (para todos los que conocen este camino)
perseverar y permanecer en él hasta que posean estas cosas,
cuyo camino es la luz de Cristo en el corazón, y no hay otro.
Andar en este camino (es decir,
en esta luz que juzga toda especie de mal) los distingue de todos
los profesantes de nombre sobre la faz de la tierra.

Es un estado precioso sentir la mente puesta en el Señor,
andar en Su camino, y conocer el cinturón y el freno de la verdad,
y ser ceñidos y frenados por ella.
En verdad es precioso sentir todo argumento y altivez derribados y sometidos a Cristo,
la luz y el camino.
Esto se puede experimentar ahora, así como en los tiempos pasados.
Es en los pensamientos,
voluntad e imaginaciones que el enemigo de la felicidad
del hombre entra y construye sus fortalezas,
y sólo cuando son quebradas, sometidas y destruidas por el poder de Dios en el interior,
se puede disfrutar de la paz, la quietud, y la satisfacción del alma.
Sin esto no hay posibilidad de sentarse en el reino de Dios,
ni el alma puede alcanzar o participar del torrente
de sus delicias que está a Su diestra.

[.centered]
=== XXIV. Vida y Paz

Se experimenta tan verdaderamente ahora, como en los días antiguos,
que tener una mente espiritual es vida y paz.^
footnote:[Romanos 8:6 Reina Valera 1602 Purificada, Reina Valera de Gómez]
De hecho, tener la mente puesta en el Espíritu, tener nuestras mentes,
pensamientos y voluntades ejercitados por el Espíritu de la verdad, es vida y paz;
y tener una mente carnal es muerte, dolor y angustia.
Estas cosas no sólo se leen, sino se experimentan verdaderamente,
y cada individuo puede sentir ambas mentes en su interior.

[.centered]
=== XXV. Jesús en Medio

Es cuando nos reunimos y esperamos juntos en el Espíritu,
y cuando vivimos y caminamos en el Espíritu,
que se realiza la adoración de Dios en Espíritu y en verdad,
de cuya adoración todos los cristianos de nombre sobre la faz de la tierra son ignorantes.
Aquellos que esperan y adoran en el Espíritu sienten
a Jesús en medio de ellos como su Salvador,
maestro y líder,
y a medida que Lo sigan y obedezcan (aunque apenas sea uno en una familia,
y dos en una tribu) serán como la luz del mundo, como la sal de la tierra,
y como modelos y ejemplos de justicia para todos los que los observan.

[.centered]
=== XXVI. El Brazo del Señor Revelado

Es algo precioso para cada individuo conocer el brazo derecho del Señor que trae salvación,
y experimentar ser sentado a Su diestra,
donde las ovejas se acuestan y donde el torrente de Su delicia corre suavemente,
y también beber de este torrente que alegra toda la ciudad de Dios.
Sentir este brazo del Señor, y conocerlo revelado, y llegar a sentarse a Su diestra,
es el fin, suma y sustancia de la religión cristiana.
Estos experimentan la salvación como muros y antemuros,
y son como el Monte de Sion que no puede ser movido.

[.centered]
=== XXVII. El Torrente de Delicia

Es un estado muy bendito, vivir, caminar,
reunirse y esperar siempre en eso que da libre acceso al trono de la gracia,
y que lleva a la presencia de Aquel que se sienta en él,
en cuya presencia (como algunos de la antigüedad
pudieron experimentar) está el torrente de delicias,
y a cuya diestra hay gozo para siempre.
¡Oh, todos los que prueban una sola gota de este torrente,
y participan de la medida más pequeña de este gozo,
saben que sobrepasa y que tiene mayor peso que todos los tesoros,
las delicias y los placeres que este mundo y su gloria pueden ofrecer!

[.centered]
=== XXVIII. La Atalaya de los Justos

La Luz, a la cual nuestras mentes han sido dirigidas,
era la atalaya de los justos en todas las eras,
y es la misma para los justos en esta era,
y para todas las personas sobre la faz de la tierra.
Todos los supuestos centinelas en el cristianismo, que no vigilan en esta atalaya,
vigilan en vano, y no ven nada que sea de provecho.
Esta es la palabra de la verdad para todo el cristianismo, y para todos los pueblos:
que esta luz es el único camino eterno que lleva a Él,
y que ella acondiciona y prepara para entrar al reino de los cielos,
da libre acceso a Dios y al trono de Su gracia, y lo presenta a Él sin mancha ni arruga.
Muchos han experimentado el principio de esta obra bendita,
y han recibido esa fe por la cual creen en su cumplimiento.
Y a medida que vivan y permanezcan en dicha fe, se le añadirá a esta,
la bendita experiencia de que la obra sea cumplida.

[.centered]
=== XXIX. El Poder y Suficiencia del Espíritu de la Verdad.

Es algo bueno que cada individuo mantenga un estado de espera en silencio
en el Señor. Sólo estos llegan a experimentar una obediencia a esos preceptos
divinos que quedaron grabados en las Sagradas Escrituras--"`Estad quietos,
y conoced que yo soy Dios.`"^
footnote:[Salmos 46:10]
Y, "`Calle toda carne delante de Jehová.`"^
footnote:[Zacarías 2:13]
Por lo tanto, esperar y adorar en el Espíritu celestial que lleva a la quietud,
a estar quietos y ver la salvación de Dios, al silencio de toda carne internamente,
al cese de todas las voces y movimientos del mal internamente,
y a la obediencia a la voz y poder de Dios internamente,
esto es la adoración de Dios en Espíritu y en verdad, en lo íntimo, la cual Dios ama,
a saber, adorar,
obedecer y seguir la aparición y manifestación del Espíritu de Dios internamente.
En verdad,
el mundo y sus profesantes orgullosos no conocen
esta adoración. Y en esto diferimos de todos ellos:
que nosotros somos hallados esperando y adorando en eso que calla toda
carne y lleva a estar quietos y ver la salvación de Dios.

La adoración universal de Dios consiste y se realiza en el Espíritu de la verdad,
que convence al mundo de pecado;
y yo les doy testimonio de que hay poder y suficiencia en este Espíritu,
no solo para convencer de pecado, para reprender y condenar por el pecado,
sino también para convertir, cambiar, limpiar y redimir al mundo entero de pecado,
si ellos creyeran en Él, Lo amaran, recibieran y obedecieran.
Esta es la condenación del mundo: que la luz ha venido al mundo,
y los hombres aman las tinieblas y no llevan sus obras a la luz, ni la aman,
ni creen ni caminan en ella.
Y de esta manera los dichos de Cristo son confirmados en ellos,
"`Si no creéis que Yo soy, en vuestros pecados moriréis,`"^
footnote:[Juan 8:24]
y, "`a donde Yo voy, vosotros no podéis venir.`"^
footnote:[Juan 8:21]

Muchos han experimentado el poder y suficiencia de este Espíritu de la verdad,
y Su poder que redime del pecado y de la fortaleza de este.
Estos no necesitan ser convencidos del pecado, como el resto del mundo que vive en él,
sino que, siendo redimidos de cometer pecado,
conocen a este Espíritu como su consolador y guía hacia toda verdad.
Es muy precioso ser hallados en el estado de discípulos verdaderos,
esperando el consuelo y guía del Espíritu de la verdad,
y experimentando lo mismo dentro de sí mismos.

Un remanente en este día, que ha recibido este Espíritu y seguido sus directrices,
puede decir como dijeron algunos en la antigüedad:
"`No nos hemos acercado al Monte de Sinaí donde se escucha la voz de las palabras,
donde están los truenos, los relámpagos y los terremotos, sino al monte de Sion,
a la ciudad del Dios vivo, Jerusalén la celestial,
a la compañía de muchos millares de ángeles,
a la congregación de los primogénitos que están inscritos en los cielos,
a Dios el Juez de todos, a los espíritus de los justos hechos perfectos,
a Jesús el Mediador del nuevo pacto,
y a la sangre rociada que habla mejor que la de Abel.`"^
footnote:[Hebreos 12:18-24]
Este es un estado elevado y celestial, al cual los primeros cristianos llegaron.
De hecho, incluso cuando estaban en sus tabernáculos terrenales,
ellos disfrutaron del tesoro celestial.
Estos tienen el testimonio en sí mismos de que son
habitantes y conciudadanos de esta Jerusalén celestial,
a la cual no puede entrar ninguna cosa inmunda.
Aun mientras moran en casas de barro,
ellos caminan en esta ciudad y tienen su ciudadanía en el cielo con Dios,
Cristo y los espíritus de los santos o justos hechos perfectos.
El espíritu de este mundo no puede tener esto,
aunque se vista con el nombre del cristianismo.

[.centered]
=== XXX. La Segunda Aparición de Cristo

Es un estado muy bendito,
ser hallados esperando y experimentando verdaderamente la segunda venida de Cristo,
la cual es "`sin relación con el pecado, para salvar.`"^
footnote:[Hebreos 9:28]
Porque la verdadera felicidad no consiste en haber
visto uno de los días del Hijo del Hombre,
o en ser testigos de Su primera aparición, en la cual convence y reprende por el pecado,
sino en esperar llegar a la experiencia de Su segunda venida que limpia,
salva y redime del pecado.
Es aquí donde se siente y se disfruta el gozo de la salvación de Dios.

Cristo aparece primero para convencer de pecado,
y esto es una ministración de condenación, que es gloriosa en su tiempo.
Pero hay una ministración que es mucho más gloriosa,
la cual todos deben esperar y experimentar, y no quedar cortos de ella.
Este es el premio del supremo llamamiento,
el estado supremo y celestial al que son llamados, es decir,
a experimentar la segunda venida de Cristo sin relación con el pecado,
para ser salvados y presentados al Padre sin mancha y sin arruga.
Poseer y disfrutar esto siempre ha sido el fin,
suma y sustancia de todas las dispensaciones de Dios para con la humanidad
desde la caída. Este es el fin de todas las buenas palabras y escritos,
y el fin de la primera y segunda aparición de Cristo.
Todos los hombres han pecado y han quedado cortos de la gloria de Dios,
y por lo tanto deben sentir la ministración de juicio y condenación cumplida
en y sobre ellos antes de conocer la gloria que está en ella,
y antes de que lleguen a experimentar la segunda ministración,
que es mucho más gloriosa.

Es algo precioso estar retirados internamente con el Señor,
y sentir nuestros corazones cerca de Él, esperando la aparición de Cristo,
para que cuando Él se manifieste,
"`nosotros también seamos manifestados con Él en gloria.`"^
footnote:[Colosenses 3:4]
Este es el estado supremo y celestial en el que algunos
se encontraban cuando podían decir,
"`nuestra comunión verdaderamente es con el Padre, y con su Hijo.`"^
footnote:[1 Juan 1:3]
Experimentar esto, es el banquete de manjares suculentos del cual se profetizó,
y los ríos y arroyos muy anchos que alegran la ciudad de Dios,
que es algo mucho más grande que todos los deleites que la tierra puede producir.
Este es el deleite, descanso y felicidad del alma,
que algunos disfrutaron en las eras anteriores, como lo hace un remanente en esta era,
¡alabado sea Dios para siempre!

Tener la mente puesta en el Espíritu, o tener una mente espiritual,
no sólo en nuestras reuniones solemnes, sino en todo tiempo, es nuestro deber,
y es algo muy precioso.
Al vivir así, el testimonio de uno en los primeros tiempos será hallado verdadero,
cuando dijo, "`la mente espiritual es vida y paz.`"^
footnote:[Romanos 8:6]
Aquí se quita la muerte y la angustia, se acaba la ministración de condenación,
habiendo terminado su obra.
Porque la Palabra que era como un martillo, un fuego y una espada ha quebrado, quemado,
destruido y lavado las inmundicias de las hijas de Jerusalén,
y ahora se ha convertido en leche, miel y bálsamo.
De hecho,
es como una luz gloriosa que resplandece más y más hasta que el día es perfecto,
y como un escudo, fortaleza y torre de defensa, donde hay paz y seguridad eternas,
siendo la salvación como muros y antemuros contra los cuales el enemigo no puede prevalecer,
y nada que contamine puede entrar.
En este estado estaban algunos en los tiempos antiguos, cuando podían decir,
"`Porque nada podemos contra la verdad, sino por la verdad;`"^
footnote:[2 Corintios 13:8]
y es posible decir y hacer lo mismo en este día.

[.centered]
=== XXXI. El Verdadero Pastor

Es una bendición que un hombre sienta dentro de sí mismo (y que sea capaz de
decir lo mismo a partir de una experiencia viva) eso que dijo uno de la antigüedad:
"`El Señor es mi Pastor, nada me faltará.`"^
footnote:[Salmos 23:1]
Estos experimentan la verdad de esos dichos de Cristo Jesús:
"`Mis ovejas oyen mi voz, y yo las conozco, y me siguen, y yo les doy vida eterna;
y no perecerán jamás, ni nadie las arrebatará de mi mano.`"^
footnote:[Juan 10:27-28]
Es a medida que escuchamos, obedecemos y seguimos esta voz,
que experimentamos una continua salida de ese estado donde está la falta,
y una continua entrada a los pastos verdes en donde podemos alimentarnos de forma
verdadera y segura y donde descansamos en un valle en el que no hay quien espante,
y donde el pan es seguro y las aguas no faltan.
Y esto testifico:
todos los que no escuchan ni obedecen la voz celestial
del verdadero Pastor son cabras y cerdos,
y no ovejas, independientemente de lo que ellos profesen.
Estos se alimentan de cáscaras,
y andan errantes en lugares secos y sobre montañas estériles donde están las necesidades,
y son ajenos a los pastos verdes de vida y salvación.

[.centered]
=== XXXII. Adorando en Espíritu y en Verdad

Es algo muy bendito que las personas sepan como adorar a Dios de manera correcta,
y que se encuentren en esta adoración,
no solo en tiempos prefijados y en lugares determinados,
sino en todo tiempo y en todo lugar.
Esta es la adoración espiritual, o la adoración en Espíritu y en verdad;
y estos son los adoradores espirituales que Dios busca y acepta.

Esta adoración supera todas las otras adoraciones que existen sobre la faz de la tierra,
con todos sus tiempos prefijados y lugares determinados,
que consisten en decir tantas oraciones al día,
y en leer y cantar tantas lecciones al día, y oír tantos sermones en tal día,
y otras observaciones externas.
Tal adoración consiste en tiempo, lugar, letra y forma;
pero aquellos que adoran a Dios de manera correcta, adoran en el Espíritu y en la verdad,
la cual es pura y universal.

Cuando las personas se encuentran en esta adoración verdadera,
su adoración llega a ser diferente y mejor que todas las otras sobre la faz de la tierra.
Estos adoradores saben qué es doblar rodillas ante el nombre de Jesús,
y qué es experimentar cada pensamiento llevado cautivo a la obediencia de Cristo.
Estos conocen cuál es Su dominio, gobierno y gran autoridad,
como toda potestad en el cielo y en la tierra le es dada,
y como todos deben adorarlo como adoran al Padre, ya sea que estén en los cielos,
o en la tierra, o debajo de la tierra.
Estos pueden confesar con sus lenguas que Jesucristo es el Señor,
para gloria de Dios Padre,
siendo por experiencia testigos verdaderos y vivos
de Su poder y gobierno celestial en sus corazones,
mentes y entendimientos,
dándoles victoria sobre todos los pensamientos vanos y deseos carnales,
sobre la voluntad propia y la mente errante.
Estos son los adoradores que sienten al viejo hombre despojado con sus hechos,
y que son vestidos del nuevo hombre.
Ellos sienten que las cosas viejas pasaron, y que todas las cosas son hechas nuevas,
y saben qué es disfrutar el día de reposo, donde ya no piensan sus propios pensamientos,
ni hablan sus propias palabras, ni hacen sus propias obras.
Ellos saben lo que significa no llevar carga en el día de reposo;
y qué es disfrutar la consolación de las Escrituras,
y gozar de las cosas buenas sobre las cuales ellas testifican.
Estos son partícipes de eso que disfrutaron los justos en todas las eras,
y están en unidad con los espíritus de los hombres justos, habiendo llegado a Dios,
el Juez de todos, quien es bendito para siempre.

Nuestra paz, gozo, consuelo y felicidad continua,
consiste en experimentar esta adoración sintiendo el poder de Dios,
el nombre de Jesús reinando sobre todo en nosotros mismos,
con todo inclinándose ante dicho poder, y rindiendo obediencia a él,
como era en la inocencia antes de la transgresión,
cuando la tierra estaba sujeta al dominio de Dios, y el gobierno celestial reinaba,
sobre todo.
De hecho, la verdadera adoración en el Espíritu y en la verdad lleva nuevamente a esto,
y hace libre de lo contrario, tal y como lo testifican las Escrituras:
"`conoceréis la verdad, la verdad os hará libres`"^
footnote:[Juan 8:32]
--libres del mal que está en el mundo, de los males que están en el corazón,
y de los enemigos internos, que son los enemigos más grandes.
Si no sentimos esta libertad, todo otro conocimiento es vano,
toda religión y profesión es vana, todo lo que hablemos de Dios,
de Cristo y del cristianismo es en vano.

[.centered]
=== XXXIII. Deleitándose en la Ley del Señor

Bienaventurados aquellos cuya mente y corazón están siempre siendo tratados por
eso que lleva a la comunión con "`los espíritus de los justos hechos perfectos.`"^
footnote:[Hebreos 12:23]
Estos también tienen unidad con las palabras y testimonios
que quedaron registrados en las Escrituras de la verdad,
como por ejemplo uno que está escrito en los Salmos:
"`Bienaventurado el varón que no anduvo en consejo de malos,
ni estuvo en camino de pecadores, ni en silla de escarnecedores se ha sentado;
sino que en la ley de Jehová está su delicia, y en su ley medita de día y de noche.`"^
footnote:[Salmos 1:1-2]
El mismo estado bendito debe ser experimentado en este día,
el cual es más que leer y cantar todos los Salmos;
y solo aquel que haga estas cosas es el varón bienaventurado.
Si la Cristiandad hubiera aprendido esta lección (que sin duda han leído y cantado),
no se hubieran convertido en un yermo de horrible soledad que no produce fruto para Dios.
Pero habiendo dado su oído al maligno, y andado en camino de pecadores por tanto tiempo,
han llegado a creer que es imposible andar en otro
camino mientras estén de este lado de la tumba.

Nosotros mismos estábamos en esta condición,
cuando el velo estaba puesto sobre nuestros corazones.
Nosotros habitábamos en estas densas tinieblas, en las que el oído está dado al maligno,
y donde se experimentan el camino del pecador y la silla del escarnecedor,
y no sabíamos cómo salir de esta oscuridad.
Aquello que dispersó estas densas tinieblas, quitó el velo de nuestro corazón,
detuvo el oído que escuchaba al maligno,
cegó ese ojo que nos hacía andar en el camino de pecadores,
y derribó ese espíritu altivo que se sentaba en la silla del escarnecedor; yo digo,
aquello que ha hecho todo esto por nosotros no fue otra
cosa más que el poder de Dios obrando en Su preciosa luz,
a la cual nuestras mentes fueron dirigidas al principio,
y en la cual hemos creído. Y a medida que caminamos y habitamos en esto,
experimentamos el cumplimiento de estos dichos que están grabados en la Escritura:
"`Para que los que no ven, vean, y los que ven, sean cegados,`"^
footnote:[Juan 9:39]
"`guiaré a los ciegos por camino que no sabían, y el cojo saltará como un ciervo;`"^
footnote:[Isaías 42:16 y 35:6]
y "`quitó de los tronos a los poderosos, y exaltó a los humildes.`"^
footnote:[Lucas 1:52]
Cuando una persona camina y permanece en eso que obra estas cosas,
siente una delicia en la ley del Señor, y medita en ella de día y de noche.

En verdad,
solo deleitarnos y meditar en esta ley es lo que puede evitar que le volvamos
a dar nuestro oído al maligno y andemos en el camino de pecadores otra vez;
esto es lo único que impide que el espíritu altivo se levante de nuevo.
Esta es "`la ley del Espíritu de Vida,`"^
footnote:[Romanos 8:2]
que nos ha librado, y puede preservarnos en la libertad que hemos alcanzado.
Todos los que son ajenos a esta ley, y a la meditación en ella,
le darán su oído al maligno, andarán en camino de pecadores,
y se sentarán en la silla del escarnecedor, sin importar cuál sea su profesión religiosa.
Con solo esta Escritura,
todas las sectas en el cristianismo (que profesan que las
Escrituras son su regla) pueden probarse a sí mismas,
y ver si están en el estado del varón bienaventurado,
o en el estado del varón en maldición. Ellos no necesitan contratar a un maestro
erudito o docto para que les explique el significado de las Escrituras,
porque ellas fueron escritas por hombres simples,
y solo son entendidas por aquellos que han llegado al Espíritu.
Los que obedecen al maligno le dan su oído a él,
y los que cometen pecado andan en el camino de los pecadores.

[.centered]
=== XXXIV. La Cámara de Su Presencia

Creer en la omnipresencia y omnipotencia de Dios
es una de las doctrinas fundamentales de la religión,
es decir, creer que Él está presente en todo tiempo y en todo lugar.
Esto es algo que generalmente se profesa y se cree entre las sectas del cristianismo,
aunque en muchos no es más que una simple profesión o una fe tradicional e histórica,
porque no experimentan esta realidad verdaderamente.

Esta es la diferencia entre aquellos que experimentan la presencia del Señor y su omnipotencia,
y aquellos que no:
Solo los primeros conocen el motivo y razón por el
que Moisés (ese eminente siervo del Señor) dijo,
"`Si tu presencia no ha de ir conmigo, no nos saques de aquí.`"^
footnote:[Éxodos 33:15]
Este era el deleite del alma de los justos en todas las edades y generaciones pasadas,
y lo sigue siendo en este día, es decir,
sentir la presencia consoladora del Señor y la luz de Su rostro alzada sobre ellos.
Esto alegra más sus corazones que la abundancia del grano, del vino y del aceite,
y es mucho mejor que todo eso.
Esto era lo que les daba fuerza y aliento a los justos en todas las edades,
y lo que hacía que ellos estuvieran dispuestos a sufrir por Su nombre.
Esto los sostenía cuando pasaban por las aguas y por el fuego.
Esto los hacía cantar y regocijarse en prisión y en el cepo,
y estar dispuestos a sufrir con gozo el despojo de sus bienes.
Y amigos, a no ser que esta presencia viva se sienta, disfrute y experimente,
y se viva en ella, somos tan débiles como cualquier otro pueblo.
Y en verdad, si alguno la pierde o se aparta de ella,
se volverá tan impío como los demás también.

Por lo tanto,
es algo muy precioso que cada individuo siempre valore las riquezas de esa gracia,
y la gloria de esa luz, a la cual su mente fue dirigida al principio.
Porque esta gracia y luz han llevado a un remanente a la cámara de Su presencia,
a la casa del banquete, donde la bandera sobre ellos es amor,
y aún siguen llevando a otros a esto mismo.
En verdad, esto guiará y dirigirá a todos fuera del camino del mal al camino de la paz.

Oh, la liberalidad de este amor y gracia,
y la gloria de esta luz que han llevado a un remanente
(que la ha amado y seguido) a las cámaras de Su presencia,
a la casa del banquete,
a la cumbre de ese monte santo en el que se disfruta del
banquete de manjares suculentos y de vinos refinados,
y a la diestra de Dios, donde está el torrente de sus delicias.
Esto en verdad es gracia y amor gratuitos.
Este amor es más fuerte que la muerte y mejor que la vida.
Oh, la consideración de este amor es capaz de quebrantar el corazón,
de derretir el alma delante de Dios y reducirla a una rendición santa y resolución
pura de vivir para alabarlo y honrarlo en medio de los hijos e hijas de los hombres,
quienes de ese modo pueden ser ganados y persuadidos a aceptar sus ofertas,
y a seguir su guía, para que conozcan sus caminos deleitosos,
y experimenten su virtud y obra en sus propias almas.

[.centered]
=== XXXV. El Despojo del Yo

Es algo bendito,
y un estado elevado y celestial que cada persona tenga un
testimonio interno de que el yo ha sido despojado.
No hay pueblo sobre la faz de la tierra que esté en el camino hacia este
estado salvo aquel que tenga su mente vuelta a la luz de Dios en el corazón,
y esté siendo tratado en ella.
Porque solo esta luz descubre y pone de manifiesto el yo en todas sus apariencias,
pensamientos, caminos e imaginaciones,
y lleva a aquellos que caminan en ella a la verdadera negación de sí mismos,
sin la cual no hay salvación.

Porque en verdad, la destrucción,
caída y miseria de toda la humanidad entraron por esta puerta,
cuando el hombre le dio atención, crédito e importancia a sus propios deseos,
pensamientos, razonamientos e imaginaciones egoístas,
y quiso conocer y ser sabio por sí mismo.
Por esto la serpiente, que habla desde sus propios recursos (Juan 8:44),
lo venció. Por esto el hombre entró en la tentación del diablo,
y perdió su morada en el paraíso. Y así, el enemigo de la felicidad del hombre,
bajo la pretensión de hacer progresar al hombre, y de mejorar su estado,
y de hacerlo tener algo de importancia y reputación,
lo llevó a un estado caído y miserable.
Darle lugar e importancia al yo fue el primer anzuelo del enemigo, y será su último.
Por ende, velen diligentemente en contra de esto, porque aquí está su poder,
y con esta trampa venció al primer Adán. Y, por lo tanto,
es algo bendito vivir en el poder del segundo Adán, que despoja al yo.
Porque,
así como el pecado y el diablo entraron y prevalecieron
por haberle dado lugar e importancia al yo,
asimismo él será echado fuera y vencido por el poder de
Dios en todos aquellos en quienes Él despoja al yo.

Esta es una lección principal del cristianismo,
que todos deben necesariamente aprender en alguna medida
antes de poder ser verdaderos discípulos de Jesús,
conforme a lo que Él mismo enseña: "`Si alguno quiere ser mi discípulo,
niéguese a sí mismo, y tome su cruz cada día, y sígame.`"^
footnote:[Lucas 9:23]
Negarse a sí mismo y tomar la cruz son dos realidades inseparables,
y deben preceder al discipulado.
Sin embargo,
incluso este estado queda corto de ser amigo de Dios y coheredero con Cristo,
hueso de Sus huesos y carne de Su carne.
Queda corto de sentarse con Él a la diestra de Dios en el reino de los cielos,
y de sentir al Hijo entregándole el reino al Padre, para que Dios sea el todo en todos.
Queda corto de experimentar que la comida y la bebida es hacer la voluntad de Dios,
de sentir que Su fruto es dulce al paladar,
y de sentarse bajo Su sombra con gran regocijo,
glorificados con aquella gloria que Cristo tuvo con el Padre antes que el mundo fuese.
En este estado, el yo es despojado verdaderamente.
De hecho, el primer nacimiento es asesinado, la cabeza de la serpiente no solo es herida,
sino quebrada y sometida, el segundo nacimiento gobierna,
y el mayor sirve al menor (el cual se deleita naturalmente en hacer la voluntad de Dios).
Y esto ya no es una cruz para él,
ni es necesario que tome la cruz porque este es el estado de la
oveja que conoce la voz de Cristo y lo sigue con alegría,
y que no seguirá al extraño.

[.centered]
=== XXXVI. El Nombre del Señor

Es una bendición que las personas conozcan el nombre del Señor. Aquellos
que lo conocen pueden confiar en él como una torre fuerte que los protege,
y como un muro de defensa dentro del cual los justos moran a salvo,
y al cual corren cuando el peligro los asecha.
Es muy precioso que las personas se reúnan y esperen en este nombre.
Estos encuentran a Jesús, el Salvador, en medio de ellos,
y sienten que sus alas se levantan como las águilas.
Estos saben que su pan es seguro y que sus aguas no faltan.
Ellos se reúnen y esperan con gran expectativa; no esperan en vano.
De hecho, su fuerza es renovada, sus alas se levantan,
y sienten que el nombre del Señor es tan precioso
y poderoso en este día como en tiempos pasados.
Ellos saben que es una torre fuerte, un refugio seguro, y un precioso ungüento derramado;
y por eso ellos lo aman, por su dulce aroma, y porque han sido lavados por él,
y son preservados por él como vírgenes.

Estos pueden decir, "`Tu nombre es como ungüento derramado;
por eso las vírgenes te aman.`"^
footnote:[Cantares 1:3]
Eran las almas vírgenes en épocas pasadas las que amaban el nombre del Señor,
y son las vírgenes en este día las que aman el nombre del Señor. Aquellos
que se unen a cualquier otro amante no pueden amar el nombre del Señor,
aunque pretendan tener mucho amor por él. Sus corazones
han fornicado en pos de otros amantes,
y aunque profesan amar el nombre del Señor, y lo toman a menudo en sus bocas,
y se acercan a Él con sus labios, sus corazones están lejos de Él,
y ellos no se apartan de la iniquidad.
Y aunque confiesan y profesan el nombre de Dios en palabras, aun así,
con los hechos lo niegan.
Este tipo de personas hacen que el nombre de Dios sea blasfemado entre los paganos.

El nombre del Señor, con el cual Él se nos ha dado a conocer, es este: _la Luz._
La luz pura y eterna que ahora resplandece en nuestros corazones,
este es el nombre del Señor. Porque Dios es luz,
y no hay ningunas tinieblas en Él. Este es el nombre del Señor para nosotros.
Cuando nos congregamos en este nombre, y esperamos en este nombre,
y vivimos y caminamos juntos en este nombre, tenemos comunión con Dios, y unos con otros,
y moramos juntos como en una fortaleza de piedra,
donde ningún mal o enemigo puede prevalecer contra nosotros.
En este nombre (Luz) es imposible tropezar.
Y cuando amamos este nombre y caminamos en él,
estamos tan lejos de caer que ni siquiera tropezamos.
Tropezar, caerse y hacer el mal son cosas que se encuentran fuera de este nombre.
Porque el que hace lo malo aborrece la luz, y no lleva sus obras,
pensamientos y palabras a ella, y por lo tanto camina, habla y obra en tinieblas,
sin saber lo que dice, ni a dónde va, ni lo que hace.

Todos los profesantes del Cristianismo, y todas las sectas sobre la faz de la tierra,
pueden ser probados, medidos y juzgados por esta única cosa,
independientemente de lo que digan acerca de amar el nombre del Señor:
si hacen lo malo o cometen pecado, aborrecen la luz.
Esta es una verdad universal e infalible;
sin importar cuál sea su religión. Si las personas son halladas haciendo el mal,
aborrecen la luz, están en enemistad con Dios, amando sus obras malas.
Este nombre del Señor (Luz), que manifiesta todas las cosas y juzga toda especie de mal,
es eso que los líderes de las sectas en la Cristiandad desprecian y rechazan,
y por eso no conocen la salvación que está en él. Pero para aquellos que creen en él,
este nombre es precioso,
y ellos poseen y experimentan la dulzura y la salvación
que están en él. Y esta es la salvación que estos han esperado,
y de la que participan: ser salvos del pecado, ser salvos de hacer,
hablar y pensar lo malo, incluso mientras moran en estas casas de barro,
en estos vasos terrenales.
Estos tienen y disfrutan los tesoros celestiales.

En verdad es un gran engaño,
y una horrible doctrina de demonios que se ha esparcido
por toda la humanidad en la gran noche de la apostasía,
en la que,
y por la que las personas son enseñadas y persuadidas a
creer que es imposible dejar de pecar durante esta vida,
y que, aunque ellos continúen y permanezcan en pecado, aun así,
disfrutarán de la salvación de Dios después de que mueran.
De verdad,
esto puede llamarse muy adecuadamente una doctrina de demonios y un gran engaño,
un estado en que las personas están entregadas a creer una mentira,
porque sabemos que "`en el lugar que el árbol cayere, allí quedará,`"^
footnote:[Eclesiastés 11:3]
y que no hay arrepentimiento en la tumba.

Esta es la felicidad de un remanente en este día:
que ellos sienten el nombre del Señor exaltado y puesto
sobre todo nombre en el cielo y en la tierra en su interior,
y que todo en ellos,
dobla rodillas ante él y adora delante de él. Aquí
el Rey de justicia está sobre Su trono.
Aquí el justo gobierna y la tierra se alegra, y se halla la paz en su territorio.

Este es mi testimonio: que nadie puede disfrutar verdadera paz,
sino en la medida que experimente este nombre del Señor
exaltado sobre todo en su corazón--sobre oro y plata,
casa y tierra, esposa e hijos, y reputación personal, sí,
sobre todos los nombres celestiales como también terrenales,
teniendo todo pensamiento e imaginación derribado y sometido
a él. No hay otro nombre bajo el cielo dado a los hombres,
por el cual puedan ser salvos de sus enemigos internos (que son sus más grandes enemigos).
Esto se realiza solo en la medida que experimenten este
nombre del Señor exaltado en ellos--el nombre del que dijo:
"`Yo soy la luz del mundo.`"^
footnote:[Juan 8:12]
Esta luz le muestra al hombre sus enemigos, y no solo eso,
sino que también los destruye con el espíritu de Su boca,
y con el resplandor de Su venida.
Hay poder en Su nombre--la luz--que manifiesta todas las cosas
con el fin de destruir y expulsar todo lo que es contrario a ella,
y redimir a la humanidad de debajo del poder de las tinieblas.

Un remanente es testigo vivo en este día,
y en amor y buena voluntad están listos para contarles a sus prójimos,
compatriotas y familiares,
lo que el nombre del Señor (a través de su amor por él) ha hecho por sus almas,
con el fin de que estos sean persuadidos a abrazarlo,
y venir a experimentar esa misma gran salvación. Grande es el conocimiento
que ha irrumpido en nuestros corazones y entendimientos,
y gloriosa es la luz de ese día que ya alumbra.
¿Qué, pues, resta por hacer,
sino que todos los que han recibido este conocimiento caminen como corresponde al mismo?
Y que todos (en quienes esta luz ha resplandecido) permanezcan en ella y la amen,
de modo que no se levante un pensamiento vano, ni se diga una palabra ociosa,
ni se haga una mala obra, sino que estas cosas estén juzgadas y condenadas por la luz.
Esta luz que juzga toda especie de mal es un día de juicio,
en el que los hombres dan cuenta de cada palabra ociosa que dicen.

[.centered]
=== XXXVII. Acercándose a Dios

El apóstol dio testimonio de una verdad infalible, cuando dijo:
"`Grande es el misterio de la piedad.`"^
footnote:[1 Timoteo 3:16]
Y este es uno de los grandes misterios: que,
aunque Dios está cerca de los hijos e hijas de los hombres,
muchos de ellos están muy lejos de Él. Dios está en el mundo, pero el mundo no lo conoce.
Dios, que es luz, resplandece en las tinieblas, pero las tinieblas no lo comprenden.
Él está en los hombres, y ellos "`viven, se mueven y existen`"^
footnote:[Hechos 17:28 NBLH]
en Él, y sin embargo están sin Él, sin Dios en el mundo, ajenos a Él,
aunque Él no está lejos de ninguno de ellos.

En esto consiste la felicidad de un remanente:
que ellos no solo sienten a Dios cerca de ellos y en ellos,
sino que también se sienten a sí mismos cerca de Él--Él morando en ellos,
y ellos en Él. Estos son los que disfrutan el efecto
de esa bendita oración de Cristo Jesús:
que "`ellos sean uno; así como Tú Padre y Yo somos uno; Yo en ellos, y Tú en mí.`"^
footnote:[Juan 17:21-26]
Esta es la bendita unidad y comunión celestial que
los primeros cristianos experimentaban cuando dijeron,
"`nuestra comunión verdaderamente es con el Padre, y con su Hijo.`"^
footnote:[1 Juan 1:3]
Este es un estado que vale la pena esperar sentir y disfrutar.
Es más, de lo que las palabras pueden expresar,
y es el fin de todas las palabras y declaraciones.
Nadie debe quedar corto de este estado.
Este es el fin de la carrera,
y el premio del supremo llamamiento de Dios en Cristo
Jesús. Aquí es donde vemos ojo a ojo a Dios,
y hablamos con Él como un hombre habla con su amigo.
Aquí vemos como somos vistos, y conocemos como somos conocidos.
Aquí caminamos con Dios como Enoc lo hizo, y hablamos con Él como Abraham,
Moisés y los profetas lo hicieron.
Aquí se experimenta la venida del Señor a la última cena,
donde son preparados los manjares suculentos y los vinos bien refinados.
Aquí el fruto de la vid se bebe nuevo en el reino de Dios.
Aquí está la unión matrimonial, donde el agua se convierte en vino,
donde la esposa y el esposo se regocijan juntos,
donde las lágrimas son enjugadas de todos los rostros, y donde no hay llanto, ni clamor,
ni dolor, ni muerte.
Aquí la muerte es sorbida en victoria, la oscuridad es sorbida en luz,
el temor es sorbido en amor, en el cual no hay castigo.
Aquí se experimenta la verdad de ese dicho, que el "`amor echa fuera el temor.`"^
footnote:[1 Juan 4:18]
Este es el amor que es mayor que la fe, mayor que la esperanza,
es el fin de la fe y de la esperanza, y permanece cuando se han ido.
Este fue el primero, y será el último.
Bendito todos los que moran y habitan en este amor,
porque ningún mal puede entrar a sus moradas.

[.centered]
=== XXXVIII. El Valle de Humillación

No hay mayor bendición que conocer el valle de humillación
en donde están los delicados pastos,
donde somos alimentados con seguridad y donde no hay quien espante.
No hay mayor bendición que experimentar ser alimentados en este
valle de humillación donde está la grosura de la casa del Señor,
donde está el verdor y la seguridad, y a donde la fiera no puede entrar.
El alimentarse aquí es más que palabras; es el fin de todas las palabras y declaraciones.
Es el objetivo del Señor al enviarnos Sus mensajeros del evangelio eterno.
Y es la corona y regocijo de ellos encontrarnos comiendo en este valle de humillación,
del cual los pastores ociosos y sus rebaños no pueden participar con nosotros,
porque no conocen el camino que lleva hasta ahí.

El recuerdo del momento en que el llamado del Señor nos alcanzó,
y nos llamó fuera de las cavernas de las piedras,
y fuera de los montes altos y montañas estériles, al valle de Josafat, donde Él,
con fuego y espada, entra en juicio con toda carne,
y donde se experimenta el juicio por el cual Sion es redimida--yo digo,
el recuerdo de este día es muy precioso para un remanente,
y la ministración de ese día fue gloriosa en su tiempo.
Pero esto es más glorioso:
morar en este valle de humillación donde nos alimentamos
de los delicados pastos de la vida y salvación,
donde crecemos hasta la medida de la estatura de la plenitud de Cristo,
donde no hay temor (porque es quitada la causa de este),
donde corre el torrente de Sus delicias, y donde la tranquilidad de mente,
la paz y la plena satisfacción se disfrutan.
Esta es la mayor de las bendiciones,
y la porción de un remanente en este día de amor y de abundantes riquezas y bondad
del Señor. Aquellos que disfrutan verdaderamente la medida más pequeña de esto,
la estiman más que al mundo entero,
porque ellos saben bien que todas las cosas en el mundo no son
suficientes para comprar la gota más pequeña de esto.

[.centered]
=== XXXIX. Poseer los Bienes

Es algo muy bendito que cada persona en particular sienta
y conozca al Espíritu de Dios dentro de sí mismo,
dando testimonio a su espíritu de que verdaderamente espera en Él y lo adora.
De acuerdo con el testimonio de los patriarcas, profetas y apóstoles,
muchas cosas gloriosas son disfrutadas por aquellos que esperan
en el Señor. Hubo uno en la antigüedad que pudo decir,
"`Los que esperan en el Señor no tendrán falta de ningún bien.`"^
footnote:[Salmo 34:10]
Este único versículo es suficiente para probar a todos los
que dicen esperar en el Señor en el mundo cristiano,
o que pretenden un tipo de espera en Él en ordenanzas y, sin embargo,
carecen de los bienes.
Pobreza, ceguera y desnudez, languidez de alma y esterilidad de corazón,
son sus diarios acompañantes.
Así que en lugar de que no les falte ningún bien,
carecen de todos los bienes relacionados a su hombre interior.

Hubo otro que pudo decir, "`Los que esperan en el Señor tendrán nuevas fuerzas;
levantarán alas como las águilas; correrán, y no se cansarán; caminarán,
y no se fatigarán.`"^
footnote:[Isaías 42:31]
Ningún hombre que solo tiene la forma externa del
cristianismo puede ser testigo vivo de estas cosas.
Estos pueden concluir con certeza que están engañados y
equivocados en la causa cuando no experimentan el efecto.
Porque este es un testimonio de la verdad para todas las sectas en la Cristiandad,
y para los distintos tipos de adoradores en cualquier parte del mundo:
que sin importar lo que profesen (aunque sea la verdad misma),
si no disfrutan estos bienes,
ni sienten su fuerza renovada como para correr sin cansarse y caminar sin fatigarse,
y si no crecen de un grado de gracia a otro, de un grado de conocimiento a otro,
ni incrementan con el incremento de Dios en el hombre interior,
entonces engañan sus propias almas con una religión vana, muerta y estéril,
que no produce frutos, sino que se desvanecerá como el humo en el día del Señor.

[.centered]
=== XL. La Gran Salvación

Es algo precioso experimentar la presencia de Jesús
en medio nuestro como un pacífico Salvador.
Los que lo conocen de esta manera viven, habitan y caminan en Él,
y están entre aquellos que no necesitan arrepentimiento.
En verdad es un estado elevado y celestial llegar a este grado de conocimiento.
Solo aquellos que primero lo han conocido como un juez y reprobador,
como un refinador con fuego consumidor,
y como uno que vence a todos los enemigos en su interior,
han llegado hasta esta condición. Estos sienten al gran dragón atado,
la boca del pozo del abismo cerrada,
y por lo tanto están de pie sobre el mar de cristal mezclado con fuego,
siendo testigos vivos de la victoria sobre la bestia y su imagen,
y sobre la marca y el número de su nombre.
Estos son los que cantan el cántico de Moisés y del Cordero,
no solo en la orilla de la salvación,
sino en medio de la Jerusalén que desciende del cielo, de Dios,
y delante del trono del Cordero, quien es la luz de esa ciudad,
y quien los ha redimido de la tierra y los ha salvado con grande salvación.

[.centered]
=== XLI. La Perla Preciosa

Aquello que estaba perdido ahora es hallado.
Un remanente en esta era ha cavado profundamente y ha encontrado
la perla preciosa que estaba escondida en el campo,
y muchos se regocijan al verla y conocerla.
Pero que todos entiendan esto:
no es suficiente encontrar el tesoro celestial o la preciosa perla;
hay que comprarla y poseerla vendiendo todo y dejando todo por ella.
Nada en nuestros corazones, nada que estimemos valioso,
debe estar en competencia con ella; todo debe ser entregado por ella.

Las palabras que Cristo dijo son verdaderas: "`El que ama cualquier cosa más que a mí,
no es digno de mí.`"^
footnote:[Mateo 10:37]
Solo Él debe reinar y regir, y tener el gobierno en nuestros corazones.
Nosotros tenemos que conocerlo como la piedra del fundamento,
la del ángulo y la superior, como la piedra escogida y preciosa.
No es suficiente conocerlo como una pequeña "`piedra cortada de la montaña,
no con mano,`"^
footnote:[Daniel 2:34]
hiriendo los pies de toda imagen,
sino que también tenemos que sentirlo creciendo e incrementándose
hasta ser un monte extremadamente grande,
que llena la tierra y se vuelve todo en todos.
Nosotros tenemos que sentir que todo se inclina ante Su nombre--todo pensamiento altivo,
toda imaginación y toda pasión vergonzosa.
Toda voluntad y deseo del yo debe ser negado,
derribado y llevado cautivo a la obediencia del nombre, del poder de Dios.

Todos los que han obtenido,
no solo el conocimiento del campo donde la perla está escondida,
sino que también han cavado profundamente en él y la han encontrado,
deben esperar y experimentar este estado bendito.
Estos no deben quedar cortos, teniendo solo la visión,
el conocimiento y la profesión de la perla preciosa, sino que deben comprarla, heredarla,
poseerla y disfrutarla.
Entonces serán capaces de decir: "`Mi amado es mío, y yo suyo.`"^
footnote:[Cantares 2:16]
Es en esta condición donde Él apacienta entre los lirios, donde no se trabaja ni se hila.

[.centered]
=== XLII. Donde el Engañador No Puede Entrar

Lo que hace que un pueblo sea bendecido por encima de todas las familias de la tierra,
es que son conscientes (tanto en sus reuniones solemnes
como en todo tiempo) de ese poder que despoja al yo,
incluso al yo que es inocente.
Porque Cristo tenía este tipo de yo inocente,
el cual era humilde y fue hecho obediente hasta la muerte de la cruz,
y este fue el camino que lo llevó a la exaltación suprema y celestial.
A medida que las personas anden en este camino (como lo hizo el Capitán de nuestra salvación),
la serpiente (que engañó a la humanidad en el paraíso,
arrastrándola hacia la exaltación y reputación del
yo) nunca podrá prevalecer contra ellos.
Porque la adoración a la cual este poder nos ha llevado
no empieza cuando nuestras reuniones solemnes comienzan,
ni termina cuando nos despedimos,
sino que está fundada en eso que no tiene principio ni fin, es decir,
en el Espíritu y en la verdad, a la cual el engañador no puede entrar.

Es un estado precioso, una condición elevada y celestial, experimentar el despojo del yo,
y tener unidad con ese poder que lo ha despojado.
Ninguna tentación prevalecerá contra aquellos que permanecen y habitan en él.
Así que todo el deber de los que han llegado al conocimiento de este poder (y
a tener fe en él) consiste en estar siempre aferrados a él con todo su corazón,
y en fijar sus mentes en él,
para que en medio de todas las tentaciones y pruebas experimenten
liberación y salvación por medio de él. En verdad,
estos nunca la perderán.

Porque cuando Cristo fue tentado, se dice que después de la tentación,
los ángeles le ministraban.
Esto mismo es experimentado por un remanente en este día ¡Alabado sea el Señor!
Estos experimentan la bendición que viene después de soportar la tentación,
y magnifican el poder de Dios sobre el poder del maligno,
y son para alabanza de Su gloria.
Aquí difieren de otros: no solo por las palabras y creencias,
sino por vivir en el sentido y obediencia a ese poder que despoja el yo.

El yo comenzó a buscar su propia gloria cuando la
tentación entró por primera vez a la humanidad.
Por darle crédito a lo que el Diablo les dijo: "`Serán como Dios,`"^
footnote:[Génesis 3:5]
etc. una esperanza egoísta fue engendrada para obtener una ganancia egoísta.
Y siendo engañados de esta manera,
un deseo vano de reputación personal brotó y se incrementó,
así que la desobediencia al mandamiento y poder de Dios,
y la esperanza y confianza egoísta fueron compañeras inmediatas en el principio.
Y todos los hijos de la luz, quienes en este día han llegado a una morada en el paraíso,
deben velar en contra de esto, no sea que, como la serpiente engañó a Eva,
los engañe también a ellos.

[.centered]
=== XLIII. El Sol de Justicia

La noche está avanzada, las tinieblas han pasado, y la luz verdadera ya alumbra.
El día de Dios ha amanecido,
y el lucero de la mañana se ha levantado en los corazones de miles.
Este estado y conocimiento es muy glorioso en su tiempo,
y es más de lo que experimentan y entienden todos los meros cristianos de nombre.
Sin embargo, aquello que tenemos que esperar y anhelar fervientemente,
es algo más profundo, o una experiencia de esto en una medida mayor de gloria, es decir,
experimentar que el Sol de Justicia se ha levantado con sanidad en sus alas.
En verdad, esto es más precioso, y es un mayor grado de conocimiento--sí,
experimentar la virtud sanadora del Sol de Justicia.

Esta ministración viene después de esa que descubre, reprueba, convence, golpea, corrige,
e hiere; de hecho, ella venda y sana, conforta y consuela al alma,
refresca y alegra al corazón, y ministra el gozo de la salvación de Dios.
Vivir en el sentido y experiencia de esta virtud sanadora,
de este poder salvador y preservador (no solo en nuestras reuniones solemnes,
sino también en otros tiempos) es muy precioso.
Esto cura toda dolencia y enfermedad, y quita,
dispersa y remueve la causa de los golpes y heridas,
incluso la causa por la que somos convencidos, reprendidos y azotados,
y preserva de caer en ella otra vez.
Mientras vivamos y permanezcamos en esto, nunca podremos errar,
ni jamás necesitaremos ser reprobados, golpeados o heridos.

El mundo es el que se encuentra en ese estado en
que el Espíritu de Dios convence del mal,
reprueba, golpea, e hiere debido a la transgresión,
pero para nosotros la salvación ahora está más cerca que cuando creímos,
y el gran día de la salvación ha llegado.
De hecho, el Reparador de los portillos y el que sana las naciones ha llegado.
Benditos todos aquellos que experimentan Su virtud sanadora,
y el bendito efecto de Su aparición con sanidad celestial en Sus alas.
Estos pueden decir que la enfermedad de su alma ha sido sanada,
y que sus heridas no solo han sido vendadas, sino curadas,
y que ellos han sido limpiados y sanados, en alma, cuerpo y espíritu.
Estos están preparados y en condiciones para tener su ciudadanía con Dios en el cielo,
y para sentarse allí en el disfrute de la luz de Su rostro,
que es mejor que la abundancia de todas las demás cosas.
Es el sabor del torrente de delicias que está a Su diestra, y del vino en Su reino,
lo que hace que aquellos que lo beben esperen y anhelen participar más y más de lo mismo.
Es por el olor de sus suaves ungüentos que las vírgenes lo aman.
Si no hubiera un buen aroma,
si no se sintiera y se experimentara algo de mayor virtud y valor
que los tesoros y placeres que este mundo puede ofrecer,
las almas de los justos no lo anhelarían ni se enfermarían de amor,
ni serían estimulados a esperar por el disfrute del incremento y abundancia de este.

En esto consiste nuestra felicidad:
en experimentar y participar diariamente de la virtud de este poder sanador,
salvador y preservador, en sentir nuestros corazones y mentes ligados a él,
unidos a él y hechos uno con él. Aquí está nuestra bendición eterna,
y lo que verdaderamente nos distingue de todos los meros cristianos de nombre, a saber,
que caminamos y permanecemos en esta bendita luz,
en el Sol de justicia que se ha levantado y ahora alumbra,
y que experimentamos su virtud sanadora.

[.centered]
=== XLIV. El Poder Enternecedor del Señor

Es un estado precioso ser tierno de espíritu, suave de corazón,
preparado para esperar en el Señor. Estos están en
capacidad de saber cuando viene el bien.
No son como el lugar seco, ni como el desierto estéril,
sino más bien como la tierna hierba, sensibles a los rocíos del cielo,
de la llovizna que cae y de los aguaceros fructíferos que descienden sobre ellos.
Ellos pueden sentir las gotas de Su amor divino,
y brotan y cantan de alegría en el disfrute de ellas.
Pero aquellos cuyos corazones son de piedra, y cuyos espíritus son duros,
no pueden probar ni ver cuán bueno es el Señor. Estos
no están preparados para esperar en el Señor,
ni para acercarse a Él y participar de Sus refrescamientos divinos,
ni tampoco tienen el sacrificio que le agrada a Su alma,
el cual es un corazón quebrantado y un espíritu contrito.

¡Oh,
que bendición es que las personas se reúnan y esperen en
el sentido y experiencia del poder enternecedor del Señor,
sí, de ese poder que nos buscó y nos reunió al principio!
En verdad,
es algo bendito que nuestros corazones sean tratados por
este poder enternecedor que ahora está con nosotros,
y nos acompaña para nuestro bien y preservación. Esto es aquello que hace que
nosotros y nuestras reuniones se diferencien de todos los cristianos de nombre.
Aquellos que se reúnen y esperan así, se sientan en la mesa del Señor,
se alimentan de la verdadera comida y beben del vino que Él ha preparado,
nutriéndose de la vida misma, y de la sustancia misma.
Esto es mejor que sentarse en la mesa de los príncipes; de hecho,
todos los banquetes y manjares de la tierra no se le pueden comparar.

A medida que todos mantengan su mente y corazón en
el sentido del poder enternecedor del Señor,
serán testigos vivos de su hermosura.
Aquí nadie puede olvidar la misericordia del Señor,
ni dejar que Sus beneficios se les escapen de sus mentes,
más bien están capacitados para alabarlo y magnificarlo por todas Sus misericordias,
Sus bendiciones celestiales y las maravillosas bondades y liberaciones
que Él ha obrado por ellos--las cuales han sido tan grandes como las que
Él ha hecho por cualquier pueblo en cualquier época del mundo.
Estos pueden decir que Él no solo los ha sacado de Egipto,
a través del Mar Rojo y del desierto,
sino que también los ha introducido en la buena tierra, y les ha repartido su heredad.
Ellos pueden decir que su suerte ha caído en un buen lugar,
y al sentir el fluir de la leche y miel,
comen y beben y alaban al Señor en la experiencia de todas Sus misericordias,
bendiciones y salvación que los acompañan y los rodean.

Este es el misterio de nuestra comunión, y el vínculo de nuestra unidad:
que nuestras mentes y corazones están siendo tratados
por el poder enternecedor del Señor,
especialmente cuando nos reunimos y esperamos solemnemente en Él,
según todos se mantienen cerca de esto, y están unidos a esto.
¡Oh, este es un estado precioso!
En esto consiste nuestra bendita unidad y comunión. Aquí somos fuertes,
incluso como el Monte de Sion,
y como un cordón de tres dobleces que no se rompe fácilmente.
Mientras que nos mantengamos y permanezcamos en esto,
las puertas del Hades no prevalecerán contra nosotros,
y ningún mal nos hará daño. En esto consiste nuestro
gozo y preservación durante nuestras reuniones,
y también cuando nos despedimos, y en todo tiempo y lugar:
en sentir nuestros corazones y mentes en unidad con el Espíritu del Señor,
ya no siendo redargüidos, reprobados y condenados por Él,
sino más bien justificados y encomendados.
En verdad, esto es dulce y precioso,
como lo saben muy bien todos los que están en este poder.

[.centered]
=== XLV. La Mente Puesta en el Señor

Es aquel que se queda en casa el que reparte el botín de sus enemigos.
Es aquel que se queda en casa el que obtiene la bendición.
El errante y cazador no la obtiene,
porque se esfuerza y se agota a sí mismo, y vende su primogenitura.
Es la mente retirada, la mente quieta,
la mente que tiene sus lomos ceñidos con la verdad y que está puesta en el Señor,
la que recibe la bendición y es guardada en completa paz,
de acuerdo a lo que fue testificado en la antigüedad: "`Tú guardarás en completa paz,
aquel cuya mente en ti persevera.`"^
footnote:[Isaías 26:3 Reina Valera 1602 Purificada]
Disfrutar esto es el premio del supremo llamamiento de Dios en Cristo Jesús,
al cual hemos sido y somos llamados, sí, a disfrutar completa paz, a ser cabales,
sin que nos falte cosa alguna.
Disfrutar esto es el fin, suma y sustancia de la religión cristiana.

Son aquellos que tienen sus mentes retiradas y puestas
en el Señor los que heredan la sustancia.
Son aquellos que han experimentado la lámpara del Señor encendida en ellos,
que han barrido su propia casa y encontrado la dracma, los que por lo tanto se gozan.
Esta luz celestial que ya alumbra descubre la vanidad
y el vacío de todas las cosas debajo del sol.
Y por esta misma luz, nuestras mentes han sido redimidas de estas cosas,
y nos hemos convertido en testigos vivos de que ni todos los tesoros, placeres,
opiniones y religiones que están en el mundo, ni la simple profesión de la verdad,
son capaces o suficientes para aquietar o satisfacer nuestras almas.
Hemos encontrado y probado que todas esas cosas son vanidad y aflicción de espíritu.
Porque el alma del hombre en sí misma es más excelente, más noble,
y de mayor valor que todas ellas, y además es superior.
Algo menor no puede satisfacer o llenar algo mayor, ni lo que es inferior,
vil y menos excelente puede aquietar o satisfacer lo que es superior, o más digno,
noble y excelente en naturaleza, capacidad y esencia.
Puesto que el alma de la humanidad es mayor que todos
los seres terrenales que han sido creados,
todas las cosas debajo del sol, en lugar de serle comida y satisfacción,
resultan ser vanidad, vacío y aflicción de espíritu.

Por lo tanto,
bendito sea el recuerdo de ese día y tiempo en que nuestras mentes
fueron vueltas a la luz verdadera y eterna que ya alumbra,
que ha descubierto la vanidad y vacío de todas las cosas debajo del sol,
y ha redimido a los hijos de la luz de debajo de todas ellas,
y los ha llevado a Aquel que está sobre todas ellas, Dios bendito por siempre.
De hecho, esta luz lleva a la única y verdadera adoración eterna y universal,
que es en el Espíritu y en la verdad.
Aquí todos se inclinan, adoran y obedecen a Dios, que es la luz y que mora en la luz.

[.centered]
=== XLVI. Las Tinieblas han Pasado

Solo los que han alcanzado un estado celestial,
son los que pueden decir por experiencia lo real que es
el siguiente antiguo testimonio de las Sagradas Escrituras,
y sellar la verdad de este: "`Las tinieblas han pasado, y la luz verdadera ya alumbra.`"^
footnote:[1 Juan 2:8 Reina Valera de Gómez]
Es una bendición experimentar la verdad de esto,
o ser capaces de decir verdaderamente que las tinieblas han pasado.
Aquellos que han conocido lo que es morar en tinieblas,
y trabajar y viajar en la tierra de oscuridad,
y han sido rodeados y sitiados con densas neblinas
y brumas en la oscura región de sombra de muerte,
pueden recordar cómo caminaban en lugares solitarios, cómo su morada era con dragones,
búhos y murciélagos como sus compañeros,
y cómo allí ellos tropezaban y palpaban la pared como hombres ciegos.
Solo aquellos que han estado en esta condición,
y que ahora han llegado a experimentar la redención y liberación de ella,
son los que pueden en verdad decir que las tinieblas han pasado,
y que la luz verdadera ya alumbra en y para ellos.
Estos pueden llamar a esta realidad un estado bendito en verdad,
y ellos saben que es mucho mejor sentir y experimentar la verdad de estas cuatro palabras--las
tinieblas han pasado--que escuchar y leer miles de palabras buenas.

Hay mucho en estas cuatro palabras.
Los que sienten que las tinieblas han pasado y se han ido,
han llegado al día eterno de Dios, al levantamiento del glorioso Sol de justicia,
que ha causado que las sombras mismas de la muerte huyan.
En estos,
el vientre que ha engendrado y generado todo el mal
e iniquidad que se manifiesta en la humanidad,
se ha hecho estéril, ha sido removido y ha desaparecido.
Ellos han llegado al amanecer de ese día, y al levantamiento de ese sol,
que dispersa toda las neblinas y brumas, las nubes y errores,
que los rodeaban y los hacían caminar en la sombra de muerte.
Sus corazones han sido llevados a regocijarse en el sentir y disfrute de este día,
y sus ojos quedaron satisfechos con ver la gloria de la luz verdadera que ya alumbra,
y ellos sienten sus corazones dispuestos a caminar en esta luz.
Sí, no solo la profesan y hablan de ella, sino que caminan en ella,
y no solo se han convertido en hijos de ella, sino que han llegado a ser jóvenes,
padres y ancianos en ella.
Caminar en la luz significa ser dirigidos y guiados por ella, y llevar cada pensamiento,
palabra y obra a ella,
para que sea probado--no solo en nuestras reuniones y congregaciones solemnes,
sino en el resto del tiempo, es decir, en nuestros asuntos,
negocios e interacciones entre los hombres, incluso en nuestras actividades comunes.
Y cuando todos se encuentran en esta luz, están en la verdadera adoración de Dios,
ya sea que estén juntos o separados.

[.centered]
=== XLVII. El Día de Reposo

Estos son dichos verdaderos y fieles que fueron testificados
en la antigüedad--que "`queda un reposo`"^
footnote:[Hebreos 4:9]
al cual el creyente entra, y el que ha entrado a este reposo, ha "`cesado de sus obras,
como Dios de las suyas.`"^
footnote:[Hebreos 4:10]
Esta es la sustancia y antitipo del día de reposo de los Judíos,
y este reposo es interno y espiritual, es una quietud y un descanso para el alma,
donde se experimenta ese estado bendito (del que se habló en tiempos antiguos), a saber,
"`Tú guardarás en completa paz, a aquel cuyo pensamiento en Ti persevera.`"^
footnote:[Isaías 26:3 Reina Valera de Gómez]
Este es un estado bendito en verdad, ser guardados en perfecta paz.
Aquellos que han entrado a este reposo, y permanecen en él,
experimentan el cese de sus propias obras,
de seguir sus propios pensamientos y de hacer su propia voluntad.
Estos guardan el día santo para el Señor,
y saben que el día del Señor (del cual se habló y profetizó hace mucho tiempo) ha llegado,
y que la luz gloriosa del mismo ya alumbra.

Este es el gran día de reposo, en el que Cristo se levanta como un maestro de Su pueblo,
y ellos escuchan y entienden Su voz, y lo siguen,
y cierran su oído contra las muchas voces que están en el mundo.
Este es el maestro al cual hemos sido dirigidos desde el principio.
No hemos sido llamados a un ruido o sonido de palabras, ni a una simple profesión,
sino a heredar la sustancia, a disfrutar el reposo,
incluso ese reposo que ha sido preparado desde la antigüedad para el pueblo de Dios.
En verdad, todavía queda este reposo, y es muy glorioso,
como lo pueden testificar aquellos que han entrado
en él. Y esta es mi experiencia y testimonio:
que nadie podrá entrar en este reposo salvo en la medida
en que experimente un cese de sus propias obras,
de su propio querer, correr y pensar,
y tenga todo pensamiento llevado a la obediencia de Cristo.
Solo en la medida que esto se efectúe,
es que alguien podrá experimentar una entrada a este reposo que está preparado,
y que todavía queda--independientemente de lo que las personas hablen y profesen.

[.centered]
=== XLVIII. El Viejo Hombre Atado

Esta es una gran verdad: que la religión de quienes no sienten un freno para su lengua,
ni experimentan una cadena para atar su voluntad, afectos, deseos y pasiones, es vana;
porque, aunque hablen de reposo y paz, aun así, no disfrutan de nada de esto.
Juan vio a un ángel que descendía del cielo,
con la llave del abismo y una gran cadena en su mano, el cual prendió al dragón,
la serpiente antigua, que es el diablo y Satanás,
y lo ató. Cada individuo debe ver y sentir esto hecho en la revelación de Dios,
antes de poder experimentar una entrada al reposo que es glorioso,
y llegar a sentarse en el mismo,
al cual la luz de este glorioso día lleva a todos sus hijos.
Así que es precioso esperar en el Señor, que mora en la luz,
y que lleva a los hijos de luz a disfrutar del reposo.

[.centered]
=== XLIX. Acercándose al Señor

El gozo y deleite de los justos en todas las edades ciertamente era acercarse
con sus corazones al Señor y estar retirados internamente con Él en sus mentes.
Y en verdad, ese también es el gozo y deleite de los justos en esta era, quienes,
al acercarse al Señor, experimentan la verdad de este testimonio:
El Señor se acercará a aquellos que se acerquen a Él.^
footnote:[Santiago 4:8]
Estos experimentan Su presencia celestial, y participan del gozo de Su salvación,
teniendo su ciudadanía en el cielo en el cual Dios habita,
y caminan con Él como hicieron Enoc, Abraham, Moisés y los profetas.
Esto es experimentado por un remanente en esta era, como lo fue en eras pasadas.
Porque el día de vida y salvación ha llegado,
y se ha revelado el bendito camino que conduce a esto,
y se ha manifestado claramente a miles en este nuestro país natal,
la isla de los gentiles, sobre los cuales ha nacido la gloria del Señor.

Es una bendición conocer el camino de vida y salvación, pero es una bendición mayor,
y un grado superior de felicidad, que cada individuo (a quien se le ha aparecido),
al caminar en la luz,
se sienta a sí mismo capacitado y preparado para poseer
y heredar la salvación. Y esto es digno de ser esperado,
y es el bendito fin de toda la sagrada escritura, de toda lectura,
predicación y creencia--es decir, poseer la cosa sobre la cual se han leído,
escrito y predicado palabras.
Aquellos que son enseñados por el Señor, y están establecidos en justicia,
no solo la conocen y profesan, sino que están establecidos en ella.
Este es el premio del supremo llamamiento,
que todos los que están en el camino que conduce a él deben buscar fervientemente,
para que puedan llegar a disfrutarlo.

Es gustar y ver cuán bueno es el Señor lo que levanta y despierta deseos de disfrutarlo,
y hace que el corazón esté cada vez más dispuesto a acercarse a Él,
y a esperar en Él. Es gustar de la corriente del río de vida y
de delicias que están a la diestra de Dios lo que da nuevas fuerzas;
y solo estos experimentan la verdad de ese dicho:
"`Los que esperan en el Señor tendrán nuevas fuerzas; levantarán alas como las águilas;
correrán, y no se cansarán; caminarán, y no se fatigarán.`"^
footnote:[Isaías 40:31]
Estos corren en el camino de los mandamientos de Dios con deleite,
porque se ha vuelto tan natural y placentero cumplirlos
como alguna vez fue hacer lo contrario.

Este es el bendito estado y privilegio de muchos:
acercarse tanto al Señor que no solo gustan y ven Su bondad,
sino que también son suplidos y colmados con nuevas fuerzas,
refrigerio divino y consolación celestial en sus almas,
lo cual hace que se enamoren cada vez más de Él y que continuamente estén dispuestos
a esperar en Él. Y en esto consiste la felicidad y preservación de todos:
que el ojo de sus mentes se mantenga mirando al Señor y esperando en Él,
así como "`los ojos de la sierva miran a la mano de su señora,`"^
footnote:[Salmo 123:2]
y mucho más. Donde sea que falte este gustar, ver, acercarse y esperar,
allí la debilidad, cansancio y fatiga abundarán,
y el enemigo del alma prevalecerá--sin importar lo que hablen y profesen de religión.

[.centered]
=== L. El Testimonio del Espíritu.

Es una bendición, sí, la más grande bendición de todas las bendiciones,
que cada individuo conozca y sienta dentro de sí mismo que el Espíritu de Dios
da testimonio a sus espíritus de que ellos son los hijos e hijas de Dios,
y de que Él los ha hecho renacer para una esperanza viva,
por la cual se purifican a sí mismos, así como Él es puro,
y de que son cristianos verdaderos, israelitas verdaderos,
en quienes no hay engaño. Yo digo que esto es la bendición más grande de todas las bendiciones--que
cada uno tenga al Espíritu de Dios dándole testimonio de estas cosas;
en verdad, es precioso esperar esto y disfrutarlo.
Porque Aquel que nos ha llamado es santo, inocente y sin mancha,
así que a medida que lo sigamos y obedezcamos seremos semejantes a Él,
incluso como lo eran los cristianos primitivos, quienes dijeron:
"`sabemos que cuando Él se manifieste, seremos semejantes a Él.`"^
footnote:[1 Juan 3:2]
Este testimonio del Espíritu de Dios es mayor que miles de testigos.
Era lo único que consolaba a los justos en todas las eras pasadas,
y es el mismo que lo hace en este día.

Es bueno tener la mente puesta en el Espíritu y en Su testimonio,
de tal modo que nos volvamos de mente espiritual.
Solo entonces se conoce la vida y la paz, y se desvanece la muerte y la angustia,
y se experimenta la verdad de ese dicho: "`La mente carnal es muerte;
mas la mente espiritual, vida y paz.`"^
footnote:[Romanos 8:6]
En verdad, el Espíritu de gracia y verdad ha llegado,
y muchos son testigos vivos de Su aparición y poder,
no solo para reprobarlos y convencerlos,
sino también para confortar y consolar a aquellos
que han esperado (y aún esperan) Su aparición,
y están enamorados de Él, y tienen su oído abierto a Su enseñanza,
y sus mentes y corazones dedicados a ella.

En esto consiste el eterno gozo, paz, consuelo y consolación de los justos, a saber,
en que ellos aprenden continuamente del Espíritu de gracia,
y sienten que los conduce y guía fuera de todo mal hacia todo bien.
Mientras se mantienen en el sentido y en el trato de este Espíritu de gracia,
ellos superan a todos los simples profesantes del cristianismo.
Solo esto los distingue de todos los demás, a saber,
que ellos están creciendo en el espíritu de un grado de gracia a otro,
de un grado de conocimiento a otro, de un grado de fe a otro,
de un grado de fuerza a otro, de niños a jóvenes, de jóvenes a ancianos y padres,
hasta la estatura y plenitud de Cristo, teniendo Su mente,
y haciendo siempre lo que le agrada a Dios.
Estos son hijos de Dios sin mancha,
y son capaces de decir lo que dijeron algunos de la antigüedad:
"`Nosotros no podemos hacer nada contra la verdad.`"^
footnote:[2 Corintios 13:8 Reina Valera 1602 Purificada]
Este en verdad es un estado sublime y celestial,
que todos deben esperar y anhelar fervientemente,
el cual es posible alcanzar en esta época, como en las épocas pasadas.
Estos pueden decir: "`Mayor es el que está en nosotros, que el que está en el mundo,`"^
footnote:[1 Juan 4:4]
y ellos experimentan a diario Su poder guardándolos fuera del mal del mundo,
aunque vivan y trabajen en él, e interactúen diariamente con los hijos del mundo.
Esto es lo que nos mantiene como un pueblo vivo y virtuoso, a saber,
que permanecemos en Él, y crecemos en Él, quien se nos apareció al principio,
y a quien nuestras mentes fueron dirigidas al principio.
Al permanecer en Él nos volveremos predicadores de justicia,
luces del mundo y sal de la tierra en verdad.

[.centered]
=== LI. El Nombre "`Luz`"

Es algo precioso esperar, caminar y morar en la luz, es decir,
en eso que manifiesta todas las cosas.
Aquellos que esperan y caminan en ella, son guiados por ella al nacimiento del Sol, sí,
del Sol eterno de justicia, cuya gloria,
luz y virtud realmente dispersan y alejan los pensamientos vanos,
las imaginaciones de las tinieblas, las neblinas,
las nubes y las brumas de ignorancia y oscuridad en el interior,
así como el sol externo expulsa, extingue y hace que las neblinas,
las brumas y las tinieblas se desvanezcan externamente.
Muchos son testigos vivos de esto.

El recuerdo mismo del primer descubrimiento de la verdad
bajo el nombre de "`luz`" en esta nuestra era,
es muy precioso.
La verdad es solo una, aunque tiene muchos nombres,
y este nombre--luz--es muy excelente para un remanente.
Muchos hombres justos y profetas en épocas anteriores anunciaron
de antemano la gloria de este día o luz que ya alumbra,
y profetizaron que iba a resplandecer sobre un pueblo asentado en tinieblas,
que estaba cubierto con la sombra de la noche, y moraba en la región de la muerte.
Nosotros vemos el cumplimiento de estas cosas,
porque en verdad estábamos asentados en tinieblas y andábamos perdidos en lugares desolados,
y estábamos rodeados de la región y sombra de la muerte.

¡Oh, cuán dulce fue la luz cuando brotó en nosotros por primera vez,
y nos hizo ver por encima de las cimas de los montes altos de oscuridad,
y nos descubrió las cámaras secretas pintadas de imágenes, y lo oculto de las tinieblas,
y guio nuestros pies fuera del lodo y del cieno,
y los puso en libertad para caminar en esa senda
que lleva fuera del camino de la muerte y oscuridad!
Esta es esa manifestación de luz por medio de la cual se efectúan todas estas cosas,
a la cual nuestras mentes fueron dirigidas al principio,
cuya luz juzga toda especie de mal,
y conduce a todos los que caminan en ella fuera de él. Este
es el camino que no solo nos lleva a la inocencia,
sino que nos preserva en ella.
Porque hay una posibilidad en esta era (como en la
antigüedad) de que las personas pierdan un buen estado,
y sean tentadas a salir de la inocencia y del estado virgen,
incluso después de haberlo alcanzado.
Fue esto, por lo que Pablo exhortó a aquellos a quienes les escribió,
diciéndoles que tuvieran cuidado de ser engañados como la serpiente engañó a Eva.
¿Cómo sucedió eso?
Atrayéndolos o seduciéndolos fuera de la inocencia,
fuera de un estado inofensivo y sin pecado,
hacia el pecado o quebrantamiento de los mandamientos de Dios,
para que así perdieran el Paraíso. La serpiente hizo esto, y puede hacerlo otra vez.
En verdad, las personas pueden perder un buen estado, sí, su lugar en el Paraíso,
si no son vigilantes.
Por lo tanto, es bueno esperar y velar en la luz,
que no solo conduce de regreso al huerto de Dios,
lleva al Árbol de Vida y concede un derecho para comer del mismo,
sino que también preserva en él,
puesto que descubre al tentador y nos da dominio sobre él,
y evita que caigamos en la tentación.

No nos sorprende que el antiguo enemigo de la humanidad se enfurezca contra la verdad,
bajo el nombre de luz.
No es algo extraño que él le dé tantos nombres de oprobio y desprecio,
para que las personas no le presten atención, ni crean en ella;
porque él sabe que ella socava su reino de oscuridad,
y lo descubre a él y todas sus obras, y también las destruye.
Nosotros somos testigos de que el poder y virtud de la fe
en la luz es capaz de romper todas las cadenas de oscuridad,
y de librar de los grillos de la muerte y del infierno.
Y también sabemos que no hay otro camino o medio bajo el cielo, designado por Dios,
que sea capaz de llevar a cabo esta obra.
Todos los demás caminos, medios e invenciones de los hombres,
no son capaces de romper ni un eslabón de las cadenas de oscuridad.
Es la fe en Cristo, la luz, que convence al mundo de pecado, la que puede hacerlo.
Y a pesar de que esta luz resplandece en el mundo, es decir en las tinieblas,
en los hombres impíos, sin embargo, por no tener fe en ella,
ni creer en ella como eso en donde Dios mora,
nunca experimentan su poder y virtud que salva.
Aun así, estos no escaparán de su poder que reprueba y condena.

[.centered]
=== LII. Conocer Su Nombre

Es una bendición que las personas conozcan el nombre del Señor, incluso,
así como algunos lo conocieron en épocas pasadas
(y han dejado escrito su conocimiento y experiencia),
quienes podían decir y dar testimonio de que el nombre del Señor era como una adarga,
como un escudo, como una torre, sí,
como una torre fuerte a la cual los justos podían correr y estar a salvo.
Es muy precioso que las personas conozcan el nombre del Señor de este modo,
y se reúnan juntas en él. Estas personas tienen la capacidad de disfrutar,
poseer y heredar todas las bendiciones que alguna vez fueron prometidas,
y evitar y escapar de todas las maldiciones que alguna vez fueron proferidas.

La luz gloriosa del evangelio (que ya alumbra) es el nombre del Señor
por el cual Él se nos ha manifestado en este nuestro día y era.
A medida que esperamos juntos, y caminamos en este nombre,
testificamos y experimentamos el cumplimiento de esta promesa:
"`Donde están dos o tres congregados en mi nombre, allí estoy Yo en medio de ellos.`"^
footnote:[Mateo 18:20]
Estos sienten a su Maestro, a su Salvador, en medio de ellos,
y sus ojos están puestos en Él, y sus oídos abiertos a Su voz,
el cual es un maestro que en verdad enseña provechosamente.
Muchos que han aprendido de Él pueden decir que muy pronto
se hicieron más sabios que todos sus maestros anteriores.
Así que oírlo y aprender de Él es el bendito fin de toda predicación,
de escuchar y creer en el evangelio, y de todas las ordenanzas, ministraciones,
dispensaciones y apariciones de Dios, desde la caída del hombre--es decir,
escuchar y obedecer la voz del Hijo de Dios, quien es luz y mora en la luz,
en la cual los justos en todas las eras gozaban de comunión con Dios,
y el uno con el otro.

Conocer este nombre es más que solo hablar o profesar;
conocer este nombre es como un refugio seguro,
como una roca firme y como una torre de defensa cuando el enemigo asalta,
cuando ríos de tentaciones invaden, cuando saetas vuelan por la noche,
y no cesan en el día, incluso cuando las tormentas descienden y los vientos soplan.
Este era y es el bendito fin del conocimiento vivo
del nombre del Señor en todas las eras:
salvar y preservar a aquellos que tienen este conocimiento,
de todos los peligros que los asechan, en todo tiempo y en todo lugar,
y del enemigo de sus almas, para que sus dardos de fuego no les hagan daño,
ni sus ríos los ahoguen, ni las tormentas y los vientos los derriben,
ni los enemigos de su propia casa prevalezcan sobre ellos.
Esta era la razón por la que aquellos que lo conocían lo comparaban con una torre fuerte, etc.
Ellos a menudo meditaban en él, y pensaban en el nombre del Señor,
y por esto encontraban fuerza para abstenerse de toda especie
de mal y para resistir al diablo en todos sus asaltos.
Este es un estado feliz en verdad,
que solo disfrutan aquellos que conocen de manera viva el nombre del Señor,
y pueden confiar en él.

Por esto pueden ser probados y medidos todos los simples profesantes
de las distintas denominaciones en la cristiandad (así llamada),
quienes hablan y profesan mucho del nombre del Señor, pero no se apartan de iniquidad,
ni dejan de hacer lo malo,
ni conocen Su nombre como una torre fuerte que los salva
y los preserva de la fuerza y poder del enemigo de sus almas.
Estos, yo digo, a pesar de su altiva profesión del nombre del Señor,
no se apartan de la iniquidad.
Y aunque mencionan Su nombre con sus bocas, aborrecen ser reformados por Él,
lo cual es una gran abominación al Señor, y es algo que hiede a Sus narices.
Porque esto testifico en el nombre del Señor:
que todas las personas sobre la faz de la tierra (no importa cual sea la denominación
o el tipo de religión que tengan) que profesen el nombre del Señor,
pero se encuentren haciendo lo malo, su profesión es vana, y su religión es una mentira.
En pecado viven, y en pecado morirán,
a menos de que lleguen a experimentar ese arrepentimiento del que no hay que arrepentirse.
Hasta que esto ocurra,
nunca llegarán a conocer el nombre del Señor como una torre fuerte,
como una adarga o escudo,
sino que en vez de esto serán llevados cautivos y atrapados por el enemigo de sus almas,
según a él le plazca.

[.centered]
=== LIII. El Poder de la Fe

En esto consiste nuestra bendición y eterna felicidad:
en que nuestros ojos se mantengan siempre puestos en Jesús,
el autor y el consumador de nuestra fe, y no solamente conocerlo como el autor,
como el que comienza la fe, sino también como el consumador,
como el que la lleva a su fin, de modo que experimentemos el fin de la fe,
que es la salvación de nuestras almas.
Los que hacen esto sienten "`más cerca la salvación que cuando creyeron al principio.`"^
footnote:[Romanos 13:11]
Es una bendición tener y conocer esa fe de la que Jesús es el autor;
la medida más pequeña de ella es muy preciosa, y muy poderosa.
Aunque es como un grano de mostaza, ella quita los montes, y hace cosas maravillosas.

Muchos son testigos vivos en esta era, como en las eras pasadas,
del poder de la fe incluso al comienzo de su obra.
Pero es un estado más sublime experimentar el fin de ella, la consumación de la fe,
es decir, sentir su obra hecha,
experimentar el corazón purificado por ella y la victoria sobre el mundo obtenida,
el maligno sometido, vencido, derribado y destruido.
Este es un estado bendito en verdad, y algo que todos deben esperar,
anhelar y experimentar.
La única manera de obtener esto es teniendo puestos los ojos siempre en Jesús,
y mantener el ojo de la mente hacia a Él, y el oído abierto a Él,
quien es el único que enseña provechosamente, incluso en silencio,
cuando no se pronuncia ninguna palabra externa.
Este es el bendito fin del ministerio y de los ministros
de la verdad que el Señor ha enviado entre nosotros,
y de toda predicación, escrito y publicación, a saber,
que los ojos de todos se vuelvan a Jesús,
y siempre estén puestos en Aquel que ha comenzado la buena obra,
y quien es el único que puede terminarla.

[.centered]
=== LIV. Los Ciudadanos de Sion

Es un estado bendito ser como extranjeros y peregrinos en la tierra,
y ser capaces de decir en verdad (como dijeron algunos en la antigüedad):
"`No tenemos aquí ciudad permanente, sino que buscamos la por venir.`"^
footnote:[Hebreos 13:14]
Yo digo que este es un estado bendito;
pero es una bendición mayor encontrar la ciudad buscada,
sentir que la ciudad celestial ha llegado, es decir,
sentir la Jerusalén celestial descender de arriba, de Dios, desde el cielo,
y ser ciudadanos de ella.
Estos habitan en una morada de quietud, y son redimidos de la tierra.
De hecho,
aquellos que moran en esta ciudad celestial (donde ninguna
cosa impura puede entrar) no moran en la tierra,
ni habitan en sus rincones oscuros, donde están los ayes y la miseria, como está escrito:
"`¡Ay de los moradores de la tierra! porque el diablo ha descendido a vosotros,`"^
footnote:[Apocalipsis 12:12] etc.

¡Oh,
que nadie que hable de la Jerusalén celestial y profese ser ciudadano
de ella sea hallado como un morador de la tierra! ¡Y que todos
los que aún no son conciudadanos con los santos en luz,
que no moran dentro de sus puertas, viajen hacia Sion, hasta que lleguen a morar allí,
y se conviertan en ciudadanos libres de ella! ¡Oh esfuércense por alcanzar esto,
para que puedan experimentar el ser sentados en el reino!
Este es el fin de nuestro peregrinaje, el fin de buscar esa ciudad que permanecerá,
cuyo Arquitecto y Constructor es Dios.
De hecho, Él es adorado en Espíritu y verdad en esta ciudad,
y recibe alabanzas eternas de todos sus habitantes.
El judío externo, la Jerusalén externa, el templo externo, con sus muebles,
su adoración y sus adoradores externos, eran sombras, figuras y tipos de estas cosas.
Jerusalén era el lugar de adoración,
y todos debían regresar allí para adorar,
para presentar sus ofrendas y ofrecer sus sacrificios.
Y dondequiera que las personas oraban o adoraban,
tenían que volver sus rostros hacia la ciudad de Jerusalén.
Ahora el antitipo y sustancia de estas cosas,
y de todas las benditas promesas relacionadas con esto,
es ser hechos testigos vivos de la venida de la Jerusalén celestial,
y convertirse en conciudadanos con los santos en luz.
Todos los que todavía no han llegado a esto (más sin embargo
están en el camino que lleva a ello) deben esperarlo.

[.centered]
=== LV. La Palabra de Fe.

Es un dicho verdadero, grabado en las Escrituras, que "`la palabra está muy cerca,
en la boca y en el corazón;
nadie tiene que subir para traerla abajo o descender para hacerla subir.`"^
footnote:[Deuteronomio 30:14; Romanos 10:8]
Esta era la Palabra de fe, que predicaban y creían los primeros cristianos,
y ahora es predicada y creída nuevamente por un remanente en esta era.

Bienaventurados todos aquellos que conocen,
experimentan y permanecen en esta Palabra de fe,
y escuchan y obedecen su voz y sus enseñanzas, y aprenden de ella,
no solo cuando se congregan en un lugar, sino en todo tiempo y lugar,
y que incluso en sus actividades cotidianas le dan su oído a ella y reciben sus instrucciones.
Estos sin duda serán hechos sabios para la salvación. Estos no
estarán siempre aprendiendo y nunca llegando al conocimiento,
ni permanecerán cargados con pecado, ni serán llevados por diversos deseos,
sino mas bien experimentarán la poderosa salvación de Dios a través de la fe en la Palabra,
que es viva, aguda y poderosa.
Es viva para enseñar e instruir en todo lo que es bueno,
y para reprender y condenar todo lo que es malo.
Y es aguda y poderosa para cortar y destruir eso que antes cargaba
con pecado y llevaba a las cosas que son malas.

Escuchar y obedecer esta Palabra de vida, esta Palabra de Dios que habla en el interior,
que está cerca en la boca y en el corazón,
es el único fundamento de todo aprendizaje y conocimiento verdadero.
Todos los que desprecian su voz,
cierran sus oídos contra sus enseñanzas y no tienen fe en ella,
aunque se llenen de todo el aprendizaje académico del mundo,
y sean oidores diligentes de la voz de los hombres y de los libros, aun así,
estos seguirán siendo ajenos e ignorantes de la sabiduría pura que santifica y satisface,
y de la salvación pacífica de Dios.
De hecho, estos permanecerán bajo la carga y poder del pecado,
y estarán sujetos a la orden de sus deseos, voluntades y pasiones.
La falta de fe en la Palabra y poder de Dios en el corazón,
y el negarse a escuchar Su voz suave y delicada, es el motivo y causa de toda ignorancia,
errores, oscuridad y confusión entre los hombres,
en todas las sectas y clases de religión sobre la faz de toda la tierra.

[.centered]
=== LVI. Los Frutos de la Fe

Es algo precioso tener fe,
y tener los ojos puestos siempre en Jesús el autor y consumador de esta fe,
y crecer en ella de un grado a otro.
Los que esperan, caminan y viven unidos en esta fe, de la cual Jesús es el autor,
son el pueblo bendito.
Esta es la misma "`fe que ha sido dada una vez a los santos,`"^
footnote:[Judas 1:3]
siendo el don de Dios y no del hombre.

La medida más pequeña de esta fe es muy poderosa porque,
aunque no sea más que un grano de mostaza,
es capaz de remover montañas. Todos los que sienten el crecimiento e incremento de ella,
y en verdad perseveran ahí, llegan a conocer a Jesús no solo como el autor,
sino también como el consumador de la fe.
Él no solo es el que comienza la fe, sino el que la consuma; porque la fe tiene un fin,
a saber, la salvación del alma.^
footnote:[1 Pedro 1:9]
Todos los que alcanzan ese fin pueden regocijarse en la salvación de Dios,
la cual se ha acercado más a ellos que cuando creyeron al principio.

Que todas las sectas del cristianismo que hablan de tener
fe en Dios prueben y examinen qué ha hecho su fe por ellos.
Si no ha removido los montes de oscuridad e ignorancia,
si no ha purificado sus corazones, si no les ha dado victoria sobre el mundo,
ni los ha salvado del mal que está en él, ni los ha capacitado para agradar a Dios,
vivir para Él y encontrar aceptación con Él--Yo digo,
si ellos no sienten estas cosas hechas en ellos y por ellos,
pueden concluir infaliblemente que su fe está muerta,
y que no es esa fe que es don de Dios,
que fue una vez dada a los primeros santos (y recibida por ellos),
de la cual Jesús era el autor.
Al contrario, ellos tienen una fe creada por ellos mismos,
que es como la fe de los demonios, que "`creen y tiemblan`"^
footnote:[Santiago 2:19]--este es el único fruto y efecto
de la fe de los demonios y de los hombres impíos.

[.centered]
=== LVII. Llamados a Heredar la Sustancia

La experiencia de estar reunidos y de esperar juntos en el nombre
de Jesús es una bendición. Los que se reúnen en este nombre,
y sienten a Jesús, el pacífico Salvador, en medio de ellos,
experimentan el adorno celestial de un espíritu afable y apacible.
Estos sienten al Príncipe de paz y Su gobierno pacífico, al Cordero sobre el trono,
al Justo dominando; sienten la tierra llena alegría y la paz celestial en su territorio.

Aquellos que verdaderamente esperan y se reúnen en este nombre,
disfrutan todas las bendiciones prometidas.
Son estos los que sienten que su fuerza, fe y confianza en Dios son renovadas,
y que su sabiduría y conocimiento crece con el crecimiento que da Dios.
Ellos sienten que la luz va en aumento hasta que el día es perfecto,
tal como fue testificado en la antigüedad:
"`La senda de los justos es como la luz de la aurora,
que va en aumento hasta que el día es perfecto.`"^
footnote:[Proverbios 4:18]
Pero antes de que se experimente este día,
"`Jerusalén debe ser escudriñada con linterna`"^
footnote:[Sofonías 1:12]
(es decir, Jerusalén, la ciudad amada y escogida, y cada uno de sus habitantes).
Porque el bendito fin de escudriñarla es limpiarla y purificarla.
De hecho, el juicio comienza por la casa de Dios,
para purgar y barrer todo lo que contamina, y para arrasar a Babilonia,
la ciudad de confusión, el misterio de la impureza.
Cada individuo debe sentir y experimentar estas cosas--es decir,
sentir que Jerusalén es escudriñada y limpiada, y que Babilonia es desolada y destruida,
y experimentar el incremento del reino de los cielos internamente, y que su poder,
luz y gloria brillan cada vez más.

Cuando nos reunimos y permanecemos en este nombre,
sentimos que el reino de Dios está presente y que la voluntad de Dios es hecha,
y que recibiremos cualquier cosa que pidamos en este nombre, según la promesa de Cristo.
Porque no hemos sido llamados a un sonido de palabras, a figuras, tipos y sombras,
o a depender de los labios de otros,
aunque sean capaces de hacer largas declaraciones de la verdad misma;
sino que somos llamados a heredar la sustancia, a sentir a Jesús,
la verdad entre nosotros, al Árbol de Vida en medio nuestro,
a comer de Su fruto y a sentarse bajo Su sombra con gran deleite.
Un remanente ha llegado a estas cosas, y las disfrutan verdaderamente.

Esta es la corona y gozo de los mensajeros y ministros
del Señor cuando están entre nosotros--a saber,
ver que estamos alimentándonos del pan de vida, disfrutando y poseyendo la sustancia,
paz, vida y salvación eterna.
Y es su tristeza y angustia ver a un pueblo profesando la verdad, siempre aprendiendo,
pero nunca llegando al verdadero conocimiento,
siempre escuchando y sin embargo ignorante de la voz de la palabra de vida en sí mismos,
y de ese pan vivo que desciende del cielo.

[.centered]
=== LVIII. Amando las Apariciones de Cristo

Para aquellos que creen, Cristo es muy precioso.
Aquel, a quien las naciones desprecian y los edificadores desechan,
ha venido a ser la cabeza de ángulo para todos los que creen.
Estos lo aman en todas Sus apariciones, manifestaciones, dispensaciones y operaciones,
ya sea que aparezca como un juez, como uno que convence, que reprueba,
que refina con fuego y lava con jabón, o como un consolador, salvador o príncipe de paz.
En todas estas apariciones, Él es precioso para aquellos que creen en Él,
porque ellos saben y creen que el bendito fin de cada aparición
y operación de Su Espíritu en ellos es hacerlos felices.

Es una gran bendición experimentar Su aparición como un juez, como uno que reprueba,
que refina y que lava, etc.
Esto es mucho más que una mera profesión religiosa,
y va más allá de la experiencia de todos los cristianos
nominales sobre la faz de la tierra.
Pero es una bendición mucho mayor sentir a Cristo como el que termina la obra,
experimentar el juicio llevado a la victoria, experimentar ser refinados,
ser purificados, ser santificados y salvados.
Este es un estado que cada creyente debe esperar y experimentar,
sin el cual no pueden ser cristianos verdaderos,
israelitas verdaderos en quienes no hay engaño.

Porque esto testifico, que este es el fin de la bendita aparición del Hijo de Dios,
de la luz, gracia, Espíritu,
poder o amor de Dios en el interior (todo lo cual es una sola cosa,
aunque con diferentes nombres):
obrar y operar en cada uno de los que verdaderamente creen en Él, y lo aman,
con el objetivo de "`poner fin al pecado, expiar la iniquidad,
y traer la justicia perdurable.`"^
footnote:[Daniel 9:24]
Este es el bendito fin de todas sus operaciones.
El cristiano de nombre, que habla de Cristo y de Sus oficios, tales como rey,
sacerdote y profeta, salvador y redentor,
etc. pero que no lo conoce primero como un refinador, lavador,
como uno que purifica la era y quema la paja con un fuego que nunca se apagará,
engaña a su propia alma con palabras vacías y con una religión vana,
y por lo tanto nunca experimenta a Aquel que pone fin al pecado,
expía la iniquidad y trae la justicia perdurable.
A menos que esto sea experimentado, toda religión es vana,
y las personas se engañan a sí mismas con el nombre de cristianos,
cuando no tienen su naturaleza.

Es muy precioso, y absolutamente necesario,
que cada individuo que profesa el nombre de Cristo, y dice que cree en Él,
sienta y conozca su corazón y su mente verdaderamente
enamorados de cada una de Sus apariciones en el alma,
con el fin de seguirlas y obedecerlas, y de disfrutar el fin de ellas, a saber,
traer la justicia perdurable y poner fin al pecado,
para que el Señor aparezca por segunda vez sin relación
con el pecado para salvación. En verdad,
esto es digno de ser esperado.
A medida que cada uno ama la aparición de Cristo,
y se une con ella en su corazón contra toda especie de mal,
está en el camino que lleva a la vida, paz y salvación eternas.
Este es el camino nuevo y vivo, y no hay otro.

Todos los que están fuera de este camino, y son ajenos a él en sus mentes,
teniendo sus corazones separados de él, nunca llegan a heredar la sustancia,
ni a sentir a Aquel que trae la justicia perdurable y termina y echa fuera la injusticia;
tampoco experimentan cómo la casa es barrida, purificada y limpiada,
ni cómo el alma se convierte en morada de Dios en el Espíritu.
En lugar de esto, continúan siendo como una jaula de pájaros inmundos,
y una morada de chacales.
Aunque hablan de la fama de la sabiduría, santificación, redención, justicia y salvación,
aun así, son hallados en lo contrario--en cautiverio y esclavitud.
De hecho, aunque hablan de libertad y redención, santificación y justicia, aun así,
caminan en inmundicia y corrupción. Que a todos los que les conciernen estas cosas,
las consideren.

[.centered]
=== LIX. Inclinándose ante Jesús

Es una bendición que las personas se reúnan unánimes en un solo lugar,
todos volviéndose a una misma cosa,
cada mente ocupándose de la operación del Espíritu
y de la verdad donde únicamente Dios es adorado.
Esta es la adoración a la que un remanente ha sido llevado,
cuya adoración no siempre comienza cuando empiezan sus reuniones solemnes,
ni termina cuando se despiden.
Es cuando cada uno es hallado en esto,
que ellos y su adoración difieren de todos los adoradores
formales sobre la faz de toda la tierra,
cuya adoración consiste en las tradiciones e invenciones de los hombres,
en tiempos y lugares prefijados, en decir ciertas oraciones, leer diversas lecciones,
en predicar y cantar, etc.
Pero cuando cada mente se entrega a la operación de la verdad,
todo lo que es contrario a ella dobla rodillas y se inclina ante ella.
Todo pensamiento, toda imaginación, todo deseo y afecto es sometido a la verdad,
y adora o se inclina ante el nombre de Jesús. Esto es más que doblar las rodillas,
o cualquier otro tipo de ejercicio corporal.
Esto es más que la adoración "`sobre montes o en Jerusalén`"^
footnote:[Juan 4:21]
de todas las diversas formas en el cristianismo.
Porque cuando la mente se dedica a la carne y el corazón es corrupto,
y cuando la consciencia está contaminada y el entendimiento entenebrecido,
todo no es más que religión humana,
una obra del yo y una humildad falsa que Dios no acepta.

[.centered]
=== LX. El Consolador

Lo que Cristo habló a sus discípulos cuando dijo: "`Si no me fuera,
el Consolador no vendría,`"^
footnote:[Juan 16:7]
es un dicho verdadero.
Hay mucho en esas palabras.
Muchos las han leído, pero no han entendido lo que han leído,
porque es una verdadera bendición experimentar que Cristo se vaya según la carne,
y poder decir (como lo hizo uno en la antigüedad)
que nosotros "`ya no lo conocemos así.`"^
footnote:[2 Corintios 5:16]
Estos son los que lo experimentan apareciendo otra vez en el Espíritu como un Consolador,
como un Príncipe de paz, y son testigos vivos de Su gobierno pacífico en sus almas,
y pueden decir: '`Él ha llegado, y no buscamos a ningún otro.`'

[.centered]
=== LXI. El Pan de Cada Día

En verdad, han venido de la presencia del Señor tiempos de refrigerio;
las aguas del cielo están cayendo y el maná celestial está descendiendo como la lluvia.
De hecho, muchos se han refrescado de manera viva,
y se han vuelto como un huerto de riego.
Aquellos que eran como un desierto y un yermo ahora están floreciendo como la rosa;
y aquellos que eran estériles ahora producen y llevan fruto para Dios.
De parte del Señor es esto, y es cosa maravillosa a los ojos de un remanente.

Bienaventuradas las personas que pueden reunirse unánimes,
y sentarse delante del Señor a esperar en Él. A estos
a veces se les concede sentarse como en un banquete,
y tener una mesa ricamente abastecida delante de ellos;
ellos comen y beben y sus almas son satisfechas.
Su felicidad y bendición eterna consiste en lo siguiente:
en sentir sus mentes y sus corazones acercándose continuamente al Señor, y puestos en Él,
no sólo en sus reuniones solemnes, sino en otros tiempos.
En esto son preservados diariamente en una capacidad de participar
de las misericordias y bendiciones del Señor. Este es un estado
bendito y seguro en verdad--sentir la mente puesta en el Señor,
el corazón fijo, unido y afirmado en el Señor. Estos no pueden ser movidos fácilmente,
ni el enemigo puede prevalecer contra ellos,
ni el extraño entrometerse en su alegría. Se le dará su pan,
y sus aguas serán seguras y experimentan la verdad de esas palabras que dijo el profeta:
"`Tú les guardarás en completa paz, cuyas mentes en ti perseveran.`"^
footnote:[Isaías 26:3 Reina Valera 1602 Purificada]
¿Qué pudiera desearse más que esta completa paz, esta paz que es absoluta,
que no le falta nada y que está llena de satisfacción y regocijo en el hombre interior?
¡Oh,
qué hubiera dado un remanente en los tiempos pasados
por sentir sus mentes puestas siempre en Él,
por conocer el tesoro celestial, que es suficiente para satisfacer,
refrescar y consolar sus almas!
Esta es la perla de gran precio.
Esto es comer del Árbol de Vida en verdad,
y es el único camino y medio para llegar a la posesión de todos los tesoros
de la sabiduría y del conocimiento que están escondidos en Cristo Jesús,
y a heredar todas las bendiciones que acompañan la religión cristiana que profesamos.
Pero aquellos que son de una mente errante, cuyos pensamientos,
voluntades y afectos no están sometidos ni crucificados,
se encuentran en ese estado en el que no saben cuándo viene el bien,^
footnote:[Jeremías 17:6]
y son como cisternas rotas que no retienen agua.^
footnote:[Jeremías 2:13]

Así que esta es la cosa principal en la que consiste nuestra seguridad y felicidad,
a saber,
sentir nuestras mentes y corazones acercándose al Señor y nuestros ojos fijos en Él,
para que después de haber participado de Sus bendiciones
y haber sido refrescados con Su presencia,
podamos permanecer en una postura interna que está preparada para recibir de Él aquello
que satisface nuestras almas y que ministra a nuestras mentes el verdadero contentamiento.
Sólo el pan de cada día puede hacer esto.
Lo que comamos hoy, no servirá mañana.
Danos hoy nuestro pan de cada día,
un pan fresco todos los días de la mesa del Señor. Aquí
se experimenta el crecimiento de un grado de gracia a otro,
de un grado de fe a otro, de un grado de gloria a otro, sí,
hasta que todos lleguemos a la estatura y plenitud de Cristo.
Cuanto más alguien espere verdaderamente para disfrutar esto,
más sentirá su fuerza renovada con un aliento celestial, para que corra y no se canse,
y camine y no se fatigue.

[.centered]
=== LXII. La Voz Suave y Delicada

Escuchar y obedecer la voz suave y delicada, que dice: "`Este es el camino,
andad por él,`"^
footnote:[Isaías 30:21]
es lo que hace que un pueblo sea bendito y feliz.
Esta es la voz del verdadero pastor, y las ovejas la conocen, la siguen y la obedecen,
mas al extraño no oirán ni seguirán. En esto consistía la seguridad,
fuerza y bendición de los justos en todas las eras y generaciones pasadas, a saber,
en oír y obedecer la voz del Señor. Por esto obtuvieron victoria sobre sus enemigos,
y los vieron a todos confundidos y llevados a la nada.
Y esto también es la fuerza y bendición de los justos en esta era y generación,
por lo cual nosotros también vencemos a nuestros enemigos.

A medida que escuchemos y obedezcamos esta voz,
nos haremos cada vez más fuertes y prevaleceremos contra nuestros enemigos,
incluyendo a los de nuestra propia casa, que son nuestros más grandes enemigos.
Cuando obedecemos esta voz celestial,
somos llamados a salir de todos los caminos y senderos torcidos del pecado y la transgresión,
al camino derecho y vivo del Señor,
y somos preservados allí. Su voz guía fuera del camino del pecado y la transgresión,
para que no estemos cautivados en el camino de la oscuridad y del error,
fuera del cual hemos sido llamados,
y del cual hemos sido redimidos y salvados con una salvación muy grande.
Alabanzas sean al nombre del Señor, quien ha hecho que Su glorioso día amanezca,
y que Su voz celestial se escuche y se distinga de todas las voces que están en el mundo,
y de la voz de la serpiente.
Y bendito sea el Señor, que, aunque Su voz muchas veces es muy baja y delicada, aun así,
nosotros la escuchamos y la distinguimos de la voz
de nuestro enemigo y de la voz del extraño,
porque ella nos llama fuera de todo mal y error, a la pureza y santidad.
Nos llama fuera de toda voluntad propia, de todo pensamiento e imaginación,
a la quietud celestial, a la negación del yo,
a una profunda humildad y a una bajeza de mente,
que es el valle de la humillación en el que se encuentran los pastos delicados,
y en donde se sienten los manantiales de vida,
se disfruta la satisfacción y se posee la paz y la tranquilidad de mente.
Esta es la sustancia de todo.
Esto es aquello a lo que hemos sido llamados en este
glorioso día de la aparición de Dios,
en esta Su visitación desde lo alto con Su aurora,
que resplandece gloriosamente sobre un remanente.
¡Alabado sea Dios por siempre!

[.centered]
=== LXIII. Mi Redentor Vive

Bendito el pueblo que no necesita buscar a su Maestro, a su Salvador y a su Redentor,
sino que en lugar de esto sus ojos Lo ven, y sus oídos escuchan Su voz,
y ellos experimentan y disfrutan lo que uno de la antigüedad conocía, cuando dijo:
"`Yo sé que mi Redentor vive, y permanecerá hasta el final sobre la tierra.`"^
footnote:[Job 19:25 Traducción Literal del Inglés]
Este es un estado celestial (que experimenta un pequeño remanente), a saber,
ver a su Redentor permanecer hasta el final sobre la tierra.
Él fue el primero sobre ella, y será conocido como el último también,
sometiendo todo bajo Su dominio,
la tierra volviéndose el estrado de Sus pies--toda la mente terrenal,
todo deseo y afecto terrenal, estando hollados y pisados por Él. De hecho,
en este estado celestial,
todo pensamiento vano e imaginación altiva es sometido bajo Sus pies,
y todos nuestros enemigos son destruidos por Él. Pero ningún pueblo o persona
sobre la faz de la tierra puede experimentar estas cosas efectuadas en ellos,
salvo en la medida que viaje a través de la obra de regeneración,
y llegue a sentir que su Redentor vive, no sólo en Sí Mismo, sino también en ellos.
Entonces se siente al que pone fin a la transgresión, y trae la justicia perdurable.
Entonces el Príncipe de paz y justicia reina, y se sienta sobre el trono y gobierna,
incluso donde el príncipe de la potestad del aire e injusticia gobernaba.
Entonces la tierra se alegra y la paz celestial abunda en sus moradas,
cuya paz ninguno puede disfrutar (independientemente de lo que profese,
aunque sea la verdad misma) a menos que conozca por experiencia a su Maestro,
a su Salvador y a su Redentor.

[.centered]
=== LXIV. La Calzada del Señor

El recuerdo mismo del tiempo en que nuestras mentes fueron vueltas
a la luz verdadera que ya alumbra (no solo en la oscuridad,
sino fuera de ella) es muy precioso.
Es en esta luz que Dios mora,
y nosotros somos testigos vivos de Su presencia y aparición,
la cual ministra mayor consuelo, refrescamiento y alegría en nuestros corazones,
que cuando abunda el grano, el mosto y el vino.

El abundante amor y bondad de Dios al equipar y preparar instrumentos en Su propia mano,
y por Su propio poder,
para volver y dirigir nuestras mentes a la luz de Cristo en nuestro corazón,
al poder de Dios en nuestro interior, nunca será olvidado.
Esperar en esta luz, y ser obedientes a ella,
es lo que nos diferencia a nosotros y a nuestras reuniones,
de aquellos que son ajenos a ella.
Y a medida que esperemos en esta luz y la obedezcamos,
nunca tendremos la necesidad de buscar a un maestro, a un guía o a un instructor,
aunque ninguna palabra sea dicha externamente.

Es algo precioso amar esta luz y andar en la misma,
porque esta es la única manera de ser un hijo de ella.
Esta es la calzada que según la profecía debía ser edificada, en la que "`los errantes,
aunque fueren torpes, no se extraviarían.`"^
footnote:[Isaías 35:8 Reina Valera Gómez]
No hay tropiezo en este camino, ni ocasión de caer.
A medida que caminamos y permanecemos allí, somos el pueblo más contento, sabio,
fuerte y feliz que hay sobre la faz de la tierra.
Pero fuera de este camino, somos tan débiles como cualquier otro pueblo.
Y, de hecho, después de haber conocido este camino, también podemos,
si no permanecemos en él, volvernos tan impíos como cualquier otro.

No hay otro camino que buscar, ni otro evangelio que predicar aparte de este,
al cual nuestras mentes fueron vueltas al principio, a saber, la luz,
la gracia y el poder de Dios, la perla, el tesoro, el reino de Dios en el interior.
En este camino se experimenta la llave que abre no solo el misterio de la piedad,
sino también el misterio de la iniquidad, y hace que nuestro ojo esté satisfecho con ver,
nuestro oído con oír y nuestro corazón con entender.
¡Oh, cómo somos llamados a andar en este camino,
y a caminar como es digno de este amor que ha sido derramado en nuestros corazones,
del cual hemos sido hechos participantes! ¡Oh,
que podamos adornar nuestra profesión con toda santidad en nuestra vida y conducta,
para la alabanza de Aquel que nos ha llamado fuera de las tinieblas
a Su luz maravillosa! ¡A Él sea la gloria para siempre!

[.centered]
=== LXV. La Levadura del Reino

Es una bendición sentir que el reino de Dios ha llegado, sí,
el mismo reino por el cual Cristo enseñó a Sus discípulos a orar hace mucho tiempo,
y por el cual ha enseñado a sus discípulos a orar en esta
era también. Es una bendición sentir que este reino ha llegado,
pero es una bendición mayor experimentar ser sentados en él, y participar de eso,
a saber, en la paz y el gozo en el Espíritu Santo,
que todos los reinos de este mundo no pueden dar ni quitar.

Ahora bien,
la razón por la que en tiempos pasados nosotros (al igual
que otros) éramos ignorantes de la venida de este reino,
y carecíamos del disfrute de eso, era que menospreciábamos su aparición,
y pasábamos por alto la semilla de este, y despreciábamos su operación,
que es como la de la levadura en la masa.
Esta era la causa: que nosotros "`menospreciábamos el día de las pequeñeces.`"^
footnote:[Zacarías 4:10]
No teníamos nada de fe en el poder santo ni en la
aparición espiritual de Dios en el corazón,
aunque solo era como un poco de levadura, o como una semilla pequeña,
que siempre actuaba contra el mal, y contra el autor de este y su reino de oscuridad.

Ahora bien, todas las sectas y sus líderes en la Cristiandad,
que pasan por alto la semilla del reino (que actúa como una levadura
en todos aquellos que tienen fe en ella) y desprecian la aparición
y operación de la luz y Espíritu de Dios en el interior,
estos nunca experimentan la venida del reino de Dios,
ni llegan a sentarse en él. Estos heredan vanidad,
cosechan dolor y son sepultados en miseria,
sin importar qué tan sublimes sean sus palabras y su religión. De hecho,
esta es la palabra de verdad para todos ellos.
Pero todos los que han experimentado la venida de este reino, y se han sentado en él,
y han disfrutado de eso (que es paz y gozo en el Espíritu Santo),
estos son testigos vivos de cómo el Señor los ha reunido del oriente, del occidente,
del norte y del sur, y los ha sentado con Abraham, Isaac y Jacob, en el reino de Dios.
Estos pueden decir, como pudieron decir algunos de la antigüedad,
a quienes el autor de los hebreos escribió:
"`Sino que os habéis acercado al monte de Sion, a la ciudad del Dios vivo,
Jerusalén la celestial, a la compañía de muchos millares de ángeles,
a la congregación de los primogénitos que están inscritos en los cielos,
a Dios el Juez de todos, a los espíritus de los justos hechos perfectos,
a Jesús el Mediador del nuevo pacto,
y a la sangre rociada que habla mejor que la de Abel.`"^
footnote:[Hebreos 12:22-24]
Si estas cosas no estuvieran escritas en las Sagradas Escrituras,
podría considerarse ilícito, y hasta blasfemia, hablar o escribir de esta manera.
Pero el reino y poder de Dios es uno y el mismo en todas las eras,
y es la morada de los justos en todas las generaciones.

A este reino y poder nuestras mentes fueron vueltas y dirigidas al principio,
cuya primera aparición fue como una luz que alumbra en un lugar oscuro,^
footnote:[2 Pedro 1:19 Reina Valera 1602 Purificada]
como una semilla pequeña que brota de una tierra seca,
como un poco de levadura operando en la masa,
según las parábolas y enseñanzas de Cristo Jesús. Esta fue la porción y herencia
que los hombres y mujeres santos en tiempos pasados esperaron y recibieron.
De hecho, ellos glorificaron y alabaron a Dios por concederles el disfrute de esto,
incluso en medio de aflicciones y ardientes pruebas, y sobre todas ellas.
Esto era su gozo y corona, y los justos en esta era no desean otra cosa.

[.centered]
=== LXVI. El Pan Que Alimenta

Hemos sido y somos llamados a heredar sustancia,
y todos aquellos que han obedecido este llamado,
y han permanecido con Aquel que los ha llamado,
experimentan ese pan que alimenta para vida eterna.
Estos experimentan la hermosura y placer que se siente
al comer de ese pan que desciende del cielo.
El pan externo, sobre la mesa externa, en el templo externo,
fue una figura y representación de este pan celestial,
que nutre a aquellos que se alimentan de él para vida eterna.

Reunirse, y sentarse juntos en esta mesa, y comer de este pan,
es mejor que sentarse en tronos con príncipes, y comer de sus deleites.
Todos los tesoros y placeres de este mundo no pueden compararse con esto;
porque no hay nada que pueda contentar al alma,
ni detener su hambre y su sed de esas cosas que se destruyen con el uso,
salvo comer de este pan.
Y en verdad, mientras más uno come de este pan,
más hambre tiene de él. Hay un placer y bendición en tener hambre y sed cuando
el suministro del pan vivo y de las aguas vivas está cerca y preparado para suplir.
Porque es el gustar de las migajas que caen de la mesa de los hijos
lo que engendra este clamor en los corazones de un remanente:
"`¡Danos siempre este pan!`"^
footnote:[Juan 6:34]

[.centered]
=== LXVII. Manteniendo los Ojos Puesto en el Señor

Benditos todos los que tienen sus ojos puestos en el Señor, y su oído abierto a Él,
en todo tiempo, en todo lugar y en todos los estados y condiciones.
Porque en verdad, Dios ha venido para enseñar a Su pueblo Él mismo,
como fue profetizado hace mucho tiempo atrás. Todos los que han aprendido de Él,
y son guiados por Su Espíritu,
son de este modo llevados dentro del velo al lugar santísimo,
y sienten que el velo es quitado--no solo el velo de Moisés y el del templo externo,
sino también el velo de la carne de Cristo.
Estos llegan a contemplarlo a Él, y a morar con Él,
quien existía antes de que se necesitara velo,
antes de que hubiera necesidad de profetas y de que Cristo sufriera.
Es precioso contemplar este estado, y muy placentero disfrutarlo.
Esta es la luz de Su rostro en verdad, que es mejor que el grano, el vino,
el aceite o que todas las cosas visibles.
Este es el bendito fin de esperar en Dios así "`como
los ojos de la sierva esperan la mano de su señora.`"^
footnote:[Salmo 123:2]
Ya sea que seas como un bebé, como un niño, como un joven,
como un anciano o como un padre,
tu deber en todos estos estados y estaturas es tener tus ojos puestos en el Señor,
para que Él te lleve de una estatura a otra, y te preserve en ella por Su gracia.
De hecho, esta gracia es capaz y suficiente para instruir en toda cosa buena,
salvar y defender de todo mal,
llevar a la gloria y establecerte en su reino para siempre.

[.centered]
=== LXVIII. Templos del Espíritu Santo

Los que verdaderamente pueden decir que sus cuerpos son templos
del Espíritu Santo están en un estado y condición muy benditos,
porque esto es una bendición muy grande.
Estos son aquellos cuyos ojos ven a su maestro;
sus ojos están internamente puestos en Aquel que enseña en Su templo,
y cuya gloria aparece allí. Los que tienen este conocimiento, son un pueblo bendito;
y todos los que lo tienen saben cómo lo obtuvieron
y cómo llegaron a ser templos del Espíritu Santo,
habiendo sido antes templos del espíritu inmundo.
Ellos ahora ven que el templo que estaba contaminado y profanado,
se encuentra limpio y purificado,
y que han sido echados los espíritus inmundos y sus obras.
Y ahora estos son un pueblo que vela contra todo
lo que puede contaminar el templo otra vez,
y ellos son los verdaderos adoradores del templo en este día y era.

Este es el templo en el que todos hablan de la gloria del Señor,
del poder del Señor y de Sus maravillas hechas allí, en Su "`templo no hecho de manos.`"^
footnote:[Hebreos 9:11]
Este es el antitipo y sustancia del templo externo que construyó Salomón,
y de las distintas adoraciones y servicios que se ofrecían en él--a saber,
cuando las personas son llevadas al estado en el que sienten
que sus cuerpos son templos del Dios vivo,
y cuando Él anda entre ellos, y mora en ellos,
según las antiguas profecías de hombres santos.
Estos son la morada de Dios en el Espíritu.
Estos son los adoradores en Espíritu y en verdad,
no sólo en lugares designados y reuniones solemnes, sino en otros tiempos y lugares,
inclinándose ante cada aparición de Dios en Su templo,
y experimentando a ese Espíritu y verdad en lo íntimo que Dios ama y acepta,
y en la cual se deleita.

Ahora bien, el templo externo, después de haberse terminado y santificado,
fue contaminado, profanado y convertido en una cueva de ladrones; y, por lo tanto,
fue robado y despojado de todos sus tesoros, y entonces fue destruido al final.
Esto sucedió como una figura, y está escrito para nuestra enseñanza.
Por ende, que todos sean vigilantes y estén atentos,
no sea que después de experimentar que sus cuerpos fueron convertidos
en los templos de Dios (habiendo sido santificados o hechos santos)
vuelvan a contaminarse y corromperse otra vez.
A estos Dios destruirá con una terrible destrucción.

Es muy precioso cuando las personas no sólo sienten que sus cuerpos son
templos del Espíritu Santo (cuya experiencia es absolutamente necesaria,
porque sin ella no se puede ser cristiano),
sino que también experimentan una quietud celestial, un silencio celestial en el templo,
sin ninguna compra y venta ni mercadería,
sin el ruido del instrumento de hierro del artífice en el templo.
Porque la obra del hombre contamina el templo y profana el altar,
con tan sólo alzar sobre el instrumento.
Las mejores habilidades, invenciones y artes del hombre en la caída,
no tienen lugar en la edificación del altar, ni en la construcción del templo,
ni en el establecimiento de la adoración ni en la ofrenda de sacrificios a Dios.
Tanto la justicia del hombre como su iniquidad,
ambas son igualmente abominación al Señor.

[.centered]
=== LXIX. El Poder del Evangelio

El evangelio es el poder de Dios para salvación.
Este evangelio fue predicado en el tiempo de Abraham,
sí, incluso en el tiempo de Enoc y de Adán,
y la salvación se obtenía en y a través de este.
Aquellos que obedecieron este evangelio (el poder de Dios) en esas eras,
fueron salvados del mal por medio de él; fueron hechos hombres justos y santos,
y amigos de Dios, y caminaron con Él. Así era antes de la ley,
bajo la ley y durante el tiempo de los profetas.
Todos los que obedecían al Espíritu y poder de Dios, obedecían al evangelio,
y eran redimidos y salvados por él del pecado y la transgresión. Toda la humanidad,
habiendo caído en pecado y transgresión,
tenía necesidad de que el evangelio le fuera predicado,
y que la redención y salvación se experimentaran por él. Y conforme es recibido y obedecido,
se conoce como el poder de Dios para salvación.

El testimonio de Pablo era que él era un ministro "`del evangelio
que fue predicado en toda criatura que está debajo del cielo,`"^
// lint-disable invalid-characters
footnote:[Colosenses 1:23 Traducción Literal "`εν παση τη  κτισει`" es decir "`en toda criatura.`"]
que en verdad era la luz, amor y poder universal de Dios,
apareciendo para la salvación del hombre.^
footnote:[Nota del Editor:
Cuando los primero Cuáqueros hablaban de la luz o amor universal de Dios,
no abogaban en absoluto la idea de salvación o reconciliación universal.
Usaban la palabra universal en relación a su creencia de que Dios le _ofrece_ salvación
a toda la humanidad (y no solo a un número pequeño de personas predestinadas) a través
de la medida de Su luz o gracia que testifica contra el pecado en el corazón,
e invita a todos a buscar salvación en Cristo.
Es esta invitación bondadosa e interna la que es universal.
Cuando esta luz es recibida, seguida y obedecida se vuelve la vida y salvación del alma.
Si es rechazada, la misma luz se vuelve la condenación del hombre.
Véase Juan 3:19-21.]
Todos los que son verdaderos ministros de este evangelio son como su Padre celestial,
cuya luz brilla para todos, cuyas lluvias descienden sobre todos,
cuyo amor se extiende hacia todos.
No son como los rabinos judíos, maestros, sacerdotes o ministros de la letra,
que no predican el poder de Dios que trae salvación a todos los que lo reciben y obedecen.
Estos tampoco llevan a sus discípulos al verdadero amor, paz, unidad,
buena voluntad y afecto fraternal entre ellos y con toda la humanidad,
ni ponen fin a lo contrario.

¡Oh, el estado miserable al que la pobre humanidad ha sido llevada,
y en el que se mantiene cautiva a través de la obra del misterio de la iniquidad
en muchos de los profesantes de nombre en el cristianismo de nombre!
Porque bajo el nombre y profesión del Príncipe de paz, amor, buena voluntad, inocencia,
paciencia, bondad y todas las virtudes santas,
realmente se encuentran y se practican toda clase de guerras, contiendas, crueldad,
violencia, envidia, odio y destrucción el uno al otro.
Estos no son los frutos del evangelio de Dios, ni de su ministerio,
sino más bien de los hombres, del príncipe de confusión y de Babilonia,
y de aquellos que han bebido de la copa de la ramera,
cuyo vino de fornicación ha embriagado a todas las naciones.
El que sea capaz de entender esto, que lo entienda.

[.centered]
=== LXX. La Jerusalén Celestial

Bienaventurados todos aquellos que sienten que son miembros de la verdadera iglesia,
que es hecha de piedras vivas, elegidas y preciosas,
y que han sido convertidos en morada de Dios en el Espíritu y en la Verdad.
Estos se reúnen y esperan en el Señor en silencio, y adoran en Espíritu y Verdad,
sin un libro o sin depender de un ministerio humano.
De hecho, benditos son todos aquellos que son de la verdadera iglesia,
que son piedras vivas, casa y morada espiritual para Dios,
que lo sienten a Él morando en ellos y andando en ellos como en Su templo,
enseñando y gobernando en sus corazones.
Estos son conciudadanos de los santos en la luz, y conocen la ciudad celestial,
Jerusalén, que descendió del cielo, y saben que son habitantes de ella.
Estos han experimentado la redención de entre los de la tierra,
y que la lengua del mar de Egipto se ha secado.
Sí, estos han descubierto el trono de la ramera,
y el misterio de toda su prostitución (en todos sus diversos vestidos,
apariencias espléndidas y trajes lujosos) y ya no pueden ser engañados por estas cosas.
Estos pueden cantar: "`¡Aleluya!
Salvación y honra y gloria y poder son del Señor su Dios.`"^
footnote:[Apocalipsis 19:1]
Estos pueden decir que "`sus juicios son verdaderos y justos;
pues ha juzgado a la gran ramera que ha corrompido a la tierra con su fornicación,
y ha vengado la sangre de sus siervos de la mano de ella.`"^
footnote:[Apocalipsis 19:2]
Estos pueden decir: "`Alabad a nuestro Dios todos sus siervos, y los que le teméis,
así pequeños como grandes, porque el Señor nuestro Dios Todopoderoso reina;
Gocémonos y alegrémonos y démosle gloria; porque han llegado las bodas del Cordero,
y su esposa se ha preparado.`"^
footnote:[Apocalipsis 19:5-7]
En verdad, estos están vestidos de lino fino, limpio y resplandeciente,
el cual es la justicia de los santos,
y el traje de bodas con el que deben vestirse todos los
que son llamados a la cena de las bodas del Cordero,
quienes son miembros de Su cuerpo, que es Su iglesia.
