== Un Tratado Con Respecto a Los Pensamientos e Imaginaciones

Los malos pensamientos e imaginaciones son grandes perturbadores del mundo,
y aquel que está dado a seguir,
obedecer o caminar conforme a sus propios pensamientos e
imaginaciones malos está acompañado y rodeado de gran miseria.
Fue un juicio terrible lo que la palabra del Señor, por medio de Jeremías,
pronunció contra los judíos desobedientes y rebeldes, diciendo: "`Oye, tierra:
He aquí yo traigo mal sobre este pueblo, el fruto de sus pensamientos.`"^
footnote:[Jeremías 6:19]
Y a través del profeta Isaías: "`Extendí mis manos todo el día a pueblo rebelde,
el cual anda por camino no bueno, en pos de sus pensamientos;
que son pensamientos de iniquidad, y obra de rapiña está en sus manos.`"^
footnote:[Isaías 65:2, 59:6-7]
También está escrito:
"`que toda imaginación de los pensamientos del corazón
del hombre es solamente mala todos los días.`"^
footnote:[Génesis 6:5 Reina Valera 1602 Purificada]
Muy grande es la miseria, servidumbre y esclavitud del hombre en este estado; en verdad,
es enemigo de Dios, y de sí mismo, y de sus prójimos y hermanos.
Destrucción y quebrantamiento hay en el camino de
aquellos que no tienen a Dios en todos sus pensamientos.

Ahora bien, lector, lo que está principalmente en mi mente,
es presentarte una manera certera e infalible de cómo puedes
llegar a ser salvo de seguir u obedecer tus propios pensamientos,
y obtener fuerza contra todas tus imaginaciones que son malas,
y alcanzar la victoria sobre ellas.
Y también,
cómo puedes llegar a tener buenos pensamientos y meditaciones
celestiales en lugar de estas imaginaciones perversas,
y a experimentar todo buen pensamiento y deseo llevado a la obediencia de Cristo,
y todo mal pensamiento e imaginación destruido y consumido con el aliento de
Su boca y el resplandor de Su aparición. Y cuando tú hayas sido restaurado y
llevado al mismo estado en el que el hombre estaba antes de la transgresión,
a saber, al huerto de Dios, cómo entonces debes labrar y guardar el huerto.
Tú entonces debes velar sobre tus pensamientos y
gobernarlos (en la sabiduría y poder de Dios),
no sea que la serpiente te engañe como engañó a Eva.

=== La Fuente y Naturaleza de los Malos Pensamientos

Primero,
debes entender que es desde el mismo terreno del cual se
levantan los malos pensamientos e imaginaciones,
que brotan los abrojos, espinos y cardos,
y otras hierbas dañinas en el mundo de la humanidad.
Estas malas hierbas comenzaron a brotar,
crecer e incrementarse en el corazón de Adán desde
el momento en que empezó a perder fe en Dios su Hacedor,
y a inclinar su oído a la voz de la serpiente, y darle crédito a sus mentiras,
las cuales engendraron un pensamiento vano.
De este pensamiento vano brotó una falsa esperanza de que, al comer del fruto prohibido,
ellos mejorarían sus condiciones y serían como Dios
según lo que la serpiente le dijo a la mujer,
el vaso más débil.
A través de esta falsa esperanza (basada en los pensamientos e
imaginaciones de los hombres) entró la primera transgresión,
y cuando se entró en la tentación, y se cometió el pecado,
entonces los pensamientos e imaginaciones comenzaron a multiplicarse
y a llenar el corazón terrenal y desobediente del hombre.
Ahora el hombre,
habiendo dado su espalda a los cielos y despreciado la voz
y mandamiento de Dios (quien era su maestro y legislador),
le dio su oído al maligno, y entregó su mente y corazón en obediencia a él,
incluso pensando que todo era para lo mejor.

Así, el pobre hombre, siendo engañado con vanos pensamientos y falsas esperanzas,
perdió su habitación y morada en el paraíso,
a pesar de que buscó mantenerla incluso después de haber transgredido.
Porque muy pronto fue convencido de que había hecho mal al comer del fruto prohibido,
y el temor se apoderó de su corazón;
pero cuando escuchó la voz de Dios en el aire del día,
buscó maneras de cubrirse y esconderse de la vista de Dios.
No obstante, aquí sus pensamientos fueron vanos y sus esfuerzos no lograron nada.
La mujer, el hombre y la serpiente, los tres, recibieron los frutos de sus propias obras.
Solo se experimentaba la vida, la bondad y la bendición antes de esto,
pero ahora la muerte,
la maldad y la maldición (el fruto y efecto de la desobediencia)
se volvieron los compañeros diarios de la humanidad,
quienes encontraron y todavía encuentran por experiencia que el siguiente dicho es verdadero:
"`Cuando el pecado es consumado da a luz la muerte.`"^
footnote:[Santiago 1:15]
Todo esto, como he dicho, primero entró al darle lugar a un pensamiento y deseo vano,
con la esperanza de ganar y mejorar su estado.

Por lo tanto, el hombre perdió su lugar en el huerto que Dios plantó,
al desatender la labor que Dios le mandó hacer, que era "`labrarlo y guardarlo.`"^
footnote:[Génesis 2:15]
Porque ciertamente el jardín necesitaba ser labrado
y guardado antes de que se comiera el fruto prohibido,
se perdiera la inocencia y se cometiera el pecado.

Y esto se levanta en mi mente, para testificar a todos los sabios de corazón:
que después de que hayan llegado a encontrar eso que estaba perdido,
a experimentar una restauración, regeneración y regreso a la inocencia del Edén,
todavía tendrán trabajo que hacer allí--porque "`labrar`"
y "`guardar`" son dos palabras muy significativas.
Esta era la ocupación del hombre en el principio, en el estado de inocencia.
Si él no hubiera abandonado este trabajo, ni menospreciado la luz, poder,
sabiduría y gloria de Dios que lo llenaban,
nunca habría caído. Cuando la tentación engendró un pensamiento,
si él hubiera velado en la luz y sabiduría de Dios,
habría visto y descubierto la tendencia de este,
y habría evitado que se convirtiera en un deseo y luego en una
acción. Pero al darle lugar primero a un pensamiento egoísta,
este rápidamente brotó y se volvió un hambre o deseo,
y entonces en una acción. Esta es la fuente y progreso del pecado en este día también,
lo cual la humanidad, en el estado de inocencia,
tiene poder y sabiduría de Dios para evitar, si permanece en dicho estado,
y si se mantiene en su atalaya--la luz y fortaleza de Dios--que
está tan cerca del hombre como lo puede estar la tentación,
y que es suficiente para preservarlo.
Pero donde sea que esta labor se descuide, los hombres (sí,
incluso los hombres santos) caerán, y pecarán a la manera de la transgresión de Adán,
y serán engañados como la serpiente engañó a Eva.
Ellos serán sacados de la inocencia y de un estado sin pecado
incluso después de haberlo alcanzado.

Por lo tanto, que nadie se ensoberbezca,
sino más bien que tema y tome al Segundo Adán como ejemplo, quién cuando fue tentado,
no deseó las cosas que fueron presentadas como lo hizo el primer Adán (aunque
tenían una apariencia muy engañosa y estaban acompañadas con muy grandes promesas).
De hecho, está escrito que Cristo durante la tentación no comió nada,
no dejó entrar nada, no les dio lugar a pensamientos egoístas ni a sutilezas del enemigo,
y, por lo tanto, cuando la tentación hubo acabado,
ángeles le servían. Que esto sea un ejemplo para todos los hijos de la luz,
porque a medida que ellos hagan lo mismo, la poderosa salvación de Dios los rodeará,
y en verdad, "`ni lo alto, ni lo profundo, ni ángeles, ni principados, ni potestades,
ni lo presente, ni lo por venir, los podrá separar del amor de Dios,
que es en Cristo Jesús Señor nuestro.`"^
footnote:[Romanos 8:38-39]
Esto es algo así como una nota al margen.

Ahora bien, los malos pensamientos e imaginaciones se multiplican por naturaleza,
y principalmente echan raíces y se incrementan en la generalidad de la humanidad,
la cual, debido a las malas obras, está apartada de la vida de Dios.
Estos son como un sarmiento de vid extraña que ha brotado de la semilla del maligno,
que mora y obra en esa tierra que el Señor ha maldecido,
quienes no han experimentado la "`semilla de la mujer`"^
footnote:[Génesis 3:15]
hiriendo la cabeza de la serpiente,
o redimiéndolos y preservándolos de seguir y obedecer sus propios pensamientos e imaginaciones,
que son malos todos los días. Y, en realidad, en ese estado, no puede ser de otra manera,
ya sea que sus pensamientos los lleven al pecado o la justicia propia,
ambas cosas son una abominación para el Señor, y, además,
son destructivas para el bienestar temporal y eterno de la humanidad.

Porque desde el principio,
toda la iniquidad que ha sido manifestada y cometida en
el mundo ha comenzado o aparecido primero en un pensamiento,
y este pensamiento, al ser recibido y abrazado por la mente,
la voluntad y el entendimiento, va creciendo hasta convertirse en palabras y acciones.
Lo puro no puede proceder de lo impuro.
El corazón de la humanidad en la caída está universalmente corrompido y pervertido,
y por esta razón (como ha sido dicho),
"`los pensamientos e imaginaciones del corazón del
hombre son solamente malos todos los días.`"^
footnote:[Génesis 6:5]
Por lo tanto, antes de que esto pueda cambiar,
hay una necesidad absoluta de que cada hombre y mujer
en particular sienta y experimente en sí mismos,
su corazón lavado, purgado, purificado y creado nuevamente.
La tierra tiene que ser hecha buena antes de que
la semilla o planta celestial pueda crecer,
incrementarse y florecer en ella, y antes de que puedan surgir,
brotar y permanecer en ella buenos pensamientos y meditaciones celestiales.

Ahora bien, cuando llegues a experimentar y disfrutar este estado,
entonces tu deber será permanecer con Él,
morar y caminar con Aquel que ha hecho estas maravillas en ti, y por ti.
Y en Su sabiduría y poder,
deberás labrar y guardar el huerto (el corazón) con toda diligencia,
para que aquello que lo contamina no pueda entrar o meterse otra vez,
como lo hizo en el principio.
De hecho,
lo que el Espíritu de Dios le indicó al hombre que hiciera
en el principio (cuando era una planta noble en el Edén,
una semilla completamente recta), a saber, labrar y guardar el huerto,
también lo indica en esta era, diciendo: "`¡Velad y orad,
para que no entréis en tentación!`"^
footnote:[Mateo 26:41; Marcos 14:38]
"`Estén atentos, no sea que como la serpiente engañó a Eva por su astucia,
así sean corrompidas vuestras mentes, de la simplicidad que es en Cristo.`"^
footnote:[2 Corintios 11:3 Reina Valera 1602 Purificada]

=== Un Medio Designado para Limpiar el Corazón

Ahora esto testifico a partir de un conocimiento certero:
que aunque el corazón de la humanidad está tan corrompido que nada bueno sale de él,
ni nada celestial o de Dios puede brotar y vivir en él,
ni siquiera por un momento (siendo tan feo y oscuro,
como un sucio pedazo de tierra natural al que nunca le pega el sol ni le cae la lluvia),
aun así,
Dios ha designado un medio por el cual el hombre en este estado miserable
puede llegar a sentir y experimentar que su corazón impuro es limpiado,
purificado y santificado, así como lo hicieron los cristianos en los primeros tiempos:
"`Esto erais algunos; mas ya habéis sido lavados, limpiados y santificados,`"^
footnote:[1 Corintios 6:11]
etc.
El campo puede ser arado,
y la mera semilla y el desierto pueden convertirse en un campo fructífero,
y los torrentes pueden abrirse en la soledad; sí,
el desierto puede alegrarse y florecer como la rosa.
De hecho, lo torcido puede enderezarse, y lo áspero allanarse.
Montes grandes, pesados y oscuros pueden ser derribados y removidos, sí,
derretidos ante la presencia de Dios, y los valles bajos pueden ser alzados.
En verdad, el desierto puede volverse como el Edén,
y la soledad como el jardín del Señor.

En esta era,
el Señor ha hecho todas estas grandes obras y maravillas en y por un remanente,
quienes han llegado al cumplimiento de estas profecías, y son testigos vivos de ellas.
Y estos, en Su Espíritu Santo y Poder,
proclaman que el amor y misericordia de Dios para con el hombre caído es universal,
y que Su mano está extendida para ayudarlo a salir de la trampa,
del pozo y de la fosa profunda y oscura en la que ha caído,
y de la cual no puede (ni con toda su fuerza, sabiduría e invención) salir por sí mismo.
En verdad, el Señor se ha manifestado para darle libertad,
para que pueda correr por el camino de Sus mandamientos con deleite,
y para que pueda llegar a ser recto otra vez (incluso como Dios hizo al hombre al principio),
y dejar a un lado todos sus pensamientos e invenciones
con los cuales se ha corrompido a sí mismo.
Indudablemente el Señor desea llevarlo a tal estado y condición en que pueda
ser capaz de hacer todas las cosas que son buenas--de pensar buenos pensamientos,
de hablar buenas palabras y de hacer buenas obras,
y de esta manera evitar y abstenerse de lo contrario.
Experimentar y ser capaz de hacer esto es la única cosa necesaria, y sin ello,
todos los hombres son miserables--sin importar cual sea su conocimiento, sabiduría,
opinión, invención y profesión de religión.

Por lo tanto, mi mente está en buena voluntad para con la humanidad,
habiendo recibido conocimiento y entendimiento del medio que Dios
ha designado para su bienestar y salvación. Y estando en una medida
familiarizado con los dos grandes misterios--el de la piedad y
el de la iniquidad--y con la manera y operación de cada uno,
es mi deseo impartir y explicar algo de esto en unas pocas palabras,
con el fin de instruir e informar a aquellos a quienes pudiera llegar mi testimonio,
respecto a cómo pueden alcanzar estas cosas,
y cómo pueden deshacerse de esos molestos compañeros, a saber,
malos pensamientos e imaginaciones que se levantan en el corazón cuando está corrompido,
y también respecto a cómo el corazón puede ser purificado
y convertido en una morada santa para Dios,
como lo era antes de que entrara el pecado, antes de que se perdiera la inocencia,
antes de que la serpiente engañara al vaso más débil, cuando todo era bueno, sí,
muy bueno.

Quienquiera que seas tú,
que tienes la intención o el deseo de encontrar aquello que está perdido, observa,
cree y recibe lo que escribo como la verdad--no una
verdad recibida o aprendida por tradición,
sino por la obra y operación viva y poderosa del
Espíritu de la verdad en mi propia mente.
Y en verdad, lo que he dicho, o diré, es de acuerdo con las Sagradas Escrituras,
y es testificado por ellas, porque no puedo escribir algo que sea contrario a ellas,
pues estoy en unidad con ellas,
y con los espíritus de los hombres justos que las escribieron.
Por lo tanto, el camino que yo declaro es el siguiente: Primero, tú debes saber,
oh hombre, quienquiera que seas tú,
y cualesquiera que sean tus pensamientos e imaginaciones,
independientemente de cuán lejos hayas corrido a la corrupción,
oscuridad y degeneración del estado de inocencia, pureza y santidad--tú debes saber que,
a pesar de todo esto,
hay una medida de luz divina que te acompaña. Aunque seas tinieblas,
ella resplandece en ti, con el fin de mostrarte tu camino fuera de esas tinieblas.
Aunque te hayas degenerado y corrido lejos de Dios a la tierra, aun así,
esta luz y Espíritu puro de Dios te sigue, y te llama de regreso,
y tú puedes (incluso en este estado) escucharlo como una voz a tus espaldas que dice:
"`Regresa, regresa, este es el camino, andad por él.`"^
footnote:[Isaías 30:21]

En verdad, esta es la bondad y amor de Dios para ti en Su Hijo,
quien es la luz del mundo, que "`alumbra a todo hombre que viene a este mundo.`"^
footnote:[Juan 1:9 Reina Valera de Gómez]
Si escuchas y obedeces esta voz de la luz del Hijo de Dios,
aunque estés muerto en pecado y enterrado como en una tumba,
te levantarás y saldrás y vivirás delante de Él;
los cerrojos y las puertas del infierno no podrán retenerte.
Pero si tomas por poco y menosprecias la luz de Dios que te visita,
y cierras tu oído contra Su voz, ella será como mil testigos en tu contra,
durante todo el tiempo en que te rebeles contra ella y te
encuentres siguiendo tus propios pensamientos e imaginaciones,
y haciendo lo malo.

Porque esta luz de la que hablo es el "`ojo del Señor que recorre toda la tierra,`"^
footnote:[2 Crónicas 16:9 Reina Valera 1602 Purificada]
mirando a los malos y a los buenos,
y discerniendo los pensamientos y las intenciones del corazón.
Ella es la palabra que está cerca en la boca y en el corazón,
que es viva y eficaz, y más cortante que toda espada de dos filos.
Esta es la linterna del Señor que escudriña a Jerusalén,
y que alumbra hasta lo último de la tierra y todos los rincones del mundo,
y de esta luz nadie puede esconderse en la sombra de muerte,
ni cubrirse o protegerse bajo las peñas y montañas. Porque está escrito: "`He aquí,
el que forma los montes, y crea el viento, y declara al hombre su pensamiento;
el que hace a las tinieblas mañana, y pasa sobre las alturas de la tierra; el Señor,
Dios de los ejércitos es su nombre.`"^
footnote:[Amos 4:13 Reina Valera de Gómez]
Este es el Espíritu de la verdad que convence al mundo de pecado,
y que pone los pecados de los hombres en orden delante de ellos,
y que los reprueba y golpea en secreto por el mal,
y que lleva a juicio "`los tesoros escondidos de Esaú.`"^
footnote:[Abdías 1:6]
De este ojo o luz del Señor, no puedes esconderte,
no más de lo que pudieron Adán o Caín. Y aunque aborrezcas
la luz que te muestra tus pensamientos,
y ames la oscuridad de tal modo que habites en ella, aun así,
la luz u ojo de Dios te perseguirá y te encontrará. Ni el infierno,
ni la oscuridad ni los fines de la tierra podrán
salvarte de la debida condenación de Dios.
Porque cuando tu odias el resplandor de Su luz,
y tapas tu oído contra Su voz y enseñanza, y amas la oscuridad y habitas en ella,
tu escoges el camino de la muerte,
y abandonas el medio de salvación que Dios ha ordenado.
"`Porque esta es la condenación: que la luz vino al mundo,
y los hombres amaron más las tinieblas que la luz, porque sus obras eran malas.`"^
footnote:[Juan 3:19]

=== Ama y Obedece la Luz

Ahora bien, en el primer paso hacia la restauración y felicidad eterna,
se requiere que vuelvas tu mente de las tinieblas en las que moras, a la luz,
ojo o Espíritu de Dios, y que resistas el poder de Satanás que opera en las tinieblas,
y abraces el poder de Dios.
Cuando apenas empieces a hacer esto,
sentirás que las escamas comienzan a caer gradualmente de tus ojos,
que el velo es quitado de tu corazón,
que los grillos y cadenas de las tinieblas son sueltos,
y que las puertas de tu prisión son abiertas.
Entonces, cuando tu candelero esté encendido, y tu ojo abierto,
discernirás tu camino de salida,
y verás al ángel del Señor yendo delante de ti y guiándote en dicho camino.
Y también percibirás lo que hay en tu casa,
y entenderás claramente lo que se ha alojado en el cuarto oscuro
de tu corazón. Y cuando llegues a ver estas cosas tal como son,^
footnote:[W. S.--"`La causa del error es un malentendido respecto a la
naturaleza de las cosas que se presentan delante de la humanidad.
Así es como algunos llaman a la luz tinieblas y a las tinieblas luz.`"]
recibirás sabiduría para darles nombres de acuerdo con su naturaleza,
y para hacer justos juicios respecto a ellas.
Y a medida que ames esta luz,
serás capacitado por ella para separar un pensamiento de otro,
y comenzarás a actuar de acuerdo con tu consciencia, y a odiar cada pensamiento vano.
Y cuando no puedas deshacerte de ellos con facilidad,
ni removerlos de su antiguo lugar de alojamiento,
tu respirarás y clamarás al Señor en el Espíritu, como lo hizo uno en la antigüedad,
quien estaba cargado y oprimido por la presencia de ellos, diciendo: "`Examíname,
oh Dios, y conoce mi corazón; pruébame y conoce mis pensamientos;
y ve si hay en mí camino de perversidad, y guíame en el camino eterno.`"^
footnote:[Salmos 139:23-24]
Este es el clamor que el Señor escucha, y que responderá en su debido y necesario tiempo.
Y el clamor de Jeremías a Jerusalén fue: "`Lava tu corazón de maldad, oh Jerusalén,
para que seas salva.
¿Hasta cuándo permitirás en medio de ti los pensamientos de iniquidad?`"^
footnote:[Jeremías 4:14]
Ahora bien, la única manera de desalojarlos y deshacerse de su compañía,
es no mostrarles aprobación, ni hacer provisión para ellos, ni darles hospedaje;
al contrario, por la luz de Dios que los descubre como tus enemigos,
debes juzgarlos y mantener tu mente puesta en la luz y poder de Dios,
al cual ella se ha vuelto.
Y aunque ellos se levanten, o puedan levantarse, y perseguirte y rodearte como abejas,
aun así,
al mantener tu ojo puesto en la luz y poder de Dios (que
está tan cerca de ti como lo están tus pensamientos,
mostrándote cada uno de ellos),
en su debido tiempo los verás esparcidos como la paja delante de un fuerte viento,
y destruidos como la hojarasca delante del fuego consumidor.

Ahora bien, a medida que llegues a ser un creyente en la luz,
y a confiar en el poder de Dios (al cual tu mente está vuelta)
te convertirás en un hijo de la luz en verdad,
y pronto serás capaz de decir: "`las tinieblas han pasado,
y la luz verdadera ya alumbra,`"^
footnote:[1 Juan 2:8 Reina Valera de Gómez]
por la cual podrás ver y juzgar cada pensamiento
y motivación que se despierte y levante en tu mente,
ya sea malo o inocente, dañino o inofensivo,
y tener sabiduría para ordenarlos como corresponde.
Esta es esa sabiduría primitiva que la humanidad tuvo en el principio,
pero el hombre no permaneció en ella,
porque miró la tentación y la belleza de eso que fue presentado al ojo de su mente.
La mujer fue engañada en sus pensamientos.
De hecho,
ella fue engañada en su juicio y entendimiento antes de que obedeciera al tentador,
porque el árbol le pareció "`bueno para comer, y agradable a los ojos,
y codiciable para alcanzar la sabiduría`"^
footnote:[Génesis 3:6]
antes de que comiera o le diera de comer a su marido.
Pablo dice que la mujer siendo engañada, incurrió en transgresión,
por la cual fue sujetada a vanidad, no por su propia voluntad, sino en esperanza,
porque ella tenía la esperanza de que las palabras de la serpiente fuesen verdad,
y de que se volvería más sabia y feliz al tomar el consejo de la serpiente;
pero en lugar de eso, cayó en la más profunda miseria.

Este mismo peligro acompaña a los hijos de la luz, a los hijos e hijas de Dios,
porque Adán fue un hijo de Dios antes de la transgresión.
Y solo aquellos que han sido restaurados,
y son hijos de la luz y del día, pueden caer como Adán y Eva,
y pecar a la manera de la transgresión de Adán, perdiendo la inocencia, pureza,
santidad y rectitud como ellos, siendo echados del huerto de Dios como ellos.
No se puede decir que aquellos que nunca han estado en ese huerto,
ni jamás han morado en el estado de restauración, inocencia, pureza y santidad,
puedan caer de él o perderlo.
En verdad, los hijos de las tinieblas y los hijos del diablo,
quienes se han descarriado y han morado en oscuridad y en la región de
sombra de muerte (como los hombres y mujeres hacen ahora en el mundo),
nunca han conocido lo que es la vida de pureza y santidad,
ni lo que es la simplicidad del evangelio de Cristo,
y por lo tanto no pueden ser seducidos (como la serpiente
sedujo a Eva) de lo que nunca han experimentado o tenido.
Estos son engañados por la serpiente de otra manera--no
con respecto a lo que alguna vez tuvieron y disfrutaron,
sino con respecto a lo que podrían tener y disfrutar.
Y esto efectúa la serpiente al mantener los ojos y las mentes
de las personas mirando y buscando lo exterior,
y al persuadirlos a seguir cualquier cosa, y a caminar en cualquier camino,
en lugar de volver el ojo de sus mentes internamente a la Luz, palabra,
poder y Espíritu de Dios.
Porque en verdad esto es lo que resplandece,
habla y obra en el hombre con el fin de conducirlo, enseñarlo,
guiarlo y dirigirlo al camino de vida y salvación,
y llevarlo a la libertad gloriosa de los hijos de Dios,
a un perfecto traslado de las tinieblas a la luz, y del reino y poder de Satanás,
al reino y poder del Hijo de Dios, y a experimentar a Cristo hecho para él sabiduría,
santificación y redención.

Este es el bendito fin por el cual Dios envió a Su Hijo al mundo como una luz--a saber,
para alumbrar a gentiles y judíos, a profesantes y profanos, a fin de que ellos,
por medio de Él, pudieran creer y recibir vida eterna,
y entrar en ese reposo bendito que Dios ha preparado,
al cual entraron los primeros cristianos que creyeron.
Estos no hablaban sus propias palabras, ni pensaban sus propios pensamientos,
ni hacían sus propias obras, sino que Su Padre celestial hablaba en ellos,
y sus pensamientos eran pensamientos de Dios,
y Él obraba todas sus obras en ellos y por ellos.
Este es un estado bendito en verdad,
y ninguno ha entrado al reposo que Dios ha preparado,
salvo aquellos que han llegado a sentir y experimentar estas cosas ahora en esta era,
como los primeros cristianos lo hicieron en eras pasadas.
Porque mientras alguno se encuentre pensando sus propios pensamientos,
hablando sus propias palabras y haciendo sus propias obras
(aunque sea bajo una profesión de Cristo y del Cristianismo),
no podrá entrar al reposo que Dios ha preparado.
Puede que estos creen para sí mismos falsos reposos,
o encender fuego y andar a la luz de sus propias teas,
pero al final serán sepultados en dolor.^
footnote:[Isaías 50:11]

El verdadero reposo y paz se obtienen a través de
una verdadera negación del yo--es decir,
al negar tanto el pecado como la justicia propia, y también los pensamientos, obras,
ideas, inventos, sabiduría y entendimiento de la carne.
Todas estas cosas deben ser negadas, aniquiladas, llevadas a la nada y frustradas.
El alimentarse de estas cosas causó y todavía causa la maldición,
junto con toda la labor, angustia,
dolor y tormento que ha acompañado a la humanidad desde la caída. Todas estas cosas
deberán morir antes de que podamos experimentar ser sentados en el reino de Dios,
o antes de que alguien pueda reposar de sus propias obras, como Dios de las suyas.^
footnote:[W. S. --"`El alimentarse del fruto prohibido, que era bueno en sí mismo,
aunque no para comer,
causó (y todavía causa en este día) todas las miserias que acompañan a la humanidad.`"]

=== Mantenerse Velando en la Luz

Ahora bien, tú que eres un hijo de luz,
entiende esta única cosa para tu consuelo y ánimo en tu guerra contra los malos pensamientos:
que a pesar de que se levanten en ti una multitud de pensamientos,
y te asedien ejércitos de ellos, los cuales son pecaminosos en sí mismos, aun así,
si tú no te unes a ellos en tu mente, voluntad y entendimiento,
ellos no serán tus pensamientos, ni la maldad de ellos te será imputada.
Si tú amas la luz, y mantienes tu mente unida al Espíritu de Dios,
o a la aparición de Cristo en ti que te muestra todas
las tentaciones en su primera aparición,
cuando apenas son un pensamiento,
entonces tú estás ayudando al Señor en contra del hombre fuerte.
Porque al unirte a Él, te vuelves uno con Él en tu mente y espíritu,
aunque en tus miembros haya una ley o poder que luche contra ti.
Y a medida que permanezcas con el Señor, esperando en Él, incluso,
así como "`los ojos de la sierva esperan la mano de su señora,`"^
footnote:[Salmo 123:2]
Él te salvará y te librará, y someterá a todos tus enemigos,
incluso aquellos de tu propia casa, que son los más grandes enemigos.

Aunque las tentaciones puedan asediarte (que sin duda lo harán), aun así,
no es pecado ser tentado, incluso con tentaciones internas.
Y tú no debes considerarte a ti mismo (ni tampoco serás considerado) un pecador,
solo porque el pecado y los vanos pensamientos se presenten a sí mismos en ti,
en tu estado de guerra.
En lugar de esto, puedes decir como Pablo dijo: "`ya no soy yo,
sino el pecado que mora en mí,`"^
footnote:[Romanos 7:20]
y que "`en mí, esto es, en mi carne, no mora el bien.`"^
footnote:[Romanos 7:18]
De hecho,
ahora estás en el camino para experimentar cómo esta carne se seca como la hierba,
y cómo la gloria de ella se vuelve como la flor caduca del campo,
y cómo el pecado que mora en ella es destruido,
y cómo la criatura hecha por Dios es preservada,
y el vaso de barro que contiene el tesoro celestial es santificado,
salvado y librado del yugo de la esclavitud bajo el cual gime toda la creación de Dios.
Y ciertamente llegarás a esto, en la medida que mantengas tu ojo puesto en tu Salvador,
tu luz, tu camino, tu Capitán, a quien verás yendo delante de ti venciendo y para vencer,
hasta que todos Sus enemigos (que son tus enemigos) sean sometidos,
dominados y destruidos, y tú seas hecho como un rey y sacerdote para Dios.^
footnote:[W. S. --"`Antes de que tropieces en este dicho,
considera que Juan era el mayor de los profetas nacidos de una mujer, sin embargo,
el más pequeño en el reino era mayor que él.`"]
Y entonces serás llevado a decir (como pudieron decir los primeros cristianos) que,
"`Como Él es, así somos nosotros en este mundo.`"^
footnote:[1 Juan 4:17]
Somos puros como Él es puro, santos como Él es santo, justos como Él es justo,
sencillos e inocentes como Él lo era,
entregados a la voluntad de Dios en todas las cosas.
"`No Mi voluntad,`" dijo el segundo Adán, "`sino la Tuya,`"^
footnote:[Lucas 22:42]
aunque Su voluntad era tan inocente y pura como la del primer Adán antes de la caída,
e incluso la superaba.
Cuando tú llegues a esto, entenderás y recibirás lo que digo;
hasta entonces será como un misterio y una dura palabra para ti.

Y mientras estés en el camino, ten cuidado de esa manera de pensar, querer y correr,
que no obtiene la recompensa.
"`Quédate quieto, y ve la salvación de Dios.`"^
footnote:[Éxodo 14:13 Reina Valera de Gómez]
Sobre todas las cosas, pon tu mente en el brazo de Su poder en ti,
que es capaz de suprimir tus pensamientos, crucificar tu voluntad,
detener tu apresuramiento y darte la fuerza perfecta
para resistir al diablo y hacerlo huir,
y para prepararte para toda buena palabra y obra.
De hecho, Él te dará dominio sobre tu propio espíritu,
cuya condición natural es ser ligero en los pensamientos,
rápido en los deseos e insatisfechos en el cumplimiento de ellos.

Ahora bien, está escrito que^
footnote:[W. S.--"`Considera la similitud, y en la luz trata de aplicártelo a ti mismo,
y encontrarás la verdad de ello.`"]
"`el que se enseñorea de su espíritu, es más fuerte que el que toma una ciudad.`"^
footnote:[Proverbios 16:32]
Y, "`como ciudad invadida y sin murallas es el hombre que no domina su espíritu.`"^
footnote:[Proverbios 25:28 LBLA]
Y "`Cuando el justo domina, la tierra se alegra; mas cuando domina el impío,
la tierra gime.`"^
footnote:[Proverbios 29:2]
Estas cosas son infaliblemente verdaderas.
Mientras el usurpador mantiene el trono,
el Príncipe de paz y su gobierno pacífico no son experimentados.
Tribulación y angustia vendrán sobre toda alma de hombre que haga lo malo,
que piense e imagine el mal, y que presente sus miembros como instrumentos de iniquidad,
independientemente de cual sea su opinión o profesión religiosa.
En verdad, "`El que hace pecado, es del diablo.`"^
footnote:[1 Juan 3:8 Reina Valera 1602 Purificada]
Y a menos de que ellos se aparten del mal,
y experimenten a Cristo poniéndole fin o terminándolo,
y estableciendo la justicia en su lugar, tendrán la paga y recompensa de este,
y poseerán el fruto de sus propios pensamientos y obras.

Ahora bien, es un estado celestial vivir bajo el gobierno de Cristo,
sentirlo y experimentarlo extendiendo el centro en el corazón,
y estando establecido en el trono de este.
Pero nadie llega a disfrutar esto,
hasta primero sentirlo a Él actuando como un refinador con fuego,
como un lavador con jabón, como un espíritu de juicio y de fuego,
y como el hombre más fuerte que echa fuera al hombre fuerte, y despoja todos sus bienes,
que barre y limpia la casa, y la acondiciona nuevamente con bienes, pensamientos,
deseos y meditaciones celestiales,
y todas las otras cosas que corresponden a la casa del Señor. Santidad al Señor
era lo que estaba escrito y grabado en la diadema y lámina de oro,
y todo el mobiliario del templo externo era santificado, de lo cual esto es el antitipo,
o sustancia, como lo sabe bien aquel que lo experimenta.

Y, ahora bien, es el deber del cristiano velar en la luz contra los malos pensamientos,
y usar el hacha de Dios (que está puesta a la raíz de ellos)
para evitar que broten de nuevo y logren su fin.
Asimismo,
es el deber de todos abrazar y unirse a los buenos pensamientos
y deseos cuando estos se levantan en lugar de los malos,
y mantener el ojo puesto en el Señor,
que es quien los engendra o levanta en el corazón.
Porque estos pensamientos son del Señor,
puesto que son pensamientos puros, pensamientos de paz y justicia,
pensamientos de santidad y gozo en el hombre interior,
los cuales no puedes pensar por ti mismo.
Estos son pensamientos reconfortantes, pensamientos que justifican y excusan,
pensamientos que permanecerán aprobados en la luz,
y el fin y tendencia de ellos es el bien, incluso como un fruto placentero al alma.
Los que tienen estos pensamientos pueden decir, como lo hizo David una vez:
"`¡Cuán preciosos me son, oh Dios, tus pensamientos! ¡Cuán grande es la suma de ellos!
Si los enumero, se multiplican más que la arena; despierto, y aún estoy contigo.`"^
footnote:[Salmos 139:17-19]
A medida que ames la luz, y te deleites en la ley de Dios, y medites en ella,^
footnote:[W. S. --"`Los buenos pensamientos son engendrados
por Dios mismo y son muy reconfortantes para el cristiano.
Estos son el fruto y efecto de guardar y obedecer
la ley de Dios en el corazón. Romanos 2:14-15`"]
estos buenos pensamientos se multiplicarán e incrementarán en ti,
para tu gran contentamiento y satisfacción. Pero los pensamientos del impío son pecado,
y el pecado produce tribulación, angustia y tormento.
Los hombres son acusados o excusados en sus pensamientos (Romanos
2:15). Se dice que Belzazar estaba tan turbado con sus pensamientos,
que su "`rostro palideció, y se debilitaron sus lomos,
y sus rodillas daban la una contra la otra.`"^
footnote:[Daniel 5:6]
De hecho, muchos son los pensamientos espantosos y tormentosos que acompañan al impío,
"`cuyos pies corren al mal, y se apresuran para derramar la sangre inocente;
sus pensamientos, pensamientos de iniquidad;
destrucción y quebrantamiento hay en sus caminos.
No conocieron camino de paz, ni hay justicia en sus caminos.`"^
footnote:[Isaías 59:7-8]

Ahora bien, los pensamientos de los justos son rectitud,
y aquellos que encomienden a Jehová sus obras, sus pensamientos serán afirmados.
Y este es un estado de bendición en verdad--tener buenos
pensamientos afirmados en el corazón y en la mente.
Estos pueden salir y entrar en paz, acostarse y levantarse en paz,
vivir y caminar en paz, y alabar al Dios de paz,
quien es bendito por los siglos de los siglos.
Y esta es la paz, la paz interna,
que el mundo no puede dar con todos sus tesoros y placeres, ni quitar con su desprecio.
Esta paz es la porción de todos los que obtienen victoria sobre sus propios pensamientos,
imaginaciones, concupiscencias, deseos y afectos,
y quienes además se mantienen en la sabiduría y poder de Dios.
Y cuando los buenos pensamientos sean afirmados en ellos,
y ellos sean de ese modo hechos partícipes de la naturaleza divina,
entonces naturalmente tendrán buenos pensamientos, pensamientos de amor,
paz y obediencia,
así como tenían pensamientos contrarios mientras estaban en el estado de degeneración.

Sin embargo, en este estado de inocencia y rectitud,
tú aún debes ser diligente en la sabiduría de Dios para labrar y guardar el huerto.
Está atento, no sea que, habiendo encontrado miel,
comas más de lo que es suficiente para alimentar al nacimiento correcto,
y te alimentes a ti mismo sin temor, y comas y bebas, y te levantes a jugar,
y te vuelvas más ocioso y disoluto por tener abundancia, y entonces olvides al Señor. Sí,
está atento, no sea que Sus beneficios se deslicen fuera de tu mente,
y menosprecies Sus mandamientos,
y permitas que el orgullo y la exaltación en tú espíritu egoísta crezcan otra vez,
como lo hicieron el primero Adán y muchos otros (mencionados en las Sagradas Escrituras,
que son dadas para nuestra enseñanza y amonestación,
a quienes han alcanzado los fines de los siglos).
Así que, el que piensa estar firme, mire que no caiga.
