[short="La Adoración Cristiana"]
== Con Respecto a la Adoración Cristiana; En qué Consiste y Cómo se Realiza

Hay una gran disputa entre las diversas sectas y
denominaciones de la Cristiandad acerca de la adoración,
y muchas son las maneras y ceremonias que son encomendadas entre ellas.
Cada secta considera que su manera es la correcta, y todas están llenas de disputa,
contienda y quejas una contra otra, envidiándose y aborreciéndose una a otra, peleándose,
matándose y destruyéndose la una a la otra.
Todas las sectas o denominaciones que actúan de esta manera
son (independientemente de lo que digan) creaciones de la imaginación propia del hombre.
Son formas e imágenes hechas por el hombre,
que en su mayoría son tomadas del ejemplo de los Judíos, Gentiles y Cristianos apóstatas,
a las cuales los hombres no han sido llevados ni guiados por el
Espíritu infalible de Dios (como sus frutos lo manifiestan claramente,
para el gran escándalo de la religión cristiana).

Ahora bien, la verdadera adoración cristiana es en el Espíritu y en la verdad,
no en la letra, ni en la simple forma.
Esta era la adoración antes de que existieran las letras,
y las leyes y prescripciones externas, antes de todas las invenciones y errores,
y del espíritu de estas cosas.
De hecho,
esta era la adoración en el Paraíso. Cuando la humanidad menospreció esta adoración,
cayó en el mal, en el invento y en el error;
y esta fue la causa por la que se introdujo la ley externa,
y todas las otras dispensaciones de Dios para recuperar al hombre perdido.
Y antes de que el hombre pueda experimentar un regreso
de su estado perdido a su estado original,
debe volver a la misma adoración en Espíritu y en verdad, a saber,
la verdad en lo íntimo, porque esa es la que Dios ama.
Sí, el hombre debe venir a la palabra en la boca,
a la ley en el corazón y al temor en el interior.
Y debe salir de todo tipo de temor de Dios que es
enseñado por los mandamientos de los hombres,
de todas las tradiciones de hombres de mente corrupta,
y de todas las creaciones e invenciones de los hombres.

Esta adoración en el Espíritu y en la verdad es el
bendito estado al cual llega el verdadero cristiano,
y es el fin, suma y sustancia de todos los escritos sagrados, formas y tradiciones,
ministraciones y dispensaciones santas antes de la ley,
bajo la ley y durante los profetas.
La adoración en el desierto, en Jerusalén y toda adoración en templos,
consistían en diversos ejercicios corporales, en obras y servicios externos,
en una variedad de ofrendas, en guardar tiempos, días, meses y años, en comidas, bebidas,
y lavamientos y purificaciones externos, en lunas nuevas, ayunos, fiestas,
reuniones solemnes y en asambleas generales una vez al año
en Jerusalén--todas estas cosas solo eran sombras y tipos,
y la adoración en Espíritu y verdad es el antitipo y sustancia al que todas ellas apuntan.
De hecho, la sustancia de todo es adorar en el Espíritu, en la verdad,
llegar al Monte Sion, a la ciudad del Dios vivo, a Jerusalén la celestial,
a la congregación de los primogénitos que están inscritos en los cielos,
a Dios el Juez de todos y a los espíritus de los justos hechos perfectos.
Es conocer la ciudad celestial la cual desciende del cielo, de Dios, es decir,
Jerusalén la madre de todos los ciudadanos vivos de ella,
cuya ley y pacto es espiritual y está escrito en sus corazones, y cuyo amor,
temor y obediencia a Dios está grabado en su interior.
De aquí surge la verdadera adoración en el Espíritu, y en la verdad.

Esta es la adoración a la cual llegaron los primeros Cristianos,
y ellos fueron ejercitados en ella.
De hecho, ellos oraban en el Espíritu,
no solo en un tiempo determinado o lugar designado, según las siguientes exhortaciones:
"`Ora en todo tiempo,`"^
footnote:[Lucas 21:36 Reina Valera de Gómez]
"`ora siempre,`"^
footnote:[Lucas 18:1]
"`orad sin cesar,`"^
footnote:[1 Tesalonicenses 5:17]
"`Quiero, pues, que los hombres oren en todo lugar, levantando manos santas,
sin ira ni contienda,`"^
footnote:[1 Timoteo 2:8]
etc.
Ellos respiraban al Señor en el Espíritu,
y aunque a veces no decían ni una palabra (cuando estaban en su aposento,
con la puerta cerrada),
el Señor escuchaba y respondía esta oración. Y muchas veces
ellos también eran movidos a orar públicamente con palabras,
pero esto fue mayormente por el bien de los demás como hacía Cristo Jesús.

El verdadero cristiano es también un predicador de justicia, no solo en palabras,
en tiempos determinados y en lugares designados, sino en vida y conducta.
Sí, en esto él es un predicador y un maestro de lo que es bueno,
como un candelero que arde y es puesto en el lugar correcto;
su lámpara está arreglada y su luz brilla.
Él es como una ciudad asentada sobre un monte,
como la sal de la tierra y como la luz del mundo,
para dar sabor y luz a otros mediante un ejemplo santo,
que predica más fuerte que las palabras.

El cántico o júbilo del verdadero cristiano también
se realiza en el Espíritu y en la verdad,
con un buen entendimiento, y no en iniquidad.
No tiene necesidad de arte o invención para poner palabras en un ritmo o rima,
para hacer un sonido agradable y un cántico de júbilo.
Su música no consiste en sonidos externos hechos por el arte y el aire,
sino que su melodía es en el corazón, en el espíritu, en el hombre interior,
en el hombre encubierto del corazón. Este es el antitipo y sustancia
de toda la música externa que se usó en el tiempo de la ley (bajo
el primer pacto) en la adoración y servicio de Dios,
y es tan superior a ella como la sustancia de una cosa supera la sombra.
Y el que tiene este regocijo celestial e interno, y esta agradable melodía en el corazón,
nunca inventará para sí mismo instrumentos musicales como David,
ni se deleitará en el sonido de estos.
La música externa e inventada ha sido establecida
donde esta melodía del corazón se ha perdido,
ya sea entre judíos, gentiles o cristianos apóstatas.
Porque el verdadero cristiano ha llegado a conocer
a Cristo Jesús como el Príncipe de Paz,
como el Pacífico salvador, como la consolación de Israel y el gozo de las generaciones.
En verdad Él es conocido como el dador de la paz que el mundo no puede dar ni quitar,
la cual sobrepasa con creces todos los deleites que los
hijos de los hombres pueden obtener mediante la naturaleza,
el arte y la invención.

Ahora bien, el Espíritu de Dios es universal, y la verdad es universal,
y por lo tanto la verdadera adoración cristiana que consiste
en este Espíritu y en esta verdad también debe ser universal.
Esta adoración no solo ocurre cuando las personas
se reúnen de una manera solemne a esperar en Dios,
sino en cada hora y en cada día,
cuando los verdaderos adoradores se inclinan en el espíritu y adoran en la verdad.
Esta adoración nos hace libres de todo error, de todo mal, de todos los ritos vanos,
tradiciones formales e invenciones humanas con respecto a la adoración de Dios.
Sí, nos hace libres de toda ordenanza carnal, como música, comida, bebida, lavamientos,
fiestas, ayunos, días y tiempos, cosas que todas se destruyen con el uso.
Y aunque estas cosas tenían su importancia cuando fueron instituidas por primera vez,
no deben ser tocadas, ni probadas, no, ni siquiera manejadas por el verdadero cristiano.
Porque ellas solo son pobres rudimentos del mundo, que tuvieron un principio,
y deben tener un final.

Y la raíz u origen de un Cristiano, que es Cristo,
es el fin de la ley y de todos los tipos y sombras que hay en ella.
En verdad, Cristo es el cumplimiento de toda la justicia de la ley,
y de los profetas y de Juan también. Y es Él quien introduce una mejor esperanza,
una mejor ley, un mejor pacto, una mejor adoración--cuya esperanza, ley,
pacto y adoración son internos y espirituales, y no externos y carnales,
formales o tradicionales.
Y todos los que han llegado a esta adoración en Espíritu
y en verdad (que es un principio puro y eterno de luz,
vida y poder) y tienen sus corazones enternecidos por ella,
y sus mentes ejercitadas en ella,
y sus pensamientos y meditaciones guiados por ella--estos
han llegado al misterio de la comunión del evangelio.
Sí, estos han llegado a la bendita unidad en la que no hay pelea, riña, disputa,
contención, traición, guerras, crueldad o violencia,
porque todos están sintiendo una misma cosa, aprendiendo de un mismo maestro,
siguiendo un mismo guía, a saber, la gracia y Espíritu de Dios.
Y aunque tienen diversidad de dones, y han alcanzado diferentes medidas de fe, gracia,
conocimiento, crecimiento y salvación en el mismo Espíritu,
y aunque algunos son como un pie, otros como una mano, ojo, oído y boca, aun así,
todos son miembros de un solo cuerpo.
El más común tiene unidad con el más noble, el mayor con el menor,
el más pequeño con el más grande, y el más fuerte con el más débil.
Tampoco hay discordia o divisiones en este cuerpo
que está bien concertado y unido entre sí,
del cual Cristo es la unción, el aceite, la cabeza y el maestro.

Esta unidad celestial es el antitipo o cumplimiento de la túnica de Cristo,
que no tenía costura, sino que era de un solo tejido de arriba abajo,
la cual los soldados no partieron, desmenuzaron o dividieron,
sino que echaron suertes sobre ella.
Y es el cumplimiento de esa ley que prohibía tejer lino con lana,
y sembrar semillas mezcladas.

Ahora bien, no hay concordia entre la luz y las tinieblas, entre el pecado y la justicia,
entre Cristo y Belial.
Estas cosas son de una naturaleza diferente y contraria, y por lo tanto no pueden unirse,
no pueden estar de acuerdo, aunque están cerca una de otra, sembradas en un mismo campo.
Dios ha sembrado una buena semilla en el campo de la humanidad;
el enemigo ha sembrado una mala semilla.
En muchos esta mala semilla ha echado raíces y brotado por encima de la buena Semilla,
incluso entre aquellos que profesan ser cristianos.
De aquí surge y crece toda voluntad perversa, envidia, odio, contienda, crueldad,
violencia, derramamiento de sangre, guerras y homicidios en el mundo,
y hasta que la cabeza de esta mala semilla no solo sea herida,
sino desarraigada del corazón del hombre (por la Semilla de la promesa que Dios ha sembrado),
todas estas cosas crecerán y aumentarán. De hecho,
estos efectos malignos nunca cesarán hasta que la causa sea removida y quitada,
como el verdadero cristiano sabe muy bien por experiencia.

Ahora bien, los verdaderos cristianos,
a medida que viven y permanecen en esta Semilla pura e interna de luz, vida,
espíritu y verdad, tienen unidad los unos con los otros, y comunión con Dios.
Ellos son los hermanos que habitan juntos en armonía, lo cual es hermoso contemplar,
quienes tienen un mismo sentir y un mismo corazón,
y tienen sus mentes y corazones siempre gobernados,
regidos y ordenados por el buen Espíritu de Dios.
Cuando cada uno vive en este orden y lo guarda,
y se mantiene bajo este gobierno celestial, no pueden evitar vivir juntos en unidad,
en amor, en buena voluntad, en paz, en concordia y acuerdo celestial,
cada uno dentro de sí mismo, con Dios, y el uno con el otro,
y en amor hacia toda la humanidad.
Aquí está el fin de las contiendas, guerras y peleas,
tanto internamente como externamente.
Y este es el tiempo y estado en que los instrumentos de guerra y crueldad
son convertidos en instrumentos para cosas necesarias (Isaías 2:4).

Cualquiera que quiera permanecer en esto, no puede adiestrarse más para la guerra,
según la bendita visión y promesa de Isaías, ese profeta del evangelio.
Aquí se siente a Jerusalén como una morada de quietud,
estando sus habitantes establecidos en paz y justicia,
lejos de la opresión. De estos ha sido removida la causa de guerra y opresión,
que es tener malos pensamientos, hablar iniquidad y hacer mal.
En verdad,
cada uno debe conocer y experimentar esto antes de que pueda ser establecido en la paz,
antes de que pueda sentir la paz de Dios (que sobrepasa
todo entendimiento) guardando su corazón y mente,
y gobernando en su corazón, y antes de que pueda experimentar la abundancia de esta paz,
y lo que significa recrearse en ella--como está escrito:
"`Los mansos heredarán la tierra, y se recrearán con abundancia de paz.`"^
footnote:[Salmos 37:11]

¡Oh, este es un estado de bendición en verdad!
Todos esperen poseerlo y disfrutarlo cada vez más. En verdad,
este es el bendito fin del evangelio de paz, y de la religión cristiana.
Mi clamor al Señor es que todos los que profesan esto lleguen a heredar la paz,
justicia y gozo en el hombre interior,
incluso a acostarse en esa paz donde no hay quien pueda espantar,
y a morar en ese monte santo donde no hay ningún destruidor,
y a habitar en esa cuidad cuyo arquitecto y constructor es Dios.
¡A Él sea la alabanza y la gloria por siempre!

[.centered]
=== Una Pocas Palabras Añadidas para el Lector Sensible

Tú que despertaste del sueño de la muerte, y te levantaste de la tumba del pecado,
y del mar de corrupción, y que tienes tus sentidos espirituales ejercitados,
de modo que puedes oír, ver,
gustar y tocar las cosas de Dios--tú sabes bien cuál es el bendito
fin de todas las palabras y escritos de los hombres santos,
y de todos sus testimonios y declaraciones, que han procedido del amor de Dios.
En verdad, tú sabes que todo esto fue dado para que aquellos que todavía no son santos,
que todavía andan vagando en y tras la vanidad de sus propias mentes,
pensamientos e imaginaciones, sobre las montañas estériles, como ovejas sin pastor,
puedan ser reunidos y traídos de regreso a casa, al verdadero redil de descanso.
Solo aquí pueden encontrar seguridad, paz y satisfacción para sus almas cansadas,
las cuales por mucho tiempo han andado perdidas en lugares desolados, buscando descanso,
pero sin encontrar ninguno, gastando su tiempo, esfuerzo y dinero en lo que no aprovecha,
ni alimenta, ni nutre para vida eterna.
Dirigir a estos viajeros errantes, ambulantes,
cargados e insatisfechos al camino de descanso y paz,
es el bendito fin de todas las palabras y escritos sagrados,
para que así los hombres puedan llegar a poseer,
disfrutar y heredar las cosas de las cuales otros han hablado y escrito.
Sin esto todo lo que escuchemos, leamos, busquemos, inquiramos, trabajemos,
todo lo que nos esforcemos, todo el tiempo y dinero que gastemos, no servirá de nada.

Ahora bien, es el alma del hombre la que carece de descanso,
y la que se ha ido de su centro y ha perdido su estancia, habitación y morada en Dios.
Y en este estado, la pobre humanidad está cargada de innumerables pensamientos,
imaginaciones, estratagemas e invenciones, deseos y metas, y es arrastrada por todo esto,
tanto judíos como gentiles, profesantes y profanos, sobre la faz de toda la tierra.
Porque en todas las sectas y tipos de religión,
los que son sinceros y devotos se han propuesto este
objetivo con la práctica de su religión,
a saber, obtener un estado de alegría y felicidad al final.
Muchos son los caminos, medios, preceptos, prescripciones,
direcciones y observaciones que los hombres se dan y reciben entre ellos,
y que se imponen y persuaden unos a otros (y algunas
veces se obligan unos a otros con violencia),
todos pensando e imaginando que ese estado de alegría y felicidad
se alcanza por andar en estos caminos y medios de ellos,
y usarlos.
Pero en esta era (como en la antigüedad),
los guías y maestros del pueblo hacen que ellos se extravíen,
los hacen errar y desviarse del camino correcto del
Señor. Ellos mismos erran en la visión,
en el juicio y en el entendimiento,
y hacen que todos los que los siguen y obedecen hagan lo mismo,
porque son guías sin experiencia, y vigilantes ciegos,
y son como el ciego que guía al ciego, los cuales ambos caen juntos en el hoyo.

Ahora bien, el camino para la felicidad eterna es solo uno,
tanto para el judío como para el gentil, y ese camino es Cristo,
quien es la sabiduría y poder de Dios, la verdad y la vida;
y la aparición de este Cristo de Dios es dentro de los hombres, en sus corazones.
Su primera aparición es como una luz que resplandece en las tinieblas,
y como un Espíritu puro y sin mancha que no consiente ningún mal,
sino que reprueba y convence a todos los que son hallados en él. Ahora bien,
todos los que escriben o hablan de parte de Dios, y por el bien de la humanidad,
convierten y dirigen las mentes de los hombres a esta luz o Espíritu,
y se esfuerzan por persuadirlos a considerar Sus reprensiones
de instrucción como el camino de la vida,
y a obedecer Su consejo y enseñanza como el único medio de salvación. En verdad,
esta es la manera de regresar a la piedra de la cual fueron cortados,
y al hueco de la cantera del cual fueron arrancados, a su habitación y morada en Dios.

Muchos miles en esta isla, y en otros lugares,
pueden dar testimonio de que este es el único camino
y medio que Dios ha designado para la recuperación,
regreso y restauración del hombre perdido,
y que todos los otros caminos y medios (en los cuales ellos habían
estado cansándose a sí mismos) no les sirvieron de nada.
Pero al andar en este camino celestial, a saber, la luz,
el Espíritu y la gracia de Dios en el interior, y al aprender de la unción interna,
ellos sienten que la salvación ha venido a su casa,
y que los rodea como muros y antemuro.
Estos experimentan el cumplimiento de esa profecía divina:
"`Mi pueblo habitará en morada de paz, en habitaciones seguras,
y en recreos de reposo,`"^
footnote:[Isaías 32:18]
y "`No se ofuscarán entonces los ojos de los que ven,
y los oídos de los oyentes oirán atentos.
Y el corazón de los necios entenderá para saber,
y la lengua de los tartamudos hablará rápida y claramente.`"^
footnote:[Isaías 32:3-4]
Estos son los benditos efectos de andar en el camino y senda de justicia,
del cual un remanente es testigo vivo en este día,
el cual puede alabar y magnificar el nombre del Señor en el sentido de estas cosas.

Pero ninguno disfrutará este estado de bendición, ni habitará en esta morada celestial,
salvo en la medida que su mente sea ejercitada verdaderamente por y en la luz del Señor,
porque al caminar y permanecer en ella, estos llegarán a tener sus mentes establecidas,
afirmadas y puestas en Aquel quien en verdad es la única ancla de Su pueblo,
y la roca de Su heredad.

En verdad, nada puede encontrarse arriba en los cielos, ni abajo en la tierra,
que sea capaz de satisfacer la mente del hombre o de establecerla en las cosas de Dios,
salvo el Señor. La mente o alma del hombre es más
noble y excelente que todas las cosas visibles,
de modo que ninguna de ellas es capaz de llenar o satisfacer su alma,
o establecer su mente.
Aunque posea el mundo entero para sí mismo, aun así,
al final no podrá evitar clamar y confesar junto con el antiguo predicador:
"`Vanidad de vanidades, todo es vanidad y aflicción de espíritu.`"^
footnote:[Eclesiastés 1:2, 12:8]
Pero el placer,
la paz y el contentamiento se encuentran y disfrutan
cuando se tiene la mente puesta en el Señor,
de acuerdo al testimonio del profeta Isaías, que dijo en el nombre del Señor:
"`Tú guardarás en completa paz a aquel cuya mente está puesta en Ti.`"^
footnote:[Isaías 26:3 Traducción Literal del Inglés]
Esta es una verdad que nadie conoce sino aquel que la tiene.
Puede escribirse, leerse o decirse fácilmente,
pero gozar de la experiencia de ser guardados en completa paz es más que palabras.
Es el fin, suma y sustancia de todo lo que puede decirse o hacerse,
y es la recompensa que los justos reciben directamente de la mano de Dios.
Es el fin de todos los santos deseos y respiraciones al Señor. Es el fin
de la predicación del evangelio de paz y salvación--a saber,
conocer, sentir y experimentar la paz de Dios guardando el corazón y la mente,
y gobernando en el interior.

Este es un estado de bendición en verdad, digno de ser esperado y buscado fervientemente,
por todos aquellos que lo han visto y probado, y que están en el camino que conduce a él,
aunque todavía no hayan llegado.
Sigue adelante en el nombre del Señor, es decir, en la Luz,
que es el nombre por el cual Él se nos ha revelado en esta era.
Por esta luz tú viste la condición errante e inestable de tu mente,
y la multitud de tus pensamientos, imaginaciones e invenciones.
Ahora persevera en ella y no solo te volverás un hijo de ella,
sino que también crecerás y pasarás del estado de niño al estado de joven,
anciano y padre.
Mantén la fe,
y cree firmemente en que eso que te muestra la condición errante e inestable de tu mente,
será para ti como el cayado del pastor,
y en su debido tiempo te llevará de regreso al redil del descanso.
La misma luz santa que descubre tus pensamientos y enemigos internos, y te los muestra,
también, por el resplandor de su nacimiento, los dispersará y destruirá por ti,
y te llevará a ese estado que tu alma desea, anhela y busca, es decir,
a la presencia del Señor, donde hay plenitud de gozo,
y donde corre el torrente de delicias.
Aquí se experimenta la siega y el volver con regocijo,
y el cántico por el júbilo del corazón, y aquí se siente el gozo de la salvación de Dios.
La luz bendita de Dios, o Hijo de justicia, en quien has creído,
es el único camino para poseer y heredar estas cosas, y caminar,
permanecer y perseverar en esto es el único medio.
No hay otro camino o medio designado por Dios para restaurar o restablecer
al hombre en ese estado de sencillez que una vez tuvo en el paraíso,
y que perdió por la transgresión.

Pero todos los que no caminen, permanezcan y perseveren en este camino,
después de haber llegado a él,
nunca alcanzarán ese bendito fin por el cual la luz
ha aparecido y resplandecido en ellos.
Porque un simple conocimiento de la verdad,
y una profesión de que la luz y Espíritu de Dios está en el interior,
para nada aprovecha, si ellos no caminan en la luz, ni son guiados o dirigidos por ella.
Más bien,
esto provoca el ardor de Su ira y venganza sobre la cabeza
de aquellos que "`conocen la voluntad de su señor,
y no hacen conforme a ella,`"^
footnote:[Lucas 12:47]
quienes hablan y profesan bien, pero se encuentran haciendo el mal,
y por lo tanto ponen una piedra de tropiezo en el camino del ciego,
y hacen que el camino de la verdad y el nombre del Señor (con el
cual se ha dado a conocer en esta era) sean blasfemados,
por causa de sus obras impías bajo una profesión de piedad,
y bajo una cubierta de justicia.
Sobre los tales su perdición no se duerme.

Y esto les testifico y declaro a todas las personas
a quienes les puedan llegar estas líneas,
que además podría servirles como una precaución y advertencia:
que si alguno de ellos se encuentra con alguien que tenga el nombre,
la forma y la profesión de un Cuáquero, quien en su conducta, transacciones, negocios,
comercios y asuntos, su sí no es sí, ni su no es no,
sino que rompe su palabra y sus promesas,
es necesario que se cuide de ese hombre de una manera especial y que lo mire como alguien
que actúa de forma falsa y engañosa con los principios santos de la verdad,
y como un hipócrita bajo la profesión de la misma.
Aquel que es falso para con Dios, no puede ser sincero para con los hombres.
Es mejor que confíen y le den crédito a un pagano o a un incrédulo que a uno como este.
En verdad,
no hay iniquidad mayor que la que se comete bajo una cubierta de religión.
Los que ganan credibilidad y reputación por usar esta cubierta,
y toman el dinero de viudas y de huérfanos en sus manos,
y crean grandes comercios por mar y por tierra,
están entre la peor clase de ladrones y estafadores,
y el gemido de los pobres, huérfanos y viudas clama fuertemente contra ellos.
Este es un testimonio breve que surge en mi corazón en contra de este tipo de iniquidad,
por el cual he aliviado un poco mi mente,
y en la verdad sigo siendo un amigo de todos los hombres.
