== Con Respecto a la Vida, Estado y Gozo de un Cristiano Verdadero

La vida de un cristiano, de un israelita en quien no hay engaño,
es una vida de inocencia, paz y contentamiento,
donde la quietud y la verdadera satisfacción abundan en el hombre interior,
de modo que nadie puede hacerle daño. Vive en el temor de Dios,
que le enseñó a apartarse de la iniquidad, y que ahora lo preserva fuera de la misma.
Ama a Dios y a su prójimo, y no siente odio por ningún hombre,
y por eso no teme lo que le pueda hacer el hombre.
Se le da su pan, y sus aguas son seguras.
Si tiene esposa o hijos, casa o tierra, o abundancia de grano, vino y aceite,
los considera como cosas de abajo, y por lo tanto no pone su corazón y afecto en ellas.
Las considera tal como son, y las ama en su lugar, pero no más que a Cristo.
En verdad, él ama al Señor por encima de todas las cosas,
y ama mantener su conciencia sin ofensa hacia Dios y hacia el hombre.
Si no puede disfrutar sus posesiones y relaciones de acuerdo con la voluntad de Dios,
está listo y dispuesto a dejarlas, y puede decir como dijo Job, "`Jehová dio,
y Jehová quitó; sea el nombre de Jehová bendito.`"^
footnote:[Job 1:21]

El verdadero cristiano no tiene temor de malas noticias,
y la agitación de los vientos y el rugido del mar no lo sorprenden ni lo espantan.
Él vive la vida de la fe, que le da victoria y lo capacita para vencer todas las cosas.
Mantiene puesto el escudo de la fe y la coraza de justicia, y la espada del Espíritu, y,
por lo tanto, siempre está armado contra todos los asaltos del mundo,
de la carne y del diablo.
Él experimenta el nombre del Señor como una torre fuerte, como un escudo,
como una adarga, como un muro de defensa,
y está preparado para sufrir y soportar todas las cosas como un buen soldado,
con su semblante firme y con una determinación santa.
Y aunque pueda ser considerado por los hombres como uno que Dios ha herido y olvidado,
y que no es digno de vivir sobre la tierra, aun así,
él disfruta de consolación celestial, de tranquilidad pura en su mente,
de refrescamiento, consuelo y gozo en el hombre interior.
Está escrito que "`toda gloriosa en su interior es la hija del Rey,`"^
footnote:[Salmo 45:13 Reina Valera de Gómez]
y todas las cosas que le suceden o que le pueden
suceder a un cristiano en este lado de la tumba,
no son dignas de ser comparadas con la gloria que es y será revelada
en él. Y aún si no hubiera recompensa al otro lado de la tumba,
él no cambiaría su vida y condición ni por toda la gloria,
las riquezas y la excelencia que el mundo le pueda ofrecer,
porque las ve y las considera todas como vanidad y aflicción de espíritu, sí,
menos que nada y tan vacías como la vanidad.
Habiendo encontrado la perla preciosa, que los cerdos menosprecian,
él está dispuesto a dejar todo por ella, porque conoce su virtud, riquezas y poder.
Él les dice adiós a todos los tesoros y deleites temporales de Egipto,
escogiendo más bien sufrir aflicción y persecución por el bien de la justicia,
que gozar de los placeres que los príncipes tienen en palacios.
De esta manera él tiene gran ganancia incluso en esta vida;
tiene cien veces más en este lado de la tumba,
y encuentra por experiencia que ese dicho es verdadero:
"`Gran ganancia es la piedad acompañada de contentamiento; la piedad para todo aprovecha,
pues tiene promesa de esta vida presente, y de la venidera.`"^
footnote:[1 Timoteo 6:6, 4:8]

Así que,
aunque el cristiano verdadero parezca (según el juicio de los que
son sabios en su propia opinión) perder el disfrute de su vida,
honor, riquezas, ganancias, placer, preferencia, relaciones, etc., es todo lo contrario,
porque él encuentra el verdadero disfrute de todas estas cosas.
De hecho, en la verdadera negación de sí mismo, disfruta todas estas cosas,
y es capaz de decir como Pablo le dijo a los Corintios
(hablando de sí mismo y de otros cristianos):
"`como entristecidos, mas siempre gozosos; como pobres, mas enriqueciendo a muchos;
como no teniendo nada, mas poseyéndolo todo; he aprendido a contentarme,
cualquiera que sea mi situación. Sé vivir humildemente, y sé tener abundancia;
donde quiera y en todas las cosas.`"^
footnote:[2 Corintios 6:10; Filipenses 4:11-12 Reina Valera 1602 Purificada]
Y donde hay un verdadero contentamiento, no hay carencia, ni pobreza, ni tristeza,
salvo aquella que se convierte en abundancia, riqueza y gozo.
Esto hace que el cristiano verdadero se regocije en la tristeza y cante en la cárcel.
Esto convierte un calabozo en un palacio, y el cautiverio y las cadenas en libertad.
Esto convierte la pobreza en riqueza, la pérdida en ganancia,
y las tinieblas en luz delante de él. Estas cosas y muchas otras
más son las virtudes y poderosas operaciones de la perla preciosa,
la piedrecita blanca, la piedra escogida y preciosa, la piedra principal del ángulo,
que los sabios edificadores desechan, con la que ellos tropiezan,
y la cual no quieren usar en su edificación. Pero
para el cristiano verdadero esta roca es preciosa.
Cristo es su fundamento, y también su piedra angular, la cabeza del ángulo.
Él es como un tesoro que es mejor que montañas de oro.
Es como una roca de la cual mana el agua de vida que forma el torrente
de delicias--el torrente que nunca deja de correr a la diestra de Dios.
Estas cosas son experimentadas y disfrutadas por
el cristiano verdadero a medida que llega a la meta,
al supremo llamamiento de Dios en Cristo Jesús,
y también por aquellos que están verdaderamente viajando en el camino.
Pero los simples profesantes, o cristianos de nombre, no saben nada de estas cosas.

La vida,
las riquezas y el disfrute de un cristiano son experiencias internas y escondidas.
En verdad, su vida está escondida con Cristo en Dios,
y nadie la conoce sino aquel que la tiene.
Su ciudadanía es con Dios en el cielo, y su tesoro está arriba, donde él camina y mora,
y donde se sienta en lugares celestiales con Cristo Jesús, su Salvador,
el cual le ha sido hecho sabiduría, justicia, santificación y redención, y no solo eso,
sino que también ha llegado a ver cuál es la comunión del
misterio escondido desde el principio del mundo en Dios.
Él ha llegado a saber que el Señor es uno,
y uno Su nombre (Zacarías 14:9). Él ha llegado a ser parte de un cuerpo, un Espíritu,
una misma esperanza, una fe, un bautismo, un camino, una verdad, una vida,
un Dios y Padre de todos, el cual es sobre todos, y por todos y en todos.
Este es el bendito fin de todas las apariciones,
manifestaciones y dispensaciones (bajo todos los diferentes nombres y diversas
operaciones) del Dios único y eterno para con la humanidad desde la caída,
que han sido mencionadas a lo largo de las Sagradas Escrituras.
En verdad, esto es experimentado por el cristiano verdadero,
quien realmente disfruta el fin por el que Pablo dobló sus
rodillas y oró al Padre de nuestro Señor Jesucristo,
de quien toma nombre toda familia en los cielos y en la tierra.

Ahora bien,
el cristiano verdadero llegará a experimentar la
realidad de estar muerto y enterrado con Cristo,
y de haber resucitado con Él,
y no solo sentirá que está buscando esas cosas que son de arriba,
sino también el haberlas encontrado.
Él conocerá y experimentará a Cristo en todos Sus oficios: como un mediador,
reconciliador, intercesor, pacificador,
sanador de la herida y reparador de la brecha que hizo el primer
Adán. Él será experimentado como un Espíritu vivificante,
como el Señor del cielo, como un rey, sacerdote y profeta, como un salvador,
santificador y redentor,
como un purificador y como Aquel que pone fin al pecado y trae la justicia perdurable.
Él será experimentado como un Sumo Sacerdote que presenta la esposa a Dios sin mancha,
ni arruga, ni cosa semejante.
Y cuando Él es experimentado de esta manera,
ejecutando todos estos oficios en y por Su pueblo,
entonces estos sienten que Él está sentado a la diestra de Dios,
que ha acabado la obra que el Padre le dio que hiciese,
que ha puesto todo debajo de Sus pies y que ha restaurado
todas las cosas a su orden primitivo.
Sí, entonces Él también será experimentado como Aquel que le entrega el reino al Padre,
para que Dios sea todo en todos.
Aquí se siente que el primero es el último, y el último el primero;
que el principio es el fin, y el fin el principio.
Y aquí está el descanso celestial con Aquel que no tiene principio ni fin; sí,
un reposo en un cese puro y celestial de toda la actividad, voluntad,
deseo y pensamiento del yo.
Y aunque se alcance un estado de inocencia, o un yo inocente,
y se llegue a tener una voluntad inofensiva, aun así, esto no debe actuar, obrar, querer,
desear ni pensar por sí mismo (como bien sabe el cristiano
verdadero que ha viajado y que tiene experiencia),
sino que debe decirle a su Padre: "`No se haga mi voluntad, sino la tuya.`"^
footnote:[Lucas 22:42]
Aquí el hombre recibe sabiduría para labrar y guardar el huerto,
y poder y fuerza para resistir y vencer la serpiente en el paraíso,
y al dragón en el cielo, y para mantener su morada en Jerusalén, la ciudad celestial,
que desciende del Cielo, de Dios, cuyos muros son salvación,
y cuyas puertas son alabanza para siempre.
