== Un Consejo para el Viajero Cristiano

¿Has puesto tu mano en el arado?
¡No mires atrás! Mantenla ahí hasta que el campo sea arado,
y los espinos y abrojos sean desarraigados y destruidos,
para que la semilla pueda crecer en ti hasta la perfección. ¿Has
sentido que el reino (y el poder en que él consiste) es como una
pequeña levadura escondida en tres medidas de harina?
¡No estorbes su operación,
deja que leude toda la masa! ¿Conoces el campo donde está escondida la perla preciosa?
¡Entonces cava profundamente y encuéntrala!
Y cuando la hayas encontrado, vende todo y cómprala,
y entonces serás el mercader sabio en verdad.

¿Has viajado fuera de Egipto, a través del Mar Rojo y el desierto?
¿Has sentido la diestra del Señor acompañándote y sosteniéndote en tus pruebas,
tentaciones y dificultades con las que te has encontrado?
Mantente aferrado a este brazo y poder que te ha llamado,
guiado y sostenido hasta este punto, y este te llevará a la tierra prometida,
y no sólo eso, sino que también te dará una posesión en ella, y destruirá a tus enemigos,
los que antes la poseían. Se te dará una casa que tú no edificaste,
una viña que no plantaste y un pozo que no cavaste que saltará en ti para vida eterna.
Te sentarás debajo de tu propia viña y debajo de tu propia higuera,
y te acostarás en un lugar donde no habrá quien te amedrente.
Bendita será tu canasta y tu artesa de amasar, bendito serás en tu salir y en tu entrar,
cuando te acuestes y cuando te levantes.
Estas bendiciones sin duda te alcanzarán, a medida que ames el día de las pequeñeces,
y sigas fielmente al Señor,
el cual se te ha aparecido con Su luz y gracia para darte una perfecta redención y restauración,
y la salvación eterna.
Yo digo, tú ciertamente disfrutarás y heredarás estas cosas,
y no sólo recibirás la añadidura de virtud, conocimiento, dominio propio, paciencia,
etc. a tu fe, sino que también recibirás el fin de tu fe.
Porque la fe y la esperanza tienen un fin, y es una bendición recibirlo--a saber,
la salvación. Y en verdad, sólo aquel que persevere hasta el fin podrá ser salvo,
es decir, hasta el fin de la obra de Dios, la nueva creación de Dios en Cristo Jesús.

=== Los Días de la Creación Experimentados Internamente.

Muchos empiezan bien, e incluso hacen un buen progreso, mas sin embargo quedan cortos.
Pueden llegar a experimentar la obra del primer día, (léase Génesis 1), es decir,
el Espíritu de Dios moviéndose sobre la faz de las aguas, la aparición de la Luz,
la separación de la luz de las tinieblas,
e incluso hasta llamar a la luz día y a las tinieblas noche.
En realidad, esto es más que lo que todos los hombres sabios,
prudentes y religiosos de este mundo pueden conocer o hacer,
quienes son todos como aguas, sobre las que se sienta la ramera,
y los cuales desprecian e ignoran el movimiento del Espíritu de Dios.
Ellos además aborrecen la aparición de la luz, así que,
cuando ella resplandece en las tinieblas, no es separada de las tinieblas,
y ellos que están en las tinieblas no la comprenden,
ni pueden darles nombres correctos a las cosas, ni llamar a la luz día,
ni a la oscuridad noche.
Sí, ellos están tan errados y equivocados que hacen de la luz tinieblas,
y de las tinieblas luz.
Todos los hombres en la caída son propensos a hacer esto, y, de hecho, lo están haciendo,
bajo el antiguo cielo y sobre la antigua tierra.
Esto es algo así como una nota al margen, para aquellos a quienes les concierne.

Pero para continuar,
puede que ellos también experimenten la obra del segundo y tercer día:
la expansión en medio de las aguas, las aguas separadas,
lo seco descubriéndose y produciendo semilla y fruto según su género, lo cual es bueno.
Esto es más que palabras, nombres y creencias.
Estos tienen alguna firmeza, algún fundamento en medio de las aguas.
Son como árboles que dan fruto, y como la tierra que da su producto a aquel que la labra.

En el cuarto día está escrito que "`Dios hizo dos grandes lumbreras;
una para que señorease en el día, y otra para que señorease en la noche`"^
footnote:[Génesis 1:16]
La lumbrera (y su autoridad y gobierno) puede llegar a experimentarse
también. Y así como en la obra del quinto día,
puede que haya una abundante producción y multiplicación,
y que se llegue a volar sobre la tierra en la abierta expansión de los cielos.
Y puede que la obra del sexto día también se experimente, a saber,
ser "`hecho a la semejanza e imagen de Dios,`"^
footnote:[Génesis 1:26]
bendecido y dotado con poder y dominio celestial, sobre todo,
y puesto en un huerto plantado por el Señor. Sí,
puede que se alcance una restauración a la inocencia y rectitud por medio de Cristo,
quien es el poder, luz, amor y sabiduría de Dios.
Sin embargo, hasta en este estado hay peligro.
Hay una tendencia a mirar hacia afuera la belleza de las obras de Dios,
a alimentarse de ellas, a deleitarnos a nosotros mismos con ellas,
o a comer lo que es prohibido,
a menos que nos aferremos y obedezcamos la ley y mandamiento de Dios.

El sol que es puesto en el medio de las obras de
Dios debe gobernar el día y a los hijos del día,
y la luna debe gobernar la noche.
El que tenga sabiduría, entienda.
La voz de la serpiente no debe ser escuchada.
Si deseas mantener tu lugar, y conservar tu morada en el paraíso, en el huerto de Dios,
debes labrarlo y guardarlo.
"`Con toda diligencia guarda tu corazón.`"^
footnote:[Proverbios 4:23 LBLA]
Si algo aparece allí que pudiera tentarte y seducirte a quebrar la ley de Dios,
asegúrate de no darle tu consentimiento.
Asegúrate de no hacerlo, más bien permanece en el gobierno y dominio que Dios te ha dado,
no sólo sobre la serpiente, sino sobre todas las obras de Sus manos.
Cuando estés haciendo esto,
entenderás la razón del celo y temor de Dios que sentía el apóstol,
quien le dijo a aquellos que habían sido llevados a un buen estado,
incluso hasta ser desposados con un solo esposo para ser presentados como una
virgen pura en Cristo (que es un estado muy cercano a la unión matrimonial):
2 Corintios 11:2-3^
footnote:[Reina Valera 1602 Purificada]
"`Mas temo,`" dijo él, "`que en alguna manera,
como la serpiente engañó a Eva con su astucia, así sean corrompidas vuestras mentes,
de la simplicidad que es en Cristo.`"

Ahora considera:
son aquellos que están desposados y ataviados como una esposa para su marido,
los que han llegado a la simplicidad que es en Cristo,
y han escapado de la corrupción que está en el mundo a causa de las concupiscencias,
y quienes han sido restaurados, redimidos y traídos de regreso a la inocencia,
y tienen una morada en el huerto de Dios--es a estos que la serpiente busca seducir,
engañar y hacer caer otra vez.
Por lo tanto, mantente en el dominio, poder y sabiduría con los cuales Dios te ha dotado,
armado y rodeado, y la serpiente nunca prevalecerá contra ti.
No mires al primer Adán, salvo para tomarlo como una advertencia,
no sea que recibas la misma recompensa.
Más bien mira al Segundo Adán, en quien la serpiente, el engañador, el diablo,
no tiene parte.
Aunque el diablo tiene poder para tentar en el paraíso, y para hacer guerra en el cielo,
y para aparecer delante del Señor y acusar, aun así,
nunca pudo engañar o vencer al Segundo Adán,
ni prevalecer contra Él. Y tampoco podrá prevalecer
contra ti mientras te mantengas aferrado a Él,
armado con Su poder y con tu mente puesta en Dios tu Salvador.

Esto te llevará a un estado más seguro que el que tuvo el primer Adán,
y que por un tiempo disfrutó en el paraíso. De hecho,
no sólo podrás llegar a ser tomado y puesto en el huerto de Dios para labrarlo y guardarlo,
sino que también podrás llegar a tener una morada en Su casa, en el templo de Dios,
y ser como una columna en él,
y nunca más salir de allí. Tú podrás ser como el Monte de Sion que no puede ser movido.
Tu corazón podrá afirmarse con la gracia, y cimentarse en la roca que es más alta que tú,
contra quien ni los engaños ni las seducciones del enemigo, por un lado,
ni las tormentas ni las tempestades que él envía por el otro, pueden prevalecer.
Tú llegarás a ver ojo a ojo, y a conocer como fuiste conocido.
Llegarás a experimentar que el Señor es uno, y uno Su nombre,
que el primero es el último, y el último el primero,
y a sentir tu descanso celestial con Él, quien no tiene principio ni fin,
¡a quien le pertenece la alabanza por los siglos de los siglos!

Este es el bendito fin de la obra de Dios que todos deben experimentar
forjado y cumplido en sí mismos por medio de Cristo,
la luz, poder y sabiduría de Dios.
Pero hay mucho peligro en el camino a este fin, como tú,
quien has sido un viajero en este camino, lo sabes bien.
Hay muchas cosas escritas para tu consuelo y aprendizaje en las Sagradas Escrituras,
y quiero que consideres como una gran misericordia
el beneficio de tenerlas y poder usarlas.
Con respecto a ellas,
está escrito que "`pueden hacer sabio para la salvación por la fe que es en Cristo Jesús.`"^
footnote:[2 Timoteo 3:15-17]
Cristo en verdad es la sabiduría de Dios, el que abre las Escrituras,
el único que lleva al entendimiento verdadero de ellas.
Y es a través de la fe en Él que el hombre de Dios llega a ser hecho perfecto
y a estar enteramente preparado para toda buena obra.
Solamente el hombre de Dios es el que tiene la consolación de las Escrituras,
y la unidad y comunión con los espíritus de los hombres santos que las escribieron.
Solamente él es quien las entiende.
Ellas son como un libro cerrado para el aprendido y para el indocto,
para el profesante (el cristiano de nombre) y para el profano.
Grande es el misterio de la piedad, el cual es revelado a los niños,
y escondido de los sabios y entendidos de este mundo.
Estos hacen un comercio de la historia escrita de la piedad para obtener ganancias deshonestas,
haciendo daño a sus propias almas y a las de otros.

Ahora bien, tierno amigo, con el fin de que seas preservado a salvo en tu camino,
siempre recuerda el consejo de Cristo Jesús: "`Ten cuidado u ora, pues,
que vuestra huida no sea en invierno ni en día de reposo.`"^
footnote:[Mateo 24:20]
Estas dos temporadas son las más peligrosas.
Hay mucho en estas palabras; la sabiduría de Dios las habló,
y sólo aquellos que están dotados con Su sabiduría pueden entenderlas.
Y por esta misma sabiduría, tú podrás ser preservado en y a través del invierno,
y ser capaz de decir: "`Ha pasado el invierno, el verano ha llegado,
y en mi tierra se oye la voz de la tórtola.`"^
footnote:[Cantares 2:11-12]
Y también conocerás al Señor del día de reposo y descansarás en Él,
quien es la morada de Su pueblo en todas las edades y generaciones
¡A Él sea la gloria por siempre y para siempre!

=== El Éxodo Interno de Egipto

De este modo, he mostrado brevemente cómo la obra interna, o nueva creación de Dios,
tiene un paralelo con la historia de la creación externa o antigua,
y qué peligro te asecha cuando eres una planta de Dios, incluso en el paraíso mismo,
el cual el hombre perdió por desobediencia y transgresión.

Tengo también en mi corazón poner delante de ti el método
y orden de la sabiduría de Dios en tu restauración,
y el peligro que te asecha en el camino hacia la misma.
Esto fue representado figurativamente en la historia de Su pueblo
bajo opresión en la tierra de Egipto--el clamor de ellos a Él,
el hecho de que Él descendió a librarlos,
de que les levantó un capitán o líder para sacarlos con mano fuerte,
de que los condujo a través del Mar Rojo,
destruyendo a sus enemigos y trayéndolos a las orillas del otro lado.
Fue demostrado cuando Él les dio un cántico de liberación y salvación,
y los guió a través del desierto, los alimentó con maná y codorniz del cielo,
y con agua que salía de la roca,
cuando iba delante de ellos en una columna de fuego
por la noche y en una columna de nube por el día,
y cuando los llevó al Monte de Sinaí y les dio Sus leyes, estatutos y juicios.
Por la instrucción de Dios, ellos prepararon Su arca, levantaron Su tabernáculo,
asentaron las basas, colocaron las tablas y lo pusieron en sus barras.
Alzaron sus columnas, metieron el arca del testimonio dentro del tabernáculo,
sobre la mesa pusieron en orden los panes, encendieron las lámparas,
y ofrecieron incienso aromático sobre el altar de oro,
de modo que la gloria del Señor apareció en el tabernáculo,
y fue su guía en todos sus viajes.
Esto fue glorioso en su tiempo.
Y sólo el viajero cristiano entiende el antitipo,
o la sustancia a la que todo esto apunta.
Estas cosas fueron grandes ayudas, grandes beneficios y bendiciones,
que los acompañaron en el viaje a la tierra prometida.

Sin embargo, considera lo siguiente: a pesar de todas estas cosas,
y de todas sus experiencias del brazo extendido y el poder y presencia del Señor,
de Sus promesas a los obedientes y Sus advertencias a los rebeldes y desobedientes,
a pesar de todo esto, ellos olvidaron al Señor y se volvieron atrás en sus corazones.
Sí, por incredulidad, murmuración y desobediencia,
cayeron por el camino y nunca entraron al descanso,
a la tierra prometida que fluía leche y miel.
Todos los que salieron de Egipto a través del Mar Rojo (mayores de veinte años,
excepto Josué y Caleb) se desviaron y quedaron cortos.
Y cuando su descendencia llegó a poseer Canaán, la tierra prometida, considera cómo,
con el pasar del tiempo,
ellos también se corrompieron y contristaron al Espíritu
del Señor por causa de sus rebeliones y abominaciones,
no solo antes,
sino también después de que Dios había hecho que Su templo fuese
erigido y amoblado de la manera más magnífica--con vasos de oro,
plata,
bronce y otros ornamentos costosos (que tenían la frase '`Santidad al Señor`' inscrita
en ellos) y con Su propia presencia y aparición también. Después de todo esto,
mediante el pecado y la desobediencia,
ellos se convirtieron en una presa para el destructor, fueron puestos en cautiverio,
y llevados a una tierra extraña.

Estas cosas están escritas para la enseñanza y advertencia del sabio de corazón,
cuyos ojos Dios ha abierto, y a quien Él le ha revelado Su brazo de poder,
y en y por quien ha hecho muchas maravillas.
Sí, estas cosas están escritas para que el hombre no se vuelva otra vez a la locura,
descuido, ligereza, orgullo y rebelión contra el Espíritu de Dios,
y para que ellos no se atavíen a sí mismos con las joyas de Dios,
ni se prostituyan con ellas (como lo hizo Israel),
y así reciban la misma recompensa en el misterio^
footnote:[Nota del Editor: es decir, en un sentido espiritual]
que ellos recibieron en la historia.
En verdad, hay un gran peligro de esto en lo interno,
como entonces lo había en lo externo.

De la misma manera,
ahora voy a hablar de la obra de Dios en la dispensación del Espíritu,
al final de los profetas,
y demostrar que el mismo peligro asecha a aquellos que hoy en día andan en Su camino.
El misterio de la piedad es grande, y el misterio de la iniquidad también lo es,
y bienaventurado eres si permaneces en la luz de Dios que pone de manifiesto a ambos.
No es suficiente sentir que la luz resplandece;
sino que debes también caminar y permanecer en ella, y ser un hijo verdadero de ella.
No es suficiente conocer al Espíritu de la verdad y Su poder;
sino que debes también ser guiado por Él, unirte a Él, volverte uno con Él,
y llevar Sus frutos.
No es suficiente conocer la semilla del reino, y su siembra en ti;
sino que debes también experimentarla quebrando los terrones y creciendo,
no sólo hasta volverse tallo y hoja, sino grano maduro en la espiga.
Y no sólo esto,
sino que además debes sentir que este grano es segado y
recogido en el granero para el uso del Señor de la cosecha.
No es suficiente sentir uno de los días del Hijo del Hombre,
al niño nacido y al Hijo dado;
sino que debes también experimentar el principado que reposa sobre Su hombro,
teniéndolo a Él reinando en tu corazón y a Sus enemigos destruidos,
que son también tus enemigos.

Para alcanzar esto (de acuerdo con las frases usadas en las Sagradas Escrituras),
debe experimentarse al "`Espíritu Santo cubriendo con su sombra,`"^
footnote:[Lucas 1:35]
a "`Cristo siendo engendrado y formado en el interior,`"^
footnote:[Gálatas 4:19]
debe sentirse un dolor de parto para dar a luz,
un nacimiento y un crecimiento de una estatura a otra, de niño a joven,
y de joven a anciano.
Debes padecer con Cristo, tomar Su cruz diariamente y seguirlo,
morir con Él y resucitar con Él, y buscar esas cosas que son de arriba,
donde Cristo está sentado a la diestra de Dios.
Tienes que resucitar con Cristo antes de estar en condiciones
de buscar las cosas que están a la diestra de Dios.
Pero encontrar estas cosas, y estar sentado en lugares celestiales en Cristo Jesús,
y sentarse en el reino con Abraham, Isaac y Jacob, es un estado superior.
Y el estado más grande y superior de todos,
es experimentar que el reino es entregado al Padre, donde Dios se vuelve todo en todos.
Este es el único estado donde hay seguridad, en el que no hay peligro de caer.

Pero hasta que hayas llegado a este estado (aunque seas un discípulo de Cristo,
y seas como una virgen pura y sabia, desposada con Él) debes velar y orar,
manteniendo tu lámpara arreglada y tu antorcha encendida, no sea que entres en tentación;
no sea que te tome el sueño y te duermas y la puerta sea cerrada contra ti.
Porque hay una posibilidad, sí,
un verdadero peligro de caer en todas las condiciones y estaturas,
hasta que entres en el seno de Abraham.
Allí se siente que la sima es puesta.
No hay cambio de estados en ese momento,
como se indica en la parábola de Lázaro y el hombre rico, Lucas 16:26:
"`Una gran sima está puesta entre nosotros y vosotros,
de manera que los que quisieren pasar de aquí a vosotros, no pueden,
ni de allá pasar acá.`" Y para hablar un poco conforme a esta conversación alegórica
entre Abraham y el hombre rico--los que quisieren descender no pueden;
y los que quisieren ascender no pueden.
Uno no puede hacer nada contra la verdad, puesto que está enteramente gobernado por ella,
y completamente enamorado y unido a ella.
Y el otro no puede hacer nada por la verdad,
puesto que está en completa enemistad y dureza de corazón contra ella,
habiendo perdido su día de visitación, y habiendo sido sellado en la oscuridad,
teniendo conciencia de su pérdida.
Porque esto añade grandemente al tormento de los impíos,
contemplar desde lejos el estado bendito de los justos,
y verse a sí mismos en un estado de tormento y miseria,
clamando y orando por misericordia y alivio.
Pero ellos no pueden ser escuchados ni aliviados de su dolor,
porque el sol ya se ha puesto en ellos, y su día se convirtió en completas tinieblas,
las cuales se han vuelto su morada o habitación, donde está el lloro,
el gemido y el crujir de dientes.

Por lo tanto, querido amigo, por lo que te he dicho brevemente,
por el testimonio de las Sagradas Escrituras y por tu propia experiencia,
puedes percibir que no es algo fácil ser un verdadero Cristiano,
y pasar por la obra de regeneración hasta ser una nueva creación de Dios
en Cristo Jesús. No es algo fácil pasar a través de la guerra,
y ser capaz de decir con el apóstol: "`He peleado la buena batalla,
he acabado mi carrera, de ahora en adelante me está guardada la corona de gloria.`"^
footnote:[2 Timoteo 4:7]
Sí, no es fácil llegar a ponerse esta corona,
y ser más que vencedor en Aquel que te ha amado.

Experimentar y disfrutar estas cosas es el fin bendito de todas las dispensaciones
de Dios desde la caída. Porque el que vence es más que vencedor.
Él ha recibido la piedrecita blanca, en donde está escrito el nuevo nombre,
el cual ninguno conoce sino aquel que lo tiene.
Él es el mercader sabio que ha vendido todo y comprado la perla preciosa,
la cual excede todas las demás cosas.
Él tiene el derecho de comer del Árbol de Vida, que crece en medio del huerto.
Él es bendecido con toda bendición espiritual en los lugares
celestiales en Cristo Jesús. Él es un coheredero con Él,
y no sólo eso, sino que ha llegado a la posesión de su herencia.
Este es su estado,
aunque puede que sea recibido por el mundo de la misma manera que recibieron
a Cristo (el capitán de su salvación) y a Sus discípulos.

Por lo tanto, que disfrutes de la luz del rostro de Dios,
que tengas unidad con el Señor y seas un espíritu con Él,
que experimentes la unión de matrimonio (siendo tu marido tu Hacedor),
esto es tu consuelo, tu regocijo,
tu corona y diadema en la prosperidad y en la adversidad, en lo alto y en lo profundo,
en el palacio y en el calabozo, en todas las condiciones, tiempos y lugares.
Tú, que participas de estas cosas, eres el único hombre feliz,
aunque pueda que tus bienes sean despojados,
y tu cuerpo esté en las manos de tus enemigos, aun así,
tú realmente puedes sellar la verdad de ese testimonio de Pablo en Romanos 8:18:
"`Pues tengo por cierto que las aflicciones del tiempo presente no son
comparables con la gloria venidera que en nosotros ha de revelarse.`"
Para ti este tiempo de revelación ha venido.
Tú sientes que el Señor ha llegado, y que Su recompensa está con Él--cien veces más,
incluso ahora en esta vida; y en el siglo venidero la vida eterna.

Gran ganancia es la piedad acompañada de contentamiento,
porque ella tiene las promesas de todas las cosas buenas,
en esta vida presente y en la venidera.
Aquellos que se han entregado a sí mismos (y todas las cosas) a las manos de Dios,
no tienen nada que perder,
no tienen nada de que preocuparse salvo de agradar al Señor.
Y la comida y bebida de estos es hacer Su voluntad,
porque Sus caminos son todos caminos deleitosos, y al final,
no habrá amargura para aquellos que caminan en ellos.

=== Considera y Sé Advertido

Por lo tanto,
considera y sé advertido por los ejemplos dejados en las Sagradas Escrituras.
Siempre recuerda que ellas te hablan de un pueblo que llegó al conocimiento de Dios,
de Sus leyes y ordenanzas, y al modo de adoración que Él mismo ordenó,
el cual le agradaba siempre y cuando se realizara con sinceridad de corazón,
y por esto Sus bendiciones y presencia los acompañaban.
Pero cuando ellos perdieron la sinceridad, rectitud e integridad de corazón,
aunque todavía practicaban y ejecutaban con exactitud la parte externa de la adoración,
aun así, todos sus actos religiosos eran abominación para Él, y Él los rechazaba.
Esto fue testificado por Su profeta Isaías, diciendo:
"`El que sacrifica buey es como si matase a un hombre; el que sacrifica oveja,
como si degollase un perro; el que hace ofrenda, como si ofreciese sangre de cerdo;
el que quema incienso, como si bendijese a un ídolo.`"^
footnote:[Isaías 66:3]
Esto es bastante extraño para aquellos que no conocen la razón verdadera
por la que estos servicios (ordenados por Dios) se volvieron tan abominables
ante los ojos de Aquel que los ordenó. Dios mira el corazón,
lo que está dentro.
Si eso se desvía, si eso se corrompe, degenera, y enamora de la creación,
nada de lo que haga el hombre (en ese estado) Dios lo aceptará como bien hecho.
En este estado,
tanto la justicia del hombre como su iniquidad son abominación para Él. Esto
fue un grave mal en el que cayeron las personas bajo la dispensación de la ley:
que ellos seguían pecando y sacrificando,
pero no escuchaban ni obedecían la voz del Señor. De la misma manera,
en la dispensación del evangelio, incluso en las primeras épocas de esta,
el mismo mal estaba infiltrándose.
Por medio de la predicación de los apóstoles, muchos fueron llevados a creer en Cristo,
y a profesarlo.
Pero pronto sucedió,
que algunos estaban dispuestos a sentarse o descansar en
una profesión y conocimiento de Cristo según la carne,
y a guardar una forma de piedad, pero negar y descuidar el poder.

Los ministros de Cristo en los primeros tiempos tenían una gran labor ante ellos:
En primer lugar, persuadir y convencer a los judíos de que Jesús era el Cristo de Dios,
el Mesías que había sido prometido y profetizado por los santos profetas,
a quienes ellos perseguían y mataban en una época,
pero honraban (al menos con sus labios) y adornaban sus sepulcros en otra.
En segundo lugar, oponerse a la continuación de su adoración en templos, es decir,
las ordenanzas y observaciones que eran sombras y figuras que en un tiempo Dios ordenó,
sacándolos de debajo de ellas y llevándolos a la sustancia señalada por ellas.
Pues ellos tenían que creer en Aquel que es el fin y sustancia de estas,
quien cumplió toda la justicia contenida en la ley, en los profetas y en Juan.

Ahora bien,
cuando habían llevado a las personas a creer que Cristo era el
gran profeta como Moisés que Dios había prometido levantar,
cuán propensos eran muchos de estos creyentes a sentarse en esta creencia,
y contentarse con un conocimiento de Cristo según la carne,
al igual que los judíos que se complacían a sí mismos con el templo del Señor,
y con sus ritos externos, mientras que carecían de la raíz del asunto, a saber,
un corazón recto, quebrantado y contrito,
que es (y siempre ha sido) el único sacrificio en el cual Dios se deleita.
Por lo tanto,
los apóstoles eran constreñidos a testificar contra
el mero conocimiento de Cristo según la carne,
diciendo: "`De aquí en adelante a nadie conocemos según la carne;
y aun si a Cristo conocimos según la carne, ya no lo conocemos así.`"^
footnote:[2 Corintios 5:16]
Ellos predicaban el conocimiento de Cristo según el Espíritu, revelado,
manifestado y conocido por la operación de Su poder y Espíritu en el corazón.
Ellos afirmaban que aquel que no tenía este conocimiento estaba reprobado.
No era suficiente saber que Él nació de la virgen, que creció en sabiduría,
estatura y gracia para con Dios y los hombres, que hizo muchos milagros externos,
predicó muchos sermones excelentes, que dijo muchos preceptos divinos y celestiales,
anduvo por todo lugar haciendo el bien, sufrió por y debido al pecado y a los pecadores,
que murió, resucitó y ascendió a la gloria de Su Padre.
No, en los primeros tiempos no era suficiente conocer
y creer la historia y la verdad de estas cosas,
y tampoco lo es ahora.
En verdad, tú debes también conocerlo y experimentarlo en Su aparición espiritual,
en Su poder y operación interna, y perseverar en esto hasta que se culmine la obra.
Sin esto, serás como un cristiano tradicional que profesa a Cristo,
pero que Dios no acepta,
así como tampoco aceptaba al judío externo cuando
mantenía la práctica externa y la forma de la religión,
y se jactaba del templo del Señor y de su santidad externa,
mientras seguía siendo un templo de inmundicia, suciedad y corrupción en el interior.

Así que, querido amigo y compañero en este viaje,
para que podamos correr hasta el fin de nuestra carrera,
y estar seguros de que obtendremos la corona; para que podamos pelear,
no como aquellos que golpean el aire,
sino como aquellos que siguen adelante venciendo y para vencer,
manteniendo sujeto todo lo que nos evitaría correr bien hasta el fin,
que nos privaría de la corona y nos entregaría a las manos de nuestros enemigos; yo digo,
para que podamos hacer esto, tengamos siempre presente los dichos del apóstol Pablo,
quien fue un viajero sabio y experimentado,
y un ministro competente del nuevo pacto--1 Corintios 9:26-27^
footnote:[Reina Valera de Gomez]
"`Así que, yo de esta manera corro, no como a la ventura; de esta manera peleo,
no como quien golpea el aire, sino que sujeto mi cuerpo, y lo pongo en servidumbre;
no sea que habiendo predicado a otros, yo mismo venga a ser reprobado.`"

En el décimo capítulo él pone como ejemplo a los judíos
que en Moisés fueron bautizados en la nube y en el mar,
y que comieron del alimento espiritual, y bebieron de la bebida espiritual, es decir,
de la roca espiritual que los seguía, cuya roca era Cristo.
Sin embargo, estos fueron vencidos en el desierto, y destruidos por el destructor,
porque cuando ellos comieron y bebieron, se levantaron a jugar, y codiciaron cosas malas.
Él dice que "`estas cosas les acontecieron como ejemplo,
y están escritas para amonestarnos a nosotros,
a quienes han alcanzado los fines de los siglos.
Así que, el que piensa estar firme, mire que no caiga.`"^
footnote:[1 Corintios 10:11-12]
De cuyos dichos, y por nuestra propia experiencia, podemos deducir y concluir,
que es el deber de los que enseñan y predican, de los que oyen y aprenden,
de los que comen y beben, incluso en esta dispensación espiritual,
asegurarse de que corran bien hasta el fin, de que peleen bien hasta el fin,
de que coman y beban dignamente,
no sea que el juicio los alcance mientras la comida está en sus bocas.
Porque algunos, incluso en esta generación, después de haber conocido a Dios,
no lo glorificaron como a Dios, sino que se envanecieron en sus razonamientos,
y su necio corazón los engañó hasta tal punto,
que estando bajo la forma y profesión misma de Cristo en Su aparición y obra en el interior,
ellos se oponen y resisten la cosa misma, tanto en sí mismos como en otros.
Están tan nublados y el misterio de iniquidad ha obrado tanto en ellos,
que no pueden ver ni entender estas cosas.
Pero sin duda,
todos los que hagan que su práctica diaria sea caminar en el temor del Señor,
y mantener sus mentes ejercitadas en Su ley, meditando en Sus misericordias y juicios,
nuevos y antiguos, pasados y presentes, estos escaparán de este grave mal.
Mientras que tú estés haciendo esto,
ningún mal podrá prevalecer contra ti o tomarte desprevenido.

Por lo tanto, querido amigo y lector,
cuyo bien es mi principal objetivo por medio de este escrito,
deseo que seas sobrio y serio al leerlo, como yo lo he sido al escribirlo,
y hallarás beneficio y consuelo ministrados en tu propio pecho.
Y no sólo percibirás y entenderás claramente la diferencia entre leer, escuchar,
profesar y hablar cosas buenas de manera ligera y descuidada,
y poseerlas y disfrutarlas de manera seria y solemne,
sino que también percibirás y entenderás claramente la diferencia entre el principio,
el progreso y el fin de la obra de Dios en la nueva creación, restauración,
regeneración y salvación.

Por lo tanto, te encomiendo de corazón a la gracia de Dios, que lleva a la gloria,
y de un grado de gloria a otro.
En verdad, esta gracia es suficiente para enseñarte todo lo que es bueno,
y preservarte de todo mal, y en ella permanezco siendo tu amigo y hermano,

[.signed-section-signature]
William Shewen
